### PR TITLE
postgresql_privs: add trust_input parameter

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql_privs: add trust_input parameter

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
```plugins/module_utils/database.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @andytom @kostiantyn-nemchenko @tcraxs @sebasmannem

**Comment by Andersson007** [comment]
@andytom thanks for reviewing!

**Comment by gundalow** [comment]
rebuild_merge

**Comment by Andersson007** [comment]
@andytom thanks for reviewing!

**Comment by Andersson007** [comment]
merged into master

**Pull request merged**
