### PR TITLE
Fix a bunch of potential security issues (secret leaking)

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
These were reported by @russoz in #1725 and checked by @relrod.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/modules/cloud/misc/ovirt.py                           
plugins/modules/cloud/oneandone/oneandone_firewall_policy.py  
plugins/modules/cloud/oneandone/oneandone_load_balancer.py    
plugins/modules/cloud/oneandone/oneandone_monitoring_policy.py
plugins/modules/cloud/oneandone/oneandone_private_network.py  
plugins/modules/cloud/oneandone/oneandone_public_ip.py        
~~plugins/modules/cloud/oneandone/oneandone_server.py~~
plugins/modules/cloud/rackspace/rax_clb_ssl.py                
plugins/modules/cloud/spotinst/spotinst_aws_elastigroup.py    
plugins/modules/identity/keycloak/keycloak_client.py          
plugins/modules/monitoring/librato_annotation.py              
plugins/modules/monitoring/pagerduty_alert.py                 
plugins/modules/net_tools/nios/nios_nsgroup.py                
plugins/modules/packaging/os/pulp_repo.py                     
plugins/modules/source_control/gitlab/gitlab_runner.py        
plugins/modules/storage/ibm/ibm_sa_host.py

### CODE REVIEW

**Comment by russoz** [comment]
Hi @felixfontein thanks for putting this together. I am still entangled in other things, will be able to put some time into this on Sunday.

**Comment by felixfontein** [comment]
I'm currently planning on releasing new community.general versions on Monday, with all the fixes contained. So everyone, please check until then if this PR looks good to you! I'll merge somewhen on Monday morning (European time).

**Comment by ndclt** [comment]
Ok for keycloak file. @felixfontein Thanks for the work.

**Comment by russoz** [comment]
hi @felixfontein  thanks once again.

LGTM

**Comment by russoz** [comment]
where are my manners? Thanks to @relrod , @gundalow @ndclt and whoever else spent time checking those lines.

**Review by gundalow — APPROVED** [review]
Thank you for doing these

**Comment by felixfontein** [comment]
While working on https://github.com/ansible/ansible/pull/73508 I found a new batch of (potential) secrets that are leaked; see 647cb18b4131105cfa6cc8aa860dc6755d8b3d12. Please help checking these as well!

This unfortunately also results in a **breaking change**: the utm_proxy_auth_profile module returns one of its options, `frontend_cookie_secret`, which is now marked `no_log=True`, which causes the return value to be replaced by a placeholder string. Since I'm not 100% sure whether `frontend_cookie_secret` is really a secret (I couldn't find any information on this), any feedback w.r.t. this would be really appreciated!

**Comment by billdodd** [comment]
Checked redfish_command.py. LGTM.
Thanks for finding and fixing these!

**Comment by zanssa** [comment]
@felixfontein, Checked pagerduty and gitlab modules. LGTM.

Thanks for working on this!

**Comment by felixfontein** [comment]
I'm merging this now. If anyone finds a `no_log=True` that shouldn't be there later, please create a new PR to remove it. Thanks!

**Review by Andersson007 — APPROVED** [review]
LGTM, thanks for doing this!

**Review by dericcrago — APPROVED** [review]

**Comment by felixfontein** [comment]
@russoz @ndclt @gundalow @billdodd @zanssa @Andersson007 @dericcrago thanks for reviewing this!

**Pull request merged**
