### PR TITLE
removed unreachable code

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
Clearing up some PyCharm inspection code results

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/modules/cloud/misc/rhevm.py
plugins/modules/cloud/ovh/ovh_ip_failover.py
plugins/modules/source_control/bitbucket/bitbucket_pipeline_variable.py

### CODE REVIEW

**Review by felixfontein — COMMENTED** [review]
Can you add a changelog fragment?

**Comment by russoz** [comment]
@felixfontein apparently the CI is having a hard time finding a `coverage` package for Python 2.6

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@russoz thanks for these improvements!

**Comment by felixfontein** [comment]
> @felixfontein apparently the CI is having a hard time finding a `coverage` package for Python 2.6. At times... (other times it seems to work fine...)

Yeah, I'm pretty sure it's related to PyPi's SNI brownouts combined with the way ansible-test tries to fix that. I'll bring that up in #ansible-devel...

**Pull request merged**
