### PR TITLE
Remove deprecated features, bump version to 6.0.0

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Preparing the 6.0.0 release. To be merged noce 5.8.0 is out (see https://github.com/ansible-collections/community.general/issues/582#issuecomment-1264404378).

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME
various

### CODE REVIEW

**Comment by felixfontein** [comment]
@russoz would be glad if you could take a look at this PR. I intend to merge it on Tuesday while working on the 5.8.0 release.

**Review by russoz — COMMENTED** [review]
Ok, first round: the PR seems to be internally consistent. Now reviewing whether there's anything else left behind.

**Comment by russoz** [comment]
There's a comment referring to 6.0.0 in:

https://github.com/felixfontein/community.general/blob/pr/felixfontein/5326/plugins/lookup/dig.py#L35

But it looks like the parameter choice has been already removed.

**Comment by russoz** [comment]
Other than that, LGTM

**Comment by felixfontein** [comment]
> There's a comment referring to 6.0.0 in:
> 
> https://github.com/russoz-ansible/community.general/blob/main/plugins/lookup/dig.py#L35
> 
> But it looks like the parameter choice has been already removed.

That choice was already removed from `main` in #4613.

**Comment by russoz** [comment]
Yeah, I figured. I was just creating an opportunity for fixing (or removing) that comment. TBH, not entirely sure we should bother.

**Comment by felixfontein** [comment]
@russoz the comment is intentionally there, so that users whose playbooks suddenly stop working can find a reference on what happened :)

**Comment by felixfontein** [comment]
@russoz thanks for reviewing this!

**Pull request merged**
