### PR TITLE
10.0.0: CmdRunner: remove deprecated feature

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY

Remove deprecated feature from CmdRunner

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/module_utils/cmd_runner.py

### CODE REVIEW

**Comment by felixfontein** [comment]
The change looks good, but it needs a changelog fragment :)

**Comment by russoz** [comment]
That was fast

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
I was waiting for CI to pass to take another look, and then I saw you asked for a review anyway ;)

**Comment by felixfontein** [comment]
@russoz thanks!

**Pull request merged**
