### PR TITLE
Restore removed google modules

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
These should be in google.cloud according to ansible-base's ansible_builtin_runtime.yml, but since these are modules not by Google and they are not in that collection (which is almost completely auto-generated), it is unlikely that they will ever appear in that collection. This reverts the according commits from #504 to restore them to this collection.

CC @gundalow @relrod

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
gcp_backend_service
gcp_forwarding_rule
gcp_healthcheck
gcpubsub
gcpubsub_facts
gcpubsub_info

### CODE REVIEW

**Comment by gundalow** [comment]
@rambleraptor are you OK with these modules staying in community.general, or do you want to add them into the Google collection?

**Comment by rambleraptor** [comment]
I'd prefer for these to stay in community.general.

**Comment by gundalow** [comment]
@rambleraptor thanks for the quick reply.

**Comment by felixfontein** [comment]
@gundalow thanks for handling this!

**Pull request merged**
