### PR TITLE
BOTMETA.yml: Add a new maintainer of parted module

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/community.general/pull/773

BOTMETA.yml: Add a new maintainer of parted module

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
`.github/BOTMETA.yml`

### CODE REVIEW

**Comment by Andersson007** [comment]
@jake2184 could you please approve the PR?

**Comment by jake2184** [comment]
Approved. 
shipit

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@jake2184 thanks a lot!

**Comment by Andersson007** [comment]
@jake2184 thanks for becoming a maintainer of the module!

**Pull request merged**
