### PR TITLE
pids - refactor module to make version-based behavior consistent

### PR DESCRIPTION
**Pull request by Ajpantuso**
##### SUMMARY
Cleaning up the `pids` module to ensure version specific operations are consistent across the module.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
plugins/modules/system/pids.py

##### ADDITIONAL INFORMATION
- Decouples `psutil` via an adapter with overridable behavior based on the package version
- Added the version based logic for the `pattern` execution path
- Tested locally with `psutils` versions `<2.0.0`, `>=2.0.0,<5.3.0`, and `>=5.3.0`

### CODE REVIEW

**Comment by Ajpantuso** [comment]
@felixfontein Can you expand on your [request](https://github.com/ansible-collections/community.general/pull/2808#issuecomment-895745156) for installing `psutil >= 5.7.0` when available? Would that just be adding `setup_psutil` to the integration tests and including that in the `pids` meta? If so I can work on that as well.

**Comment by felixfontein** [comment]
> @felixfontein Can you expand on your [request](https://github.com/ansible-collections/community.general/pull/2808#issuecomment-895745156) for installing `psutil >= 5.7.0` when available? Would that just be adding `setup_psutil` to the integration tests and including it in the `pids` meta? If so I can work on that as well.

Right now, the integration tests (tests/integration/targets/pids/tasks/main.yml) install `psutil < 5.7.0` on all targets to avoid pip failures with *some* targets. It would be better to install `psutil` without the version restriction on all targets except for those where this restriction is actually needed.

**Comment by felixfontein** [comment]
CC @dagwieers

**Comment by Ajpantuso** [comment]
> It would be better to install `psutil` without the version restriction on all targets except for those where this restriction is actually needed.
>

Done.

**Comment by felixfontein** [comment]
Thanks!

If nobody complains, I'll merge next week.

**Comment by felixfontein** [comment]
recheck

**Comment by felixfontein** [comment]
@Ajpantuso thanks for improving this!

**Pull request merged**
