### PR TITLE
BOTMETA.yml: add a new team member to team_virt

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
BOTMETA.yml: add a new team member to team_virt

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`.github/BOTMETA.yml`

### CODE REVIEW

**Comment by Andersson007** [comment]
See the last comment https://github.com/ansible-collections/community.general/pull/811

**Comment by Andersson007** [comment]
cc @Aversiste

**Comment by Andersson007** [comment]
@Aversiste please approve the PR if this is ok for you

**Review by Aversiste — APPROVED** [review]

**Review by felixfontein — APPROVED** [review]

**Comment by gundalow** [comment]
@joshainglis @karmab Hi, looks like you've got some extra help with the [GitLab issues and PRs](https://github.com/ansible-collections/community.general/labels/gitlab).

**Pull request merged**
