### PR TITLE
Sort parameters in gitlab_group to aid in adding more params

### PR DESCRIPTION
**Pull request by julien-lecomte**
##### SUMMARY

Sort parameters in gitlab_group to aid in adding more params.

No changes to code.

##### ISSUE TYPE
- Refactoring Pull Request

##### COMPONENT NAME

gitlab_group

### CODE REVIEW

**Comment by russoz** [comment]
Hi @julien-lecomte thanks for the contribution!

This is a Documentation PR, it should have no changelog fragment. Other than that, it LGTM

**Comment by julien-lecomte** [comment]
@russoz, I've removed the changelog fragment.

**Comment by russoz** [comment]
Hi @julien-lecomte I had looked in the phone only, and missed it: you **did** add more parameters. I apologise, I failed to see that the first time - the PR title seemed to indicate that it was just about sorting the parameters. Well, my bad, I should have taken a closer look earlier on.

If you could please add the changelog fragment (mea culpa mea culpa)

**Comment by julien-lecomte** [comment]
@russoz If I did, then I screwed up with another MR that I'm preparing. Let me fix that, and ping you when fixed. This MR should not have extra parameters.

**Comment by julien-lecomte** [comment]
@russoz I've redone the steps and ended up with the same file. In other words, I don't believe I've added any extra parameter. If I did, please indicate which one(s).

**Comment by russoz** [comment]
In that case, it seems I screwed up multiple times reading this PR. My apologies.

@felixfontein this PR only changes the order in which options appear in the docs and the order in which local vars are assigned with those options. From where I'm standing I don't think a changelog frag is needed here, please let us know otherwise.

**Comment by felixfontein** [comment]
I'm fine with no changelog entry here.

**Comment by felixfontein** [comment]
(If this is ready for reviewing, please remove the draft status.)

**Review by russoz — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@julien-lecomte thanks for your contribution!
@russoz thanks for reviewing!

**Pull request merged**
