### PR TITLE
Document attributes (_info and _facts modules for now)

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Uses attributes to document module capabilities.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
all modules

### CODE REVIEW

**Comment by felixfontein** [comment]
You can find the rendered docs here: https://ansible.fontein.de/collections/community/general/#modules

Examples:
- https://ansible.fontein.de/collections/community/general/cloud_init_data_facts_module.html#attributes
- https://ansible.fontein.de/collections/community/general/ali_instance_info_module.html#attributes

**Comment by felixfontein** [comment]
bot_skip

**Comment by felixfontein** [comment]
CI failure is unrelated.

**Review by briantist — APPROVED** [review]

**Comment by felixfontein** [comment]
@briantist thanks!!!

**Pull request merged**
