### PR TITLE
BOTMETA.yml: add new maintainer to gitlab team

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
BOTMETA.yml: add new maintainer to gitlab team

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
.github/BOTMETA.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
Hi @sh0shin ! Thank you for your great contribution to GitLab related modules.
Would you like to become a team member in BOTMETA.yml?
It means that you'll get indirect commit to the related stuff via Andible Bot.
Your `shiptit`, `LGTM`, `+1` will be counted by the bot for automerge (2 votes from the team members are required).
The bot will also notify you via email when GitLab-related issues / PRs are created, so you don't miss the opportunity to say your opinion on them:)
What do you think?
If it sounds interesting, please approve this PR.
If you're not interested, please say it and we close the issue.

Thanks once more for the regular and great contribution!

**Review by sh0shin — APPROVED** [review]

**Comment by sh0shin** [comment]
@Andersson007 I'm happy to be onboard 8)_

**Comment by Andersson007** [comment]
@sh0shin that's great! Thank you:)
cc @felixfontein

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@sh0shin awesome, thanks a lot for doing this! You will probably shortly receive first GitHub notifications when the bot starts CC'ing you in all GitLab related issues / PRs. (I'm not sure how often the new bot iterates over all issues and PRs.)

@Andersson007 thanks for asking and creating the PR!

**Comment by Andersson007** [comment]
@felixfontein thanks for approving and merging!

**Comment by russoz** [comment]
Hi @sh0shin thanks for joining the band, happy to have more hands on deck. You might want to take a look at the issues raised on gitlab modules.

**Pull request merged**
