### PR TITLE
Prepare 10.0.0 release

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
~~Currently contains #8918. Will rebase once that's merged.~~

This PR should be rebased and merged once community.general 9.5.0 has been released. From that point on, `main` will start preparing 10.0.0.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
various

### CODE REVIEW

**Comment by ptoscano** [comment]
As part of "remove deprecated modules and plugins", you can also drop `plugins/module_utils/redhat.py` entirely, as the dropped `rhn_register` module is its only consumer.

**Comment by felixfontein** [comment]
@ptoscano we haven't deprecated that, and it's part of the [public API](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#standards-for-developing-module-and-plugin-utilities) of the collection.

**Comment by felixfontein** [comment]
Oh, I see that it *is* marked as deprecated.

**Comment by ptoscano** [comment]
LGTM for `rhn_register`, `rhn_channel`, and `module_utils.redhat`.

(that said, since I was the one deprecating them for removal in the first place, obviously I'm biased here)

**Comment by felixfontein** [comment]
Good point, I added a reminder to #7434, in case someone really wants to keep the module(s). (They can always be resurrected under another name and/or in another collection if needed, anyway...)

**Comment by felixfontein** [comment]
@ptoscano thanks for reviewing!

**Pull request merged**
