### PR TITLE
proxmox inventory plugin: deprecate `want_proxmox_nodes_ansible_host` option's default value

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
See https://github.com/ansible-collections/community.general/pull/4432#discussion_r843187850.

CC @ralgar @ilijamt 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
proxmox inventory plugin

### CODE REVIEW

**Comment by ilijamt** [comment]
yeah, looks good, it's time we deprecate this.

**Comment by ilijamt** [comment]
shipit

**Review by russoz — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@ilijamt @russoz thanks for reviewing this!

**Pull request merged**
