### PR TITLE
BOTMETA.yml: update team_gitlab

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/community.general/pull/1829#issuecomment-822515614

##### ISSUE TYPE
- Docs Pull Request
- 
##### COMPONENT NAME
BOTMETA.yml

### CODE REVIEW

**Comment by felixfontein** [comment]
@metanovii can you please approve this PR to confirm?

**Comment by metanovii** [comment]
LGTM
right?

**Review by metanovii — APPROVED** [review]

**Comment by felixfontein** [comment]
@metanovii thanks!

**Comment by felixfontein** [comment]
Manual backport to stable-1 in #2300.

**Pull request merged**
