### PR TITLE
gitlab_project_variable: added support for variable_type

### PR DESCRIPTION
**Pull request by axarriola**
##### SUMMARY
Added support for variable_type (env_var or file).

##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME
gitlab_project_variable.py

##### ADDITIONAL INFORMATION
Tested with gitlab-ce 12.9.2

### CODE REVIEW

**Comment by markuman** [comment]
@axarriola Can you please append the integration test witha `variable_type: 'file'` case?

**Comment by axarriola** [comment]
@markuman of course, just pushed the addition.

**Comment by gundalow** [comment]
@markuman When you get a chance, would you be able to retest this?

**Comment by markuman** [comment]
@gundalow @axarriola 

the CI test is failing 

```

TASK [gitlab_project_variable : add one variable with variable_type file] ******
changed: [testhost] => {"changed": true, "project_variable": {"added": ["my_********"], "removed": [], "untouched": [], "updated": []}}

TASK [gitlab_project_variable : append one variable state must be changed] *****
fatal: [testhost]: FAILED! => {
    "assertion": "gitlab_project_variable_state.project_variable.added[0] == \"my_file\"",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}

PLAY RECAP *********************************************************************
testhost                   : ok=51   changed=18   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by felixfontein** [comment]
@markuman I've relaunched CI, let's see whether it now also fails here.

**Comment by felixfontein** [comment]
Oh, just realized the tests are `unsupported`, never mind what I wrote :)

**Comment by axarriola** [comment]
@markuman Thank you for sharing the results.
Seems the test is failing because the variable name is returned masked: `my_********`
I will delete that condition line from the `assert that` block and leave the other conditions.

**Comment by markuman** [comment]
> Seems the test is failing because the variable name is returned masked: `my_********`
> I will delete that condition line from the `assert`

You should then check for the masked value.  
Is a variable type `file` always masked?

**Comment by axarriola** [comment]
@markuman After reading gitlab_project_variable.py again, I realized nothing should be masking part of the variable name, so it was ansible that was masking "file". I changed the name of the variable in the tests and now the assertion conditions can be executed correctly.

**Comment by markuman** [comment]
CI passes now.

<details><summary>log</summary>
<p>

#### for the record

```
m@hell:~/dev/ansible/collections/ansible_collections/community/general$ ansible-test integration -v --python 3.7 gitlab_project_variable --docker --allow-unsupported
Falling back to tests in "tests/integration/targets/" because "roles/test/" was not found.
Run command: docker images quay.io/ansible/default-test-container:1.10.1 --format '{{json .}}'
Run command: docker pull quay.io/ansible/default-test-container:1.10.1
1.10.1: Pulling from ansible/default-test-container
5667fdb72017: Pulling fs layer 
d83811f270d5: Pulling fs layer 
ee671aafb583: Pulling fs layer 
7fc152dfb3a6: Pulling fs layer 
3fb967a6fd03: Pulling fs layer 
b3e63023ca5f: Pulling fs layer 
653cb3e65dbf: Pulling fs layer 
f4712b586375: Pulling fs layer 
d696ed7812f8: Pulling fs layer 
29bf28764f14: Pulling fs layer 
47d7edb3c2b7: Pulling fs layer 
07550ad4f6e4: Pulling fs layer 
7e79526e64c5: Pull complete 
4fffb32882b7: Pull complete 
fc7a38b06f4e: Pull complete 
6d9d912e060e: Pull complete 
5dd542dd28d9: Pull complete 
cef8beb99552: Pull complete 
bd5557e101ad: Pull complete 
e057c20fabdd: Pull complete 
d16059cdae2e: Pull complete 
431e42d906a3: Pull complete 
7a0fd3b1d7c3: Pull complete 
aacdb6db0c8c: Pull complete 
2e7f04ae8c8b: Pull complete 
4cd343027a44: Pull complete 
0b4379883f90: Pull complete 
3d9d6d9dfc91: Pull complete 
57d6314bd293: Pull complete 
774036afeb7f: Pull complete 
54b10f0e1645: Pull complete 
78cf439d9fdb: Pull complete 
36e5e20969c7: Pull complete 
4b19ac3f17a8: Pull complete 
Digest: sha256:954c4edffb0905df64e23c8611b1c4a62db9af13062f51cad5b658e727238d41
Status: Downloaded newer image for quay.io/ansible/default-test-container:1.10.1
quay.io/ansible/default-test-container:1.10.1
Scanning collection root: /home/m/dev/ansible/collections/ansible_collections
Including collection: community.general (3570 files)
Creating a payload archive containing 9310 files...
Created a 12776445 byte payload archive containing 9310 files in 2 seconds.
Run command: docker run --detach --volume /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged=false --security-opt seccomp=unconfined --volume /var/run/docker.sock:/var/run/docker. ...
Run command: docker exec -i e2d64738c7abd2e70cdc84c1d94944b3d7f9b90333b539076ab61aae4c202e36 dd of=/root/docker.sh bs=65536
Run command: docker exec e2d64738c7abd2e70cdc84c1d94944b3d7f9b90333b539076ab61aae4c202e36 /bin/bash /root/docker.sh
Run command: docker exec -i e2d64738c7abd2e70cdc84c1d94944b3d7f9b90333b539076ab61aae4c202e36 dd of=/root/ansible.tgz bs=65536
Run command: docker exec e2d64738c7abd2e70cdc84c1d94944b3d7f9b90333b539076ab61aae4c202e36 mkdir /root/ansible
Run command: docker exec e2d64738c7abd2e70cdc84c1d94944b3d7f9b90333b539076ab61aae4c202e36 tar oxzf /root/ansible.tgz -C /root/ansible
Run command: docker exec e2d64738c7abd2e70cdc84c1d94944b3d7f9b90333b539076ab61aae4c202e36 /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible/ansible_collections/community/g ...
Falling back to tests in "tests/integration/targets/" because "roles/test/" was not found.
Run command: /usr/bin/python3.7 -m pip.__main__ install --disable-pip-version-check -c /root/ansible/test/lib/ansible_test/_data/requirements/constraints.txt -r /root/ansible ...
Ignoring coverage: markers 'python_version > "3.7"' don't match your environment
Ignoring cryptography: markers 'python_version < "2.7"' don't match your environment
Ignoring deepdiff: markers 'python_version < "3"' don't match your environment
Ignoring jinja2: markers 'python_version < "2.7"' don't match your environment
Ignoring urllib3: markers 'python_version < "2.7"' don't match your environment
Ignoring sphinx: markers 'python_version < "2.7"' don't match your environment
Ignoring wheel: markers 'python_version < "2.7"' don't match your environment
Ignoring yamllint: markers 'python_version < "2.7"' don't match your environment
Ignoring paramiko: markers 'python_version < "2.7"' don't match your environment
Ignoring pytest: markers 'python_version < "2.7"' don't match your environment
Ignoring pytest: markers 'python_version == "2.7"' don't match your environment
Ignoring pytest-forked: markers 'python_version < "2.7"' don't match your environment
Ignoring requests: markers 'python_version < "2.7"' don't match your environment
Ignoring virtualenv: markers 'python_version < "2.7"' don't match your environment
Ignoring pathspec: markers 'python_version < "2.7"' don't match your environment
Ignoring pyopenssl: markers 'python_version < "2.7"' don't match your environment
Ignoring pyyaml: markers 'python_version < "2.7"' don't match your environment
Ignoring pycparser: markers 'python_version < "2.7"' don't match your environment
Ignoring xmltodict: markers 'python_version < "2.7"' don't match your environment
Ignoring lxml: markers 'python_version < "2.7"' don't match your environment
Ignoring pyvmomi: markers 'python_version < "2.7"' don't match your environment
Ignoring setuptools: markers 'python_version <= "2.7"' don't match your environment
Ignoring ordereddict: markers 'python_version < "2.7"' don't match your environment
Requirement already satisfied: cryptography in /usr/local/lib/python3.7/dist-packages (from -r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 1)) (2.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from -r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 2)) (2.10.3)
Requirement already satisfied: junit-xml in /usr/local/lib/python3.7/dist-packages (from -r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 3)) (1.8)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from -r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 5)) (5.1.2)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from cryptography->-r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 1)) (1.12.0)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.7/dist-packages (from cryptography->-r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 1)) (1.1.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.7/dist-packages (from cryptography->-r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 1)) (1.13.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->-r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 2)) (1.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi!=1.11.3,>=1.8->cryptography->-r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 1)) (2.19)
Run command: /usr/bin/python3.7 -m pip.__main__ check --disable-pip-version-check
Run command: /usr/bin/python3.7 /root/ansible/test/lib/ansible_test/_data/yamlcheck.py
Running gitlab_project_variable integration test role
Injecting "/tmp/python-lott2qly-ansible/python" as a symlink to the "/usr/bin/python3.7" interpreter.
Run command: ansible-playbook gitlab_project_variable-_db73xno.yml -i inventory -v
Using /root/ansible/ansible_collections/community/general/tests/output/.tmp/integration/gitlab_project_variable-oc4z6hix-ÅÑŚÌβŁÈ/tests/integration/integration.cfg as config file
[WARNING]: running playbook inside collection community.general

PLAY [testhost] ****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [testhost]

TASK [gitlab_project_variable : Install required libs] *************************
ok: [testhost] => {"changed": false, "cmd": ["/usr/local/bin/pip3", "install", "python-gitlab"], "name": ["python-gitlab"], "requirements": null, "state": "present", "stderr": "WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n", "stderr_lines": ["WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.", "You should consider upgrading via the 'pip install --upgrade pip' command."], "stdout": "Requirement already satisfied: python-gitlab in /usr/local/lib/python3.6/dist-packages (1.12.1)\nRequirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from python-gitlab) (1.12.0)\nRequirement already satisfied: requests>=2.4.2 in /usr/local/lib/python3.6/dist-packages (from python-gitlab) (2.22.0)\nRequirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.4.2->python-gitlab) (1.24.3)\nRequirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.4.2->python-gitlab) (2.5)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.4.2->python-gitlab) (2019.9.11)\nRequirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.4.2->python-gitlab) (3.0.4)\n", "stdout_lines": ["Requirement already satisfied: python-gitlab in /usr/local/lib/python3.6/dist-packages (1.12.1)", "Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from python-gitlab) (1.12.0)", "Requirement already satisfied: requests>=2.4.2 in /usr/local/lib/python3.6/dist-packages (from python-gitlab) (2.22.0)", "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.4.2->python-gitlab) (1.24.3)", "Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.4.2->python-gitlab) (2.5)", "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.4.2->python-gitlab) (2019.9.11)", "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.4.2->python-gitlab) (3.0.4)"], "version": null, "virtualenv": null}

TASK [gitlab_project_variable : purge all variables for check_mode test] *******
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": ["my_file"], "untouched": [], "updated": []}}

TASK [gitlab_project_variable : add a variable value in check_mode] ************
changed: [testhost] => {"changed": true, "project_variable": {"added": ["ACCESS_KEY_ID"], "removed": [], "untouched": [], "updated": []}}

TASK [gitlab_project_variable : check_mode state must be changed] **************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : apply add value from check_mode test] **********
changed: [testhost] => {"changed": true, "project_variable": {"added": ["ACCESS_KEY_ID"], "removed": [], "untouched": [], "updated": []}}

TASK [gitlab_project_variable : state must be changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : test new format] *******************************
ok: [testhost] => {"changed": false, "project_variable": {"added": [], "removed": [], "untouched": ["ACCESS_KEY_ID"], "updated": []}}

TASK [gitlab_project_variable : state must be not changed] *********************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : change protected attribute] ********************
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": [], "untouched": [], "updated": ["ACCESS_KEY_ID"]}}

TASK [gitlab_project_variable : state must be changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : revert protected attribute] ********************
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": [], "untouched": [], "updated": ["ACCESS_KEY_ID"]}}

TASK [gitlab_project_variable : state must be changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : change masked attribute] ***********************
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": [], "untouched": [], "updated": ["ACCESS_KEY_ID"]}}

TASK [gitlab_project_variable : state must be changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : revert masked attribute by not mention it] *****
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": [], "untouched": [], "updated": ["ACCESS_KEY_ID"]}}

TASK [gitlab_project_variable : state must be changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : revert again masked attribute by not mention it (idempotent)] ***
ok: [testhost] => {"changed": false, "project_variable": {"added": [], "removed": [], "untouched": ["ACCESS_KEY_ID"], "updated": []}}

TASK [gitlab_project_variable : state must be not changed] *********************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : set both (masked and protected) attribute] *****
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": [], "untouched": [], "updated": ["ACCESS_KEY_ID"]}}

TASK [gitlab_project_variable : state must be changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : set again both (masked and protected) attribute (idempotent)] ***
ok: [testhost] => {"changed": false, "project_variable": {"added": [], "removed": [], "untouched": ["ACCESS_KEY_ID"], "updated": []}}

TASK [gitlab_project_variable : state must not be changed] *********************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : revert both (masked and protected) attribute] ***
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": [], "untouched": [], "updated": ["ACCESS_KEY_ID"]}}

TASK [gitlab_project_variable : state must be changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : change a variable value in check_mode again] ***
ok: [testhost] => {"changed": false, "project_variable": {"added": [], "removed": [], "untouched": ["ACCESS_KEY_ID"], "updated": []}}

TASK [gitlab_project_variable : check_mode state must not be changed] **********
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : apply again the value change from check_mode test] ***
ok: [testhost] => {"changed": false, "project_variable": {"added": [], "removed": [], "untouched": ["ACCESS_KEY_ID"], "updated": []}}

TASK [gitlab_project_variable : state must not be changed] *********************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : purge all variables at the beginning] **********
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": ["ACCESS_KEY_ID"], "untouched": [], "updated": []}}

TASK [gitlab_project_variable : set two test variables] ************************
changed: [testhost] => {"changed": true, "project_variable": {"added": ["ACCESS_KEY_ID", "SECRET_ACCESS_KEY"], "removed": [], "untouched": [], "updated": []}}

TASK [gitlab_project_variable : set two test variables state must be changed] ***
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : re-set two test variables] *********************
ok: [testhost] => {"changed": false, "project_variable": {"added": [], "removed": [], "untouched": ["ACCESS_KEY_ID", "SECRET_ACCESS_KEY"], "updated": []}}

TASK [gitlab_project_variable : re-set two test variables state must not be changed] ***
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : edit one variable] *****************************
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": [], "untouched": ["SECRET_ACCESS_KEY"], "updated": ["ACCESS_KEY_ID"]}}

TASK [gitlab_project_variable : edit one variable state must be changed] *******
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : append one variable] ***************************
changed: [testhost] => {"changed": true, "project_variable": {"added": ["some"], "removed": [], "untouched": ["ACCESS_KEY_ID", "SECRET_ACCESS_KEY"], "updated": []}}

TASK [gitlab_project_variable : append one variable state must be changed] *****
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : re-set all variables] **************************
ok: [testhost] => {"changed": false, "project_variable": {"added": [], "removed": [], "untouched": ["ACCESS_KEY_ID", "SECRET_ACCESS_KEY", "some"], "updated": []}}

TASK [gitlab_project_variable : re-set all variables state must not be changed] ***
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : set one variables and purge all others] ********
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": ["ACCESS_KEY_ID", "SECRET_ACCESS_KEY"], "untouched": ["some"], "updated": []}}

TASK [gitlab_project_variable : set one variables and purge all others state must be changed] ***
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : only one variable is left] *********************
ok: [testhost] => {"changed": false, "project_variable": {"added": [], "removed": [], "untouched": ["some"], "updated": []}}

TASK [gitlab_project_variable : only one variable is left state must not be changed] ***
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : test integer values] ***************************
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": [], "untouched": [], "updated": ["some"]}}

TASK [gitlab_project_variable : only one variable is left state must be changed] ***
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : test float values] *****************************
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": [], "untouched": [], "updated": ["some"]}}

TASK [gitlab_project_variable : only one variable is left state must be changed] ***
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : delete the last left variable] *****************
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": ["some"], "untouched": [], "updated": []}}

TASK [gitlab_project_variable : no variable is left state must be changed] *****
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : add one variable with variable_type file] ******
changed: [testhost] => {"changed": true, "project_variable": {"added": ["my_test_var"], "removed": [], "untouched": [], "updated": []}}

TASK [gitlab_project_variable : append one variable state must be changed] *****
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : change variable_type attribute] ****************
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": [], "untouched": [], "updated": ["my_test_var"]}}

TASK [gitlab_project_variable : state must be changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : revert variable_type attribute] ****************
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": [], "untouched": [], "updated": ["my_test_var"]}}

TASK [gitlab_project_variable : state must be changed] *************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : delete the variable_type file variable] ********
changed: [testhost] => {"changed": true, "project_variable": {"added": [], "removed": ["my_test_var"], "untouched": [], "updated": []}}

TASK [gitlab_project_variable : no variable is left state must be changed] *****
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [gitlab_project_variable : check that no variables are left] **************
ok: [testhost] => {"changed": false, "project_variable": {"added": [], "removed": [], "untouched": [], "updated": []}}

TASK [gitlab_project_variable : check that no variables are untoucheded state must be changed] ***
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY RECAP *********************************************************************
testhost                   : ok=60   changed=21   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Run command: docker exec e2d64738c7abd2e70cdc84c1d94944b3d7f9b90333b539076ab61aae4c202e36 tar czf /root/output.tgz --exclude .tmp -C /root/ansible/ansible_collections/communi ...
Run command: docker exec -i e2d64738c7abd2e70cdc84c1d94944b3d7f9b90333b539076ab61aae4c202e36 dd if=/root/output.tgz bs=65536
Run command: tar oxzf /tmp/ansible-result-lkwd6rv9.tgz -C /home/m/dev/ansible/collections/ansible_collections/community/general/tests
Run command: docker rm -f e2d64738c7abd2e70cdc84c1d94944b3d7f9b90333b539076ab61aae4c202e36

```

</p>
</details>

**Comment by markuman** [comment]
LGTM

**Comment by markuman** [comment]
shipit

**Comment by felixfontein** [comment]
rebuild_merge

**Comment by felixfontein** [comment]
Looks like `rebuild_merge` isn't properly working. I've triggered a manual rebuild, and will merge once it passes.

**Comment by felixfontein** [comment]
@axarriola thanks for implementing this!
@markuman thanks for reviewing and testing!

**Pull request merged**
