### PR TITLE
Try to make pids test more stable

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
The pids integration test regularly fails on macOS. Adds a small delay to hopefully make it more stable.

##### ISSUE TYPE
- Test Request

##### COMPONENT NAME
tests/integration/targets/pids/tasks/main.yml

### CODE REVIEW

**Comment by felixfontein** [comment]
Ironically, the failed CI runs were totally unrelated (there were some galaxy connection problems).

**Comment by felixfontein** [comment]
Re-started the tests three times, always succeeded.

**Review by gundalow — APPROVED** [review]
Nice, thanks

**Comment by felixfontein** [comment]
@gundalow thanks for reviewing and merging!

**Pull request merged**
