### PR TITLE
fix passwordstore.py to be compatible with gopass versions

### PR DESCRIPTION
**Pull request by yeoldegrove**
##### SUMMARY
`gopass show` is deprecated and executing it will result in these messages:
```
gopass mypass
DEPRECATION WARNING: Use gopass show
mysecret
```
The `DEPRECATION WARNING: Use gopass show` will be written to a file looked up by `passwordstore.py`.

This commit fixes it by using `pass show` instead of `pass`.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
passwordstore.py

### CODE REVIEW

**Comment by felixfontein** [comment]
Thanks for the contribution!

1. Does `show` work with every supported version of the tool, or is some logic necessary so it continues to work with all older versions as well?
2. Every change needs a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to).

**Comment by yeoldegrove** [comment]
> 1. Does `show` work with every supported version of the tool, or is some logic necessary so it continues to work with all older versions as well?
AFAIK `show` has worked for a long time in `pass`. At leas in the last years where I used it.

**Comment by yeoldegrove** [comment]
>     2\. Every change needs a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to).

added the fragment as requested

**Comment by felixfontein** [comment]
@yeoldegrove thanks for fixing this!

**Pull request merged**
