### PR TITLE
Functions added to support firmware update operations to HPE iLO.

### PR DESCRIPTION
**Pull request by rajeevkallur**
##### SUMMARY
Functions added to support firmware update operations to HPE iLO.

##### ISSUE TYPE
Utility functions to support FW update operations to HPE iLO

##### COMPONENT NAME
ilo_redfish_utils

##### ADDITIONAL INFORMATION
Unit testing completed.

### CODE REVIEW

**Comment by felixfontein** [comment]
BTW, have you thought about creating a HPE iLO specific collection instead of adding all these modules to community.general? (Maybe it would also make sense to create a Redfish specific collection, assuming someone wants to maintain it...)

**Comment by rajeevkallur** [comment]
> BTW, have you thought about creating a HPE iLO specific collection instead of adding all these modules to community.general? (Maybe it would also make sense to create a Redfish specific collection, assuming someone wants to maintain it...)

@felixfontein ,  we are adding this to ilo_redfish_command which is kind of ilo specific only.  Is there anything else you are trying to tell me?

**Comment by rajeevkallur** [comment]
> > BTW, have you thought about creating a HPE iLO specific collection instead of adding all these modules to community.general? (Maybe it would also make sense to create a Redfish specific collection, assuming someone wants to maintain it...)
> 
> @felixfontein , we are adding this to ilo_redfish_command which is kind of ilo specific only. Is there anything else you are trying to tell me?

@felixfontein ,  You mean to say something like collection hpe.ilo  in the namespace hpe?  It is possible, hpe already has namespace in ansible.  But code may become repetitive... I will think about it.

**Comment by rajeevkallur** [comment]
Closing this as we wont be merging this with community.general due to the nature of this feature only used by hpe.  It will be part of hpe.ilo collection which will be published soon.

**Pull request closed without merging**
