### PR TITLE
add description and hookscript parameters to proxmox LXC container

### PR DESCRIPTION
**Pull request by Links2004**
##### SUMMARY
adding missing options for the Proxmox LXC container.
 - hookscript
 - description

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
proxmox

##### ADDITIONAL INFORMATION
no big change only added 2 new parameters.
example:
```
- proxmox:
    vmid: 100
    node: uk-mc02
    api_user: root@pam
    api_password: 1q2w3e
    api_host: node1
    password: 123456
    hostname: example.org
    ostemplate: 'local:vztmpl/debian-10.0-standard_10.0-1_amd64.tar.gz'
    hookscript: 'local:snippets/vm_hook.sh'
    description: created with ansible
```

### CODE REVIEW

**Comment by Andersson007** [comment]
i've changed the format of current examples https://github.com/ansible-collections/community.general/pull/248 to correspond to best practices

**Comment by Links2004** [comment]
master merged
changelog fragment and example added

**Comment by Andersson007** [comment]
I'm not a user of the module, @UnderGreen could you look at the changes please?

**Comment by Links2004** [comment]
Any updates or change to get this merged?

**Comment by felixfontein** [comment]
@UnderGreen @joshainglis @karmab could you please take a look?

**Comment by Andersson007** [comment]
@Links2004 thanks for the contribution!
@felixfontein thanks for reviewing!

**Comment by Andersson007** [comment]
merged #245 into master

**Pull request merged**
