### PR TITLE
Add nejch and lgatellier as GitLab module maintainers

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
@nejch and @lgatellier I would like to promote you to GitLab module maintainers, assuming you are interested :)

This practically means:
1. You will get pinged in all issues and PRs regarding GitLab modules;
2. Two maintainer `shipit`s can merge a PR (in case nobody with commit rights is around to press the button for you).

Please approve this PR if you want to become module maintainers. If you don't just write it, then I will remove you from this PR :)

Ref: https://github.com/ansible-collections/community.general/pull/4136#issuecomment-1038444003

##### ISSUE TYPE
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME
.github/BOTMETA.yml

### CODE REVIEW

**Review by lgatellier — APPROVED** [review]
@felixfontein I'm of course interested, thanks for your confidence :-)

Just to be sure I clearly understand this :
> Two maintainer shipits can merge a PR (in case nobody with commit rights is around to press the button for you).

Does it mean that when two module maintainers approve a PR, even if none of them have commit rights, the `shipit` bot will merge the PR ?
Are we talking about [this shipit project](https://github.com/shipitjs/shipit) ?

**Comment by felixfontein** [comment]
> Just to be sure I clearly understand this :
> 
> > Two maintainer shipits can merge a PR (in case nobody with commit rights is around to press the button for you).
> 
> Does it mean that when two module maintainers approve a PR, even if none of them have commit rights, the `shipit` bot will merge the PR ?

The bot's called @ansibullbot, but besides that (and some special cases where automerge might not work), yes.

> Are we talking about [this shipit project](https://github.com/shipitjs/shipit) ?

No, it's unrelated to that. `shipit` is one of the ansibullbot commands: https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md#label-shipit (`LGTM` and `+1` should also work).

**Review by nejch — APPROVED** [review]
Sounds good to me as well, thanks a lot @felixfontein :) hopefully this will also help with shorter feedback loops for me between the modules and the python-gitlab library.

**Comment by felixfontein** [comment]
@lgatellier @nejch thank you very much for becoming module maintainers :)

**Pull request merged**
