### PR TITLE
Tidy up validate-modules:doc-choices-do-not-match-spec II: The Rebase

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
Tidy up on sanity tests' ignore files, removing lines with validation-modules for these modules.

The focus was to pass the tests so no code was changed other than adjusting argument_spec for missing types or inconsistencies with the docs. The priority has been not to change any functionality, but to ensure that code and docs are synchronized.

Some lines were added back to the files, but a total of 48 lines were removed (among 2.9, 2.10 and 2.11).

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
plugins/modules/cloud/univention/udm_share.py
plugins/modules/remote_management/stacki/stacki_host.py
plugins/modules/remote_management/manageiq/manageiq_provider.py
plugins/modules/remote_management/ipmi/ipmi_power.py
plugins/modules/remote_management/ipmi/ipmi_boot.py
plugins/modules/remote_management/hpilo/hpilo_boot.py
plugins/modules/clustering/znode.py
plugins/modules/clustering/etcd3.py
plugins/modules/cloud/univention/udm_user.py
plugins/modules/cloud/lxc/lxc_container.py
plugins/modules/cloud/univention/udm_dns_zone.py
plugins/modules/cloud/univention/udm_dns_record.py
plugins/modules/cloud/spotinst/spotinst_aws_elastigroup.py
plugins/modules/cloud/smartos/vmadm.py
plugins/modules/cloud/lxc/lxc_container.py

### CODE REVIEW

**Comment by felixfontein** [comment]
Looks like the 2.9 ignore needs some removals: https://app.shippable.com/github/ansible-collections/community.general/runs/5619/11/tests

**Comment by russoz** [comment]
Yup, I was working on those, but last night (night for me), shippable seemed to be loaded - it took more than one hour for the previous push to go through. Should be finishing that today (good morning world!!).

**Comment by felixfontein** [comment]
> Yup, I was working on those, but last night (night for me), shippable seemed to be loaded - it took more than one hour for the previous push to go through. Should be finishing that today (good morning world!!).

Yeah, that are the nightly CI runs for github.com/ansible-collections. Starts at 09:00 UTC and takes roughly 2 hours to complete everything. For "us" in Europe that's during the late morning, which is also somewhat annoying :)

**Comment by russoz** [comment]
Well, good to know that, so probably will stop doing late night coding sessions. The missus sends her appreciation to all involved. :laughing:

**Comment by russoz** [comment]
... and like Borat would say: great success

**Review by felixfontein — APPROVED** [review]

**Comment by russoz** [comment]
thanks @felixfontein !

**Comment by felixfontein** [comment]
@russoz thanks for doing this!

**Comment by felixfontein** [comment]
Backport in #1416.

**Pull request merged**
