### PR TITLE
Add dependent lookup plugin

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This adds a new lookup plugin `community.general.dependent` which allows to do something like nested loops without having to resort to dynamic includes, using jinja2 templates to render JSON/YAML files, or other (ugly) hacks.

Basically the pseudo-code
```
for server in servers:
  for ip in server.ips:
    for network_interface in server.network_interfaces[ip]:
      run foobar module with:
        data: "{{ ip }} @ {{ network_interface }}"
        comment: "IP of server {{ server.name }}"
```
translates to
```.yaml
- foobar:
    data: "{{ item.ip }} @ {{ item.interface }}"
    comment: "IP of server {{ item.server.name }}"
  with community.general.dependent:
    - server: servers
    - ip: item.server.ips
    - interface: item.server.network_interfaces[item.ip]
```
See the examples in the lookup for some real-life examples I used this for.

I've already tried to get this included into Ansible once (ansible/ansible#42151, was finally rejected in a meeting since the opinion was that it allows people to stick to close to programming IIRC; see https://meetbot.fedoraproject.org/ansible-meeting/2018-10-09/ansible_core_plublic_irc_meeting.2018-10-09-19.00.html), and right now it lives in [felixfontein.tools](https://ansible.fontein.de/collections/felixfontein/tools/).

##### ISSUE TYPE
- New Plugin Pull Request

##### COMPONENT NAME
dependent

### CODE REVIEW

**Comment by russoz** [comment]
LGTM

**Comment by russoz** [comment]
Right after I pushed the last comment, I kept staring at the example code in the description:
```yaml
- foobar:
    data: "{{ item.1 }} @ {{ item.2 }}"
    comment: "IP of server {{ item.0 }}"
  with community.general.dependent:
    - servers
    - item.0.ips
    - item.0.network_interfaces[item.1]
```
It occurred to me that it might be interesting to have the items being named, such as:
```yaml
- foobar:
    data: "{{ item.ip }} @ {{ item.network_interface }}"
    comment: "IP of server {{ item.server }}"
  with community.general.dependent:
    - server: servers
    - ip: item.server.ips
    - network_interface: item.server.network_interfaces[item.ip]
```
But that could be something for a future PR, of course.

**Comment by felixfontein** [comment]
@russoz that's unfortunately impossible (otherwise I would have already implemented that ;-) ). A `with_*` / `loop` construct in Ansible allows to loop over one variable (whose name can be configured with `loop_control:`), the lookup plugin itself simply returns a list of values that this variable will have.

Having something you suggest would require support in ansible-core itself, and it probably won't happen...

**Comment by felixfontein** [comment]
ready_for_review

**Review by russoz — APPROVED** [review]
looking good :-)

**Comment by felixfontein** [comment]
@russoz thanks for reviewing this!

**Pull request merged**
