### PR TITLE
Add new members to gitlab team

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Add new members to gitlab team

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
BOTMETA.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
@zanssa could you please approve the PR?

**Comment by Andersson007** [comment]
@scodeman could you please approve this
@zanssa , I'm waiting for your approval as well
thank you

**Review by zanssa — APPROVED** [review]

**Comment by zanssa** [comment]
@Andersson007 , approved. Thank you!

**Comment by gundalow** [comment]
@Lunik@ Shaps @dj-wasabi @marwatk @waheedigood news, we have two extra maintainers for GitLab now.

You can see the existing GitLab issues and PRs here https://github.com/ansible-collections/community.general/labels/gitlab

Thank you for your support.

**Comment by Andersson007** [comment]
@zanssa you and the community is always welcome!

**Comment by felixfontein** [comment]
@scodeman this was merged a bit too early. Please still approve this :) (If you don't want to, we'll add another PR to remove you from the list.)

**Comment by scodeman** [comment]
This is ok. I can no more approve though.

**Comment by felixfontein** [comment]
@scodeman just writing it is fine :)

**Pull request merged**
