### PR TITLE
passwordstore: Add missing_subkey parameter

### PR DESCRIPTION
**Pull request by mluzarreta**
##### SUMMARY

Add ability to trigger error or warning when a subkey is missing in pass file.
By default the behavior is unchanged (if subkey is missing, None is returned).
This option can also be set in ansible.cfg

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
passwordstore missing_subkey

##### ADDITIONAL INFORMATION

Here some command lines to illustrate the feature:

```sh
❯ ansible -m debug -a "msg={{ lookup('community.general.passwordstore', 'existing_pass_file_but_missing_subkey subkey=foo') }}" -i localhost, localhost
localhost | SUCCESS => {
    "msg": ""
}

❯ ansible -m debug -a "msg={{ lookup('community.general.passwordstore', 'existing_pass_file_but_missing_subkey subkey=foo missing_subkey=warn') }}" -i localhost, localhost
[WARNING]: passwordstore: subkey foo for passname existing_pass_file_but_missing_subkey not found
localhost | SUCCESS => {
    "msg": ""
}

❯ ansible -m debug -a "msg={{ lookup('community.general.passwordstore', 'existing_pass_file_but_missing_subkey subkey=foo missing_subkey=error') }}" -i localhost, localhost
localhost | FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'community.general.passwordstore'. Error was a <class 'ansible.errors.AnsibleError'>, original message: passwordstore: subkey foo for passname existing_pass_file_but_missing_subkey not found and missing=error is set. passwordstore: subkey foo for passname existing_pass_file_but_missing_subkey not found and missing=error is set"
}
```

### CODE REVIEW

**Review by felixfontein — COMMENTED** [review]
Thanks for your contribution! I've added some first comments.

**Comment by mluzarreta** [comment]
@felixfontein thanks for your review, suggestions have been applied :slightly_smiling_face:

**Comment by felixfontein** [comment]
If nobody objects, I'll merge this in ~a week.

**Comment by felixfontein** [comment]
@mluzarreta thanks for your contribution!

**Pull request merged**
