### PR TITLE
collection: Change default='no's and 'yes's to default=False and default=True

### PR DESCRIPTION
**Pull request by aminvakil**
##### SUMMARY
Fixes: https://github.com/ansible-collections/community.general/issues/550

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
collection

```

### CODE REVIEW

**Comment by felixfontein** [comment]
@aminvakil thanks for fixing this!

**Comment by aminvakil** [comment]
Actually I was going to fix all modules in this PR, not just packaging/os.

Sorry I should have said WIP, don't merge.

**Comment by felixfontein** [comment]
I assumed (or hoped) these were all :)

**Comment by aminvakil** [comment]
Fine, my fault, I'll open a new PR and change title of this PR if it's OK.

**Comment by felixfontein** [comment]
No problem. Feel free to open another PR and/or rename this one.

**Pull request merged**
