### PR TITLE
Return correct terraform changed state when running in check mode

### LINKED ISSUE #807: Terraform plan output and changed state not returned when running in check mode
##### SUMMARY
Running the terraform module in check mode does not return the terraform plan output and does not correctly report the changed state of the resource to Ansible

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
terraform

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.9.12
  config file = None
  configured module search path = ['/home/charles/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/charles/tmp/ansible-test/.direnv/python-3.6.9/lib/python3.6/site-packages/ansible
  executable location = /home/charles/tmp/ansible-test/.direnv/python-3.6.9/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE
playbook.yml:
```yaml
- hosts: localhost
  tasks:
    - terraform:
        project_path: './terraform'
        state: present
```
terraform/main.tf
```terraform
resource "local_file" "foo" {
  content = "foo"
  filename = "foo.txt"
}
```
1. Run the playbook
1. Change the "content" in main.tf to something else
1. Run the playbook again using in check mode using `--check --verbose`

##### EXPECTED RESULTS
The documentation for the terraform module says: "To just run a terraform plan, use check mode". So I would expect the steps above to display the change plan from Terraform and the resource to be reported as "changed" by Ansible.'

In Ansible 2.8.14 the output used to look like this:

```
TASK [terraform] **************************************************************************************************************************************************************************************************
ok: [localhost] => {"changed": false, "command": "/opt/bin/terraform apply -no-color -input=false -auto-approve=true -lock=true /tmp/tmpnuqnp2mz.tfplan", "outputs": {}, "state": "present", "stderr": "", "stderr_lines": [], "stdout": "Refreshing Terraform state in-memory prior to plan...\nThe refreshed state will be used to calculate this plan, but will not be\npersisted to local or remote state storage.\n\nlocal_file.foo: Refreshing state... [id=0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33]\n\n------------------------------------------------------------------------\n\nAn execution plan has been generated and is shown below.\nResource actions are indicated with the following symbols:\n-/+ destroy and then create replacement\n\nTerraform will perform the following actions:\n\n  # local_file.foo must be replaced\n-/+ resource \"local_file\" \"foo\" {\n      ~ content              = \"foo\" -> \"foo1\" # forces replacement\n        directory_permission = \"0777\"\n        file_permission      = \"0777\"\n        filename             = \"foo.txt\"\n      ~ id                   = \"0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33\" -> (known after apply)\n    }\n\nPlan: 1 to add, 0 to change, 1 to destroy.\n\n------------------------------------------------------------------------\n\nThis plan was saved to: /tmp/tmpnuqnp2mz.tfplan\n\nTo perform exactly these actions, run the following command to apply:\n    terraform apply \"/tmp/tmpnuqnp2mz.tfplan\"\n\n", "stdout_lines": ["Refreshing Terraform state in-memory prior to plan...", "The refreshed state will be used to calculate this plan, but will not be", "persisted to local or remote state storage.", "", "local_file.foo: Refreshing state... [id=0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33]", "", "------------------------------------------------------------------------", "", "An execution plan has been generated and is shown below.", "Resource actions are indicated with the following symbols:", "-/+ destroy and then create replacement", "", "Terraform will perform the following actions:", "", "  # local_file.foo must be replaced", "-/+ resource \"local_file\" \"foo\" {", "      ~ content              = \"foo\" -> \"foo1\" # forces replacement", "        directory_permission = \"0777\"", "        file_permission      = \"0777\"", "        filename             = \"foo.txt\"", "      ~ id                   = \"0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33\" -> (known after apply)", "    }", "", "Plan: 1 to add, 0 to change, 1 to destroy.", "", "------------------------------------------------------------------------", "", "This plan was saved to: /tmp/tmpnuqnp2mz.tfplan", "", "To perform exactly these actions, run the following command to apply:", "    terraform apply \"/tmp/tmpnuqnp2mz.tfplan\"", ""], "workspace": "default"}
```

##### ACTUAL RESULTS
The change plan from Terraform is not shown and Ansible reports the task as "changed=false". Actual output is:
```
TASK [terraform] **************************************************************************************************************************************************************************************************
ok: [localhost] => {"changed": false, "command": "/opt/bin/terraform apply -no-color -input=false -auto-approve=true -lock=true /tmp/tmp2uwl0dkf.tfplan", "outputs": {}, "state": "present", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": [], "workspace": "default"}
```

I think [this commit](https://github.com/ansible/ansible/commit/cf623fa62fd78910f86617cfbd7e8c9564feee28#diff-b1fbd5d526878f04f9df313ae0451a2a) may have stopped the plan output from being returned, as it resets `out` to an empty string after the `terraform plan` has been run. Indeed the plan output *is* returned in Ansible 2.8.14.

I'm not sure if "changed" was ever set correctly when run in check mode. It doesn't work in Ansible 2.8.14 either.

### PR DESCRIPTION
**Pull request by ampedandwired**
##### SUMMARY
Sets the "changed" status of the terraform module correctly when running in check mode or with `state == "planned"`

Fixes #807 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
terraform

##### ADDITIONAL INFORMATION
Before:
```
$ ansible-playbook --verbose --check playbook.yml 
TASK [community.general.cloud.misc.terraform] *********************************************************************************************************************************************************************
ok: [localhost] => changed=false 
  command: /opt/bin/terraform apply -no-color -input=false -auto-approve=true -lock=true /tmp/tmp3blq158_.tfplan
  outputs: {}
  state: present
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Refreshing Terraform state in-memory prior to plan...
    The refreshed state will be used to calculate this plan, but will not be
    persisted to local or remote state storage.
  
    local_file.foo: Refreshing state... [id=afebec4feb9975feae93f03d7cb613257d566f41]
  
    ------------------------------------------------------------------------
  
    An execution plan has been generated and is shown below.
    Resource actions are indicated with the following symbols:
    -/+ destroy and then create replacement
  
    Terraform will perform the following actions:
  
      # local_file.foo must be replaced
    -/+ resource "local_file" "foo" {
          ~ content              = "foo6" -> "foo7" # forces replacement
            directory_permission = "0777"
            file_permission      = "0777"
            filename             = "foo.txt"
          ~ id                   = "afebec4feb9975feae93f03d7cb613257d566f41" -> (known after apply)
        }
  
    Plan: 1 to add, 0 to change, 1 to destroy.
  
    ------------------------------------------------------------------------
  
    This plan was saved to: /tmp/tmp3blq158_.tfplan
  
    To perform exactly these actions, run the following command to apply:
        terraform apply "/tmp/tmp3blq158_.tfplan"
  stdout_lines: <omitted>
  workspace: default

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

After:
```
TASK [community.general.cloud.misc.terraform] *********************************************************************************************************************************************************************
changed: [localhost] => changed=true 
  command: /opt/bin/terraform apply -no-color -input=false -auto-approve=true -lock=true /tmp/tmpjmy_c9ao.tfplan
  outputs: {}
  state: present
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Refreshing Terraform state in-memory prior to plan...
    The refreshed state will be used to calculate this plan, but will not be
    persisted to local or remote state storage.
  
    local_file.foo: Refreshing state... [id=afebec4feb9975feae93f03d7cb613257d566f41]
  
    ------------------------------------------------------------------------
  
    An execution plan has been generated and is shown below.
    Resource actions are indicated with the following symbols:
    -/+ destroy and then create replacement
  
    Terraform will perform the following actions:
  
      # local_file.foo must be replaced
    -/+ resource "local_file" "foo" {
          ~ content              = "foo6" -> "foo7" # forces replacement
            directory_permission = "0777"
            file_permission      = "0777"
            filename             = "foo.txt"
          ~ id                   = "afebec4feb9975feae93f03d7cb613257d566f41" -> (known after apply)
        }
  
    Plan: 1 to add, 0 to change, 1 to destroy.
  
    ------------------------------------------------------------------------
  
    This plan was saved to: /tmp/tmpjmy_c9ao.tfplan
  
    To perform exactly these actions, run the following command to apply:
        terraform apply "/tmp/tmpjmy_c9ao.tfplan"
  stdout_lines: <omitted>
  workspace: default

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### CODE REVIEW

**Review by Andersson007 — COMMENTED** [review]
Please add a changelog fragment https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to

**Comment by Andersson007** [comment]
cc @m-yosefpor

**Comment by aslafy-z** [comment]
cc @ampedandwired
We're hitting the same issue.
Could you rebase and add the changelog block as asked by @Andersson007 please?
Thanks

**Comment by felixfontein** [comment]
@ampedandwired are you still working on this?

needs_info

**Comment by felixfontein** [comment]
Closing since there was no more reaction. @ampedandwired if you're interested again in working on this, please ping me. If someone else is interested in continuing this PR, please also write it here so we can coordinate.

**Pull request closed without merging**
