### PR TITLE
mksysb - revamped module + fix bug in backup_dmapi_fs option

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
Revamped the module + fixed bug: option should be `-A` instead of `-a`.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/modules/system/mksysb.py

### CODE REVIEW

**Comment by kairoaraujo** [comment]
I will try to borrow a machine to run tests.

**Comment by russoz** [comment]
@kairoaraujo it would be awesome if we could write some unit and integration tests for this and the other AIX-related modules. We will be more than happy to assist with that, and it will give us more confidence when making improvements in the future. Would you be interested and available for that? TIA

**Comment by felixfontein** [comment]
@russoz the diff now looks a bit strange, can you please rebase?

**Comment by russoz** [comment]
@felixfontein done

**Comment by felixfontein** [comment]
@kairoaraujo any luck with testing this?

**Comment by felixfontein** [comment]
@kairoaraujo any update on testing?

**Comment by felixfontein** [comment]
I've just remembered this PR. I really hate to let it rot for too long. How about we merge it for community.general 5.0.0?

**Comment by felixfontein** [comment]
Ok, if nobody complains, I'll merge this beginning of next week. Let's get this out.

**Comment by felixfontein** [comment]
@russoz thanks for your contribution!
@kairoaraujo @mator thanks for looking at this!

**Pull request merged**
