### PR TITLE
ease limitation for nios_host_record DNS Bypass

### LINKED ISSUE #1786: nios_host_record DNS Bypass check is too strict
**Summary**

`nios_host_record` doesn't allow creation of a host record with a non-default dns view specified when `configure_for_dns` is `false`. 

The `network` we target for our host record is in a network view that only has a non-default dns view assigned to it.

This limitation does not exist in Infoblox WAPI (tested in version 2.10), and creation via Infoblox Web UI (Add Host Wizard) works as well. So currently using the URI module as a workaround.

As NIOS/Infoblox does support multiple DNS views, and users can not always target the default, the module should not limit specifying non-default views.

**Issue Type**

Bug Report

**Component Name**

`nios_host_record`

**Ansible Version**

```
ansible 2.10.3
python version = 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23)
```

**Configuration**

```paste below

```

**OS / Environment**

Infoblox WAPI 2.10

**Steps To Reproduce**

```
- name: create host record
  community.general.nios_host_record:
    name: "my_host"
    ipv4:
      - address: "{{ host_ip }}"
        configure_for_dhcp: false
    state: present
    configure_for_dns: false
    dns_view: "default.my-custom-view"
    provider: "{{ nios_provider }}"
```

**Expected Results**

HTTP success response 201 "created".

**Actual Results**

```
fatal: [xxxxx]: FAILED! => changed=false
  invocation:
    module_args:
      aliases: null
      comment: null
      configure_for_dns: false
      dns_view: default.my-custom-view
      extattrs: null
      ipv4:
      - add: null
        address: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        configure_for_dhcp: false
        ipv4addr: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        mac: null
        remove: null
      ipv4addrs:
      - add: null
        address: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        configure_for_dhcp: false
        ipv4addr: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        mac: null
        remove: null
      ipv6addrs: null
      name: my_host
      provider:
        host: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        http_pool_connections: 10
        http_pool_maxsize: 10
        http_request_timeout: 10
        max_results: 1000
        max_retries: 3
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        silent_ssl_warnings: true
        username: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        wapi_version: '2.10'
      state: present
      ttl: null
      view: default.my-custom-view
  msg: DNS Bypass is not allowed if DNS view is set other than 'default'
```

Calling the endpoint via the URI module does work as expected:

```
- name: create host record
  uri:
    method: POST
    url: "https://{{ nios_host }}/wapi/v2.10/record:host"
    user: "{{ nios_user }}"
    password: "{{ nios_pass }}"
    body: >
      {
        "name": "my_host",
        "configure_for_dns": false,
        "ipv4addrs": [
            {
                "configure_for_dhcp": false,
                "ipv4addr": "{{ host_ip }}"
            }
        ],
        "view": "default.my-custom-view"
      }
    body_format: json
    status_code: 201
```

### PR DESCRIPTION
**Pull request by shieni**
DNS bypass should be allowed when `configure_dns` is `false` and `view` is set other than default.

##### SUMMARY

Fixes #1786 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`community.general.nios_host_record`
##### ADDITIONAL INFORMATION

Removal of the limiting check.

After removal results are as expected (as opposed to those in the Issue)

```
changed: [xxxxx] => changed=true
  invocation:
    module_args:
      aliases: null
      comment: null
      configure_for_dns: false
      dns_view: default.my-custom-view
      extattrs: null
      ipv4:
      - add: null
        address: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        configure_for_dhcp: false
        ipv4addr: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        mac: null
        remove: null
      ipv4addrs:
      - add: null
        address: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        configure_for_dhcp: false
        ipv4addr: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        mac: null
        remove: null
      ipv6addrs: null
      name: testi_vm
      provider:
        host: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        http_pool_connections: 10
        http_pool_maxsize: 10
        http_request_timeout: 10
        max_results: 1000
        max_retries: 3
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        silent_ssl_warnings: true
        username: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        wapi_version: '2.10'
      state: present
      ttl: null
      view: default.my-custom-view
```

### CODE REVIEW

**Comment by felixfontein** [comment]
Three quick remarks:
1. You need to add a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to).
2. The one CI job (CI (Cloud devel Python 3.6)) will always fail until ansible/ansible#73563 is fixed, this is unrelated to your PR.
3. The modules are also living in https://github.com/infobloxopen/infoblox-ansible/, so you also want to fix it there. Eventually the modules will be removed from this collection and redirections will be added to that collection.

**Comment by shieni** [comment]
thanks for your patience and the remarks!

I added a fragment to this PR and opened corresponding issue&PR to the infoblox-ansible repo:
- https://github.com/infobloxopen/infoblox-ansible/issues/38
- https://github.com/infobloxopen/infoblox-ansible/pull/39

**Review by felixfontein — APPROVED** [review]
I have no idea whether this is correct, but it shouldn't break any existing use-case, so I'll merge this if nobody complains in a few days.

**Comment by felixfontein** [comment]
@shieni thanks for fixing this!

**Pull request merged**
