### PR TITLE
Fix: apache2_mod_proxy python3 / BeautifulSoup4 support

### LINKED ISSUE #4167: community.general.apache2_mod_proxy issue with new BeautifulSoup library
### Summary

It seems that new beautifulsoup library version 4 changes the way the library is imported:
```python
from bs4 import BeautifulSoup
```

causing errors even if pip3 library beautifulsoup4 is installed when calling module community.general.apache2_mod_proxy, which tries to import it as:
```python
from BeautifulSoup import BeautifulSoup
```

Many thanks!

### Issue Type

Bug Report

### Component Name

community.general.apache2_mod_proxy

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.11.1] 
  config file = /home/jmsierra/.ansible.cfg
  configured module search path = ['/home/jmsierra/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jmsierra/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/jmsierra/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jmsierra/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

### Community.general Version

```console (paste below)
$ ansible-galaxy collection list community.general

# /home/jmsierra/.local/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.2.0  

# /home/jmsierra/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 4.4.0  
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

### OS / Environment

Ansible machine: Ubuntu 20 WSL
Target machine: Ubuntu 20.04 Minimal

### Steps to Reproduce

Installed beautiful soup 4 manually on dc1-frontend machine:
```console
# pip3 install beautifulsoup
Collecting beautifulsoup
  Using cached BeautifulSoup-3.2.2.tar.gz (32 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-w9axyja9/beautifulsoup_88953322c3844e60bb79f27ef1c1efaa/setup.py", line 3
          "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."
                                                                                                          ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

# pip3 install beautifulsoup4

# pip3 list | grep soup
beautifulsoup4         4.10.0
soupsieve              2.3.1

```
Launch ansible module:

```yaml (paste below)
  pre_tasks:
    - name: Remove node from balancer
      community.general.apache2_mod_proxy:
        balancer_vhost: 'notification'
        member_host: 'ws://{{ ansible_host }}:15674/ws'
        state: drained
      delegate_to: dc1-frontend1
```

### Expected Results

Expected for the target machine (ansible_host) to be drained from apache2 load balancer. 

### Actual Results

```console (paste below)
TASK [Remove node from balancer] ******************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'BeautifulSoup'
fatal: [dc1-sat1 -> dc1-frontend1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (BeautifulSoup) on dc1-frontend1's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by IceEyz**
##### SUMMARY
Migrates from python2 beautifulsoup to python3 beautifulsoup4 module, in order to fix apache2_mod_proxy on python3.
Fixes #4167

No changelog fragment yet

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
apache2_mod_proxy

##### ADDITIONAL INFORMATION
Changes made according to https://www.crummy.com/software/BeautifulSoup/bs4/doc/#porting-code-to-bs4

### CODE REVIEW

**Review by felixfontein — COMMENTED** [review]
Thanks for your contribution! Please note that your PR breaks backwards compatibility for folks who use the module with BeautifulSoup and do not have BeautifulSoup4 installed.

For this to be accepted, you need to modify the patch so it supports both BS and BS4.

**Comment by IceEyz** [comment]
I understand, however, bs3 has been discontinued on 2020-12-31 and bs3 does not support python3, while bs4 is both available in python2.7 and python3, and bs4 has been available since 2012.

I feel that nudging users to a supported dependency makes sense, but if it doesn't, some guidance on the preferred implementation style would be welcome, i.e. aliasing bs3's imported methods?

**Comment by felixfontein** [comment]
> I feel that nudging users to a supported dependency makes sense, but if it doesn't, some guidance on the preferred implementation style would be welcome, i.e. aliasing bs3's imported methods?

There is no preferred implementation style. I would probably have a helper function `def find_all(node, what)` which calls `node.findAll(what)` for BS and `node.find_all(what)` for BS4.

**Comment by felixfontein** [comment]
Ping @IceEyz

**Comment by felixfontein** [comment]
needs_information

**Pull request closed without merging**
