### PR TITLE
Run tests with Ansible 2.9 as well

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
As topic says.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by felixfontein** [comment]
Tests are green! \o/ That means: if a new version of community.general gets published, and several 2.9 backports for Ansible merged, community.general is fully functional (at least from perspective of existing tests!) with Ansible 2.9.

**Comment by felixfontein** [comment]
In [yesterday's meeting](https://github.com/ansible/community/issues/539) we decided to keep the symlinks at least for 1.x.y, and thus support Ansible 2.9. This PR adds CI testing with the latest Ansible 2.9 release. @gundalow said that RH is willing to pay for the additional CI costs (see meeting log). This PR implements them.

**Comment by felixfontein** [comment]
(The cancelled test is unrelated to this PR, it will be fixed in #598.)

**Comment by Andersson007** [comment]
@felixfontein i'm not sure i understand the changes correctly but if a pr to `main` branch touches feaures that are not in 2.9, what will happen?

**Comment by felixfontein** [comment]
@Andersson007 I guess it needs to add some logic to the tests to skip the tests for 2.9. Right now I know of only one such feature, and there's a simple work-around for it which also makes it work with 2.9.

But that's the same problem we will have with 2.10 vs. devel vs. 2.11 (when it's around) etc.

**Comment by Andersson007** [comment]
and a number of red lines is larger than green which also looks good:) thanks for doing this

**Comment by felixfontein** [comment]
@Andersson007 thanks a lot for reviewing!

**Pull request merged**
