### PR TITLE
Add Ansible 2.10 runs for CI

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Add Ansible 2.10 to CI.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by felixfontein** [comment]
Continues #524.

**Comment by felixfontein** [comment]
@gundalow can you check whether the 2.10 target selection is ok?

**Comment by felixfontein** [comment]
@Andersson007 is the `TASK [setup_postgresql_db : restart postgresql service]` task really needed? It was hanging again.

**Comment by Andersson007** [comment]
@felixfontein , i don't think so. I removed one restarting and changed another one to `state=started`. Let's see https://github.com/ansible-collections/community.general/pull/533

**Comment by Andersson007** [comment]
@felixfontein the tests doesn't work w/o that statement, unfortunately. Have no idea why. I tried several workarounds but failed:(

**Comment by felixfontein** [comment]
Hmm, that's really not good. The standard behavior in this case is to disable all tests using `setup_postgresql_db`, but that's pretty harsh.

For now I'll merge this PR, as the CI problem is not related to it.

**Pull request merged**
