### PR TITLE
Prepare main for 7.0.0

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Bump version to 7.0.0.
##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
collection

### CODE REVIEW

**Comment by felixfontein** [comment]
First step: let's see what the sanity tests complain about.

**Comment by felixfontein** [comment]
ready_for_review

**Review by russoz — APPROVED** [review]
LGTM!

**Comment by felixfontein** [comment]
@russoz thanks a lot for reviewing this!

If anybody spots more things that are missing for 7.0.0, please comment here, or create specific issues / PRs. Thanks!

**Pull request merged**
