### PR TITLE
Remove ANSIBLE_METADATA

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Remove ANSIBLE_METADATA

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by martinm82** [comment]
Is the ANSIBLE_METADATA not required anymore? Do you have a link to a documentation of what we need to take into account when writing new modules/plugins? I have an open PR for a new module and probably would need to clean it up as it was created based on rules from Ansible 2.7

**Comment by gundalow** [comment]
> Is the ANSIBLE_METADATA not required anymore? Do you have a link to a documentation of what we need to take into account when writing new modules/plugins? I have an open PR for a new module and probably would need to clean it up as it was created based on rules from Ansible 2.7
@martinm82 https://github.com/ansible-collections/overview/issues/45#issuecomment-627922948
May I suggest subscribing (button on the right hand side) to https://github.com/ansible-collections/overview/issues/45 and https://github.com/ansible/community/issues/346 this is a good way to keep in the loop about potential changes.

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
https://github.com/ansible/community/issues/346

**Comment by Andersson007** [comment]
CC @gundalow @felixfontein

**Comment by Andersson007** [comment]
sorry, guys, i thought it's only for modules. Now i grepped through the whole content. When CI passed, it's ready for review

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/overview/issues/57

**Comment by gundalow** [comment]
> Is the ANSIBLE_METADATA not required anymore? Do you have a link to a documentation of what we need to take into account when writing new modules/plugins? I have an open PR for a new module and probably would need to clean it up as it was created based on rules from Ansible 2.7
@martinm82 https://github.com/ansible-collections/overview/issues/45#issuecomment-627922948
May I suggest subscribing (button on the right hand side) to https://github.com/ansible-collections/overview/issues/45 and https://github.com/ansible/community/issues/346 this is a good way to keep in the loop about potential changes.

**Comment by gundalow** [comment]
@Andersson007 Thank you for doing this
@felixfontein @resmo Thank you for the careful reviews

**Comment by Andersson007** [comment]
@gundalow @felixfontein @resmo thanks for reviewing and merging

**Comment by felixfontein** [comment]
If we ever need this, here's a list of modules which was marked as `stableinterface`:
```
cloud/digital_ocean/digital_ocean_domain.py
database/proxysql/proxysql_replication_hostgroups.py
database/proxysql/proxysql_mysql_users.py
database/proxysql/proxysql_global_variables.py
database/proxysql/proxysql_backend_servers.py
database/proxysql/proxysql_query_rules.py
database/proxysql/proxysql_scheduler.py
database/proxysql/proxysql_manage_config.py
database/postgresql/postgresql_db.py
database/postgresql/postgresql_privs.py
database/postgresql/postgresql_user.py
files/xattr.py
notification/bearychat.py
notification/osx_say.py
notification/slack.py
notification/say.py
notification/irc.py
notification/mail.py
notification/jabber.py
notification/cisco_spark.py
notification/hipchat.py
packaging/os/pkgutil.py
packaging/os/apk.py
system/interfaces_file.py
system/runit.py
system/svc.py
system/osx_defaults.py
system/awall.py
system/puppet.py
```

**Pull request merged**
