### PR TITLE
fix structure xcc_redfish_command

### LINKED ISSUE #3354: For the hackathon: Improve readability of examples in nios_network module
### Summary

**NOTE: Please don't fix this before the hackathon** https://hackmd.io/CqUQNTEqRBCHBTC4WF-9Aw?view. If interested in fixing this, please register for the [summit](https://github.com/ansible-collections/community.general/issues/3273#issuecomment-906314999)

The readability of examples in the EXAMPLES doc block in `./plugins/modules/net_tools/nios/nios_network.py` can be improved. Currently it looks like below:
```
 109 - name: Configure a network ipv4
110   community.general.nios_network:
111     network: 192.168.10.0/24
112     comment: this is a test comment
113     state: present
114     provider:
115       host: "{{ inventory_hostname_short }}"
116       username: admin
117       password: admin
118   connection: local
119 - name: Configure a network ipv6
120   community.general.nios_network:
121     network: fe80::/64
122     comment: this is a test comment
123     state: present
124     provider:
125       host: "{{ inventory_hostname_short }}"
126       username: admin
127       password: admin
128   connection: local
129 - name: Set dhcp options for a network ipv4
130   community.general.nios_network:
...
```
Needs to put a blank line between the tasks.

### Issue Type

Documentation Report

### Component Name

./plugins/modules/net_tools/nios/nios_network.py

### Ansible Version

_No response_

### Configuration

_No response_

### OS / Environment

_No response_

### Additional Information

_No response_

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by bile0026**
Part of Ansible contributer summit hackathon. 

Relates #3354 (Andersson007 changed Fixes to Relates to prevent closing of the issue after the PR gets merged)

Adhere to proper task structure with task names.

### CODE REVIEW

**Comment by bile0026** [comment]
@Andersson007 Ready for Review!

**Review by Andersson007 — COMMENTED** [review]
@bile0026 hi, thanks for the doc improvement!

The fragment is not needed for bugfixes in this collection,
so please 1) remove it or 2) change `bugfixes:` to `trivial:` so that it'll be ignored when the changelog is generated.

the PR LGTM, after you change the above, we'll be happy to merge this!

**Comment by felixfontein** [comment]
Removing it would be best.

**Review by Andersson007 — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@bile0026 thanks a lot for improving the docs!
@Andersson007 thanks for reviewing!

**Pull request merged**
