### PR TITLE
postgresql_user: add scram-sha-256 password support

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql_user: add scram-sha-256 password support

i rewrote https://github.com/ansible/ansible/pull/51121 in part of saslprep
implemended RFC from scratch with BSD licence

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
```plugins/modules/database/postgresql/postgresql_user.py```
```plugins/module_utils/saslprep.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
rebuild_failed

**Comment by Andersson007** [comment]
@Neustradamus I rewrote that. We have CI tests but manual testing will be very valuable too.

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
cc @astorath @andytom @kostiantyn-nemchenko @tcraxs @sebasmannem

**Comment by Andersson007** [comment]
@Neustradamus i hope so, thanks!

**Comment by gundalow** [comment]
rebuild_merge

**Comment by Andersson007** [comment]
@Neustradamus (or anybody else) do you have a possibility to test this manually and put shipit if everything is ok?
The feature looks pretty important.
Would be cool if anyone of potential users confirms that it works as expected and won't break existing pipelines.
It allows us to merge the PR faster (moreover, the changes are significant, so, there's no garantee it'll be merged without a review)

**Comment by Neustradamus** [comment]
Andersson007: I can not check but thanks for the merging!

**Comment by Andersson007** [comment]
@Neustradamus thanks to Ansibullbot for merging:) and you for your support!

**Comment by predmijat** [comment]
Is this working for anyone? I can't seem to set up password for PostgreSQL user if `scram-sha-256` is set in `pg_hba.conf`.

Ansible finishes without errors, but if I try to log in I get this:
`psql: error: could not connect to server: FATAL:  password authentication failed for user "postgres"`

I have to change `scram-sha-256` to `trust` in `pg_hba.conf`, restart PostgreSQL, alter user with password, change encryption back to `scram-sha-256`, restart PostgreSQL again and only then it works.
I'm using simple, literal password in my playbook (`asdf`), and I see it printed like that to stdout using `env ANSIBLE_DISPLAY_ARGS_TO_STDOUT=1`, so anything with vars/vault is not the issue here.

Am I missing something here?

**Comment by Andersson007** [comment]
```
    - name: 'Using cleartext password with scram-sha-256: check that password is changed when using cleartext password'
      <<: *task_parameters
      postgresql_user:
        <<: *parameters
        password: "{{ db_password1 }}"
        encrypted: "{{ encrypted }}"
      environment:
        PGCLIENTENCODING: 'UTF8'
        # ansible postgresql_user module interface does not (yet) support forcing password_encryption
        # type value, we'll have to hack it in env variable to force correct encryption
        PGOPTIONS: "-c password_encryption=scram-sha-256"
```

**Comment by predmijat** [comment]
@Andersson007 adding `environment:` section did the trick! Thanks!

**Comment by Andersson007** [comment]
@predmijat you're welcome!

**Comment by hoax89** [comment]
Is this in any stable version? Even with environment vars set like in your example, the module always reports changed, and alwaysa regenerates the password hashes in pg_authid. Currently using 2.9.9

**Comment by Andersson007** [comment]
The feature will be released in 2.10. Alternatively you could use community.general collection tarball from galaxy. See how to use collections on Ansible docsite

**Comment by Neustradamus** [comment]
@Andersson007: Good news for 2.10!

**Comment by Andersson007** [comment]
@Neustradamus yep, though this hasn't been tested manually:)

**Pull request merged**
