### PR TITLE
opennebula: port one_image to pyone

### PR DESCRIPTION
**Pull request by nilsding**
##### SUMMARY

This pull request ports the `one_image` module to use the `pyone` library instead of `python-oca`.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

one_image

##### ADDITIONAL INFORMATION

`one_image` is (was? :-)) the last module in cloud/opennebula that still depended on the old and unmaintained `python-oca` library, which does not work with Python 3.

Before the change, the output of this basic playbook failed with a syntax error because `python-oca` used the old python2 syntax for rescuing exceptions:

```yaml
---
- hosts: localhost
  module_defaults:
    community.general.one_image:
      api_url: 'https://some-opennebula-host/RPC2'
      api_username: 'oneuser'
      api_password: 'secret'
  tasks:
  - name: Fetch the IMAGE by name
    community.general.one_image:
      name: foxy-test
    register: result

  - name: Print the IMAGE properties
    ansible.builtin.debug:
      var: result
```

```paste below
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Fetch the IMAGE by name] *************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: invalid syntax
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/foxy/.ansible/tmp/ansible-tmp-1615972663.7346778-15888-126585625806266/AnsiballZ_one_image.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/foxy/.ansible/tmp/ansible-tmp-1615972663.7346778-15888-126585625806266/AnsiballZ_one_image.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/foxy/.ansible/tmp/ansible-tmp-1615972663.7346778-15888-126585625806266/AnsiballZ_one_image.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.opennebula.one_image', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_one_image_payload_ywj97paa/ansible_one_image_payload.zip/ansible/modules/cloud/opennebula/one_image.py\", line 169, in <module>\n  File \"/home/foxy/.local/lib/python3.8/site-packages/oca/__init__.py\", line 118\n    except socket.error, e:\n                       ^\nSyntaxError: invalid syntax\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

After this change it just works™:

```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Fetch the IMAGE by name] *************************************************
ok: [localhost]

TASK [Print the IMAGE properties] **********************************************
ok: [localhost] => {
    "result": {
        "changed": false,
        "failed": false,
        "group_id": 0,
        "group_name": "oneuser",
        "id": 6466,
        "name": "foxy-test",
        "running_vms": 0,
        "state": "READY",
        "used": false,
        "user_id": 0,
        "user_name": "oneuser"
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### CODE REVIEW

**Review by felixfontein — COMMENTED** [review]
Thanks for this contribution! Could you please add a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)?

There's one problem with this though. Since this is a breaking change - for Python 2 users it will stop working if they don't have pyone installed -, I can only merge this for the next major release (community.general 3.0.0).

The only way to make it a proper bugfix is to support both pyone and oca - but I don't think that's worth the effort.

**Comment by nilsding** [comment]
Thanks for your comment.  I've updated the commit with a changelog fragment marking this a `breaking_change`.

fwiw I don't think supporting both libraries is worth the effort either, especially considering that all the other opennebula modules are using pyone exclusively already ...

**Comment by felixfontein** [comment]
I cannot comment on the code, but if nobody complains, I'll merge this in a couple of weeks. I'd appreciate if anyone can give this a proper review, but if not, then so it will be :)

**Comment by xorel** [comment]
Perfect, thanks for the contribution!

LGTM

**Comment by felixfontein** [comment]
@nilsding thanks for implementing this!
@xorel thanks for reviewing!

This will appear in community.general 3.0.0.

**Pull request merged**
