### PR TITLE
Update BOTMETA.yml - Remove fxfitz as maintainer of IPA

### PR DESCRIPTION
**Pull request by fxfitz**
##### SUMMARY

I no longer have the free time to help maintain the IPA module. Removing myself.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME

IPA

### CODE REVIEW

**Comment by felixfontein** [comment]
Thanks a lot for maintaining the modules!

Can you please add a line `ignore: fxfitz` next to `maintainers: $team_ipa` in https://github.com/ansible-collections/community.general/blob/8d390bbbfff0cfe66d99bd5b2af00e3a42833795/.github/BOTMETA.yml#L651 ?

**Comment by fxfitz** [comment]
Done! Let me know if I need anything else :-D

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@fxfitz thanks again for all your work on the IPA modules!

**Comment by fxfitz** [comment]
You're welcome, Felix! If I ever get me free time, I'll jump back in again
😁😁

**Pull request merged**
