### PR TITLE
Add attributes to more modules (1/4)

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This docs PR adds basic attributes (`check_mode` and `diff_mode`) to some modules.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
various

### CODE REVIEW

**Review by kristianheljas — COMMENTED** [review]
Review in progress

**Review by kristianheljas — CHANGES_REQUESTED** [review]
Few nitpicks, other than that  - looks good.

**Review by kristianheljas — APPROVED** [review]
LGTM!

**Review by cloudnull — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@kristianheljas @cloudnull thank you very much for reviewing!

**Pull request merged**
