### PR TITLE
added gitlab_project_members

### PR DESCRIPTION
**Pull request by metanovii**
##### ISSUE TYPE
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME
gitlab_project_members

##### ADDITIONAL INFORMATION
this module for add/delete members to/from projects

### CODE REVIEW

**Review by felixfontein — COMMENTED** [review]
Generally looks good. Please note that all new modules are required to have tests (unit tests, integration tests, or both). Many other GitLab modules have both unit tests and integration tests (where the latter are not running in CI). I think having similar tests would be great for this module as well.

**Comment by metanovii** [comment]
> Generally looks good. Please note that all new modules are required to have tests (unit tests, integration tests, or both). Many other GitLab modules have both unit tests and integration tests (where the latter are not running in CI). I think having similar tests would be great for this module as well.

done

**Comment by felixfontein** [comment]
Dear GitLab module maintainers @Lunik @Shaps @dj-wasabi @marwatk @scodeman @waheedi @zanssa, please take a look at this new GitLab module :)

**Comment by zanssa** [comment]
I am proud to see my gitlab module, gitlab_group_members, being used as an example to develop more modules :) 

@felixfontein, thanks for all the comments and suggestions that made the module very useful! 

reviewed the files and I have no comments :) LGTM

**Comment by felixfontein** [comment]
@metanovii thanks a lot for contributing this module!
@zanssa thanks a lot for reviewing this!

**Comment by Andersson007** [comment]
@metanovii hi, thanks for your contribution! We could add your GH login to `.github/BOTMETA.yml` to the `team_gitlab` as a maintainer.
You'll be notified about Issues/PRs related to this stuff and your `shipit` will be counted by bot for automerge (needs two for bugfixes and minor changes).
What do you think?

**Comment by metanovii** [comment]
On понедельник, 19 апреля 2021 г. 16:22:16 MSK Andrew Klychkov wrote:
> @metanovii hi, thanks for your contribution! We could add your GH login to
> `.github/BOTMETA.yml` to the `team_gitlab` as a maintainer. You'll be
> notified about Issues/PRs related to this stuff and your `shipit` will be
> counted by bot for automerge (needs two for bugfixes and minor changes).
> What do you think?

Hi, no problem. I agree.

**Comment by Andersson007** [comment]
@metanovii great, thanks! I created a PR https://github.com/ansible-collections/community.general/pull/2287

**Pull request merged**
