### PR TITLE
Add a Pulp 2 related note to pulp_repo

### PR DESCRIPTION
**Pull request by mdellweg**
##### SUMMARY
The module operates with Pulp 2 only, which is sunsetting soon. Add a note to inform users before they become frustrated.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
pulp_repo

### CODE REVIEW

**Review by sysadmind — APPROVED** [review]
shipit

**Review by felixfontein — APPROVED** [review]
shipit

**Comment by felixfontein** [comment]
Looks like the bot doesn't want to automerge :)

**Comment by felixfontein** [comment]
@mdellweg thanks for improving the docs!
@sysadmind thanks for reviewing!

**Pull request merged**
