### PR TITLE
apache2_mod_proxy - minor improvements/fixes

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
- moved imports from the bottom of the code to the top (ansible-style).
- pythonified/simplified `get_member_status()`/`set_member_status()`
- reduced clutter in `Balancer.__init__()`

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
apache2_mod_proxy

### CODE REVIEW

**Comment by russoz** [comment]
@felixfontein unsure of how to categorize this one (and what to put into chglog frag, if anything)

**Review by felixfontein — COMMENTED** [review]
@russoz I'd use `minor_changes` and call this a refactoring / cleanup.

**Comment by russoz** [comment]
@felixfontein done!

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@russoz thanks for the improvements!

**Pull request merged**
