### PR TITLE
airbrake_deployment: Add types to the argument_spec

### PR DESCRIPTION
**Pull request by leedm777**
##### SUMMARY
As suggested in #583 ([here](https://github.com/ansible-collections/community.general/pull/583#discussion_r445994800))

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
airbrake_deployment

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by felixfontein** [comment]
Merging since this is a really safe change.

**Comment by felixfontein** [comment]
@leedm777 thanks for fixing this!

**Comment by phumpal** [comment]
Thank you @leedm777!

**Pull request merged**
