### PR TITLE
xfconf - state absent was not honoring check_mode

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
Module `xfconf` was not honoring the check mode when `state=absent`.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
xfconf

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@russoz thanks for spotting and fixing this!

**Comment by felixfontein** [comment]
@russoz can you create a backport PR for stable-1?

**Comment by russoz** [comment]
AFAIR xfconf main and stable-1 were up-to-date, I would try and backport automatically first, if that is OK. If that doesn work, I'll be happy to.

**Comment by felixfontein** [comment]
@russoz the automatic backport failed (https://github.com/ansible-collections/community.general/pull/2185/checks?check_run_id=2277463005), that's why I asked. I'm always trying that first ;-)

**Pull request merged**
