### PR TITLE
udm_share: fix sanity checks

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
Fix sanity check in the module by adding `elements` to the `list` parameters.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
plugins/modules/udm_share.py

### CODE REVIEW

**Comment by russoz** [comment]
References obtained from:
https://service.univention.de/download/docs.api/_modules/univention/admin/handlers/shares/share.html

**Review by felixfontein — APPROVED** [review]
Looks good to me. If nobody complains in ~a week, I'll merge this.

**Comment by felixfontein** [comment]
@russoz this now has conflicts. Can you please rebase?

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@russoz thanks again :)

**Pull request merged**
