### PR TITLE
BOTMETA.yml: add new maintainer to nmcli

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
BOTMETA.yml: add new maintainer to nmcli

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
BOTMETA.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
Hi @hummeltech ! Thank you for your great contribution to nmcli related stuff.
Would you like to become a maintainer of the module?
It means that you'll get indirect commit to the related stuff via Andible Bot.
Your `shiptit`, `LGTM`, `+1` will be counted by the bot for automerge (2 votes from the team members are required).
The bot will also notify you via email when nmcli-related issues / PRs are created, so you don't miss the chance to say your opinion on them:)
What do you think?
If it sounds interesting, please approve this PR.
If you're not interested, please say it and we close the issue.

Thanks once more for the regular and great contribution!

**Comment by Andersson007** [comment]
cc @hummeltech ^

**Comment by felixfontein** [comment]
Closing due to apparent lack of interest.

**Comment by Andersson007** [comment]
>... apparent lack of interest.

Pity:)

**Pull request closed without merging**
