### PR TITLE
cloudflare_dns: announce removal of SPF support

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Ref: #7758.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
cloudflare_dns

### CODE REVIEW

**Comment by felixfontein** [comment]
@gderber can you please take a quick look whether this looks OK to you? Once this is merged I'll create a PR to actually remove support for SPF (which won't get backported).

**Comment by gderber** [comment]
@felixfontein I'd recommend also changing line 153: "choices: [ A, AAAA, CNAME, DS, MX, NS, SPF, SRV, SSHFP, TLSA, CAA, TXT ]" -> "choices: [ A, AAAA, CNAME, DS, MX, NS, SRV, SSHFP, TLSA, CAA, TXT ]" unless that does more than affect the documentation.

**Comment by felixfontein** [comment]
@gderber choices in documentation must coincide with the choices in argument spec.

**Comment by gderber** [comment]
I'm good with what you got then.

**Comment by felixfontein** [comment]
@gderber thanks for taking a look!

**Comment by gderber** [comment]
@felixfontein You're welcome!

**Pull request merged**
