### PR TITLE
fixed ignored sanity tests in nagios module

### PR DESCRIPTION
**Pull request by tgoetheyn**
##### SUMMARY

Fixed errors in documentation and removed ignored sanity tests

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

nagios.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]
Awesome!

BTW, not sure if you are aware, docs-only and test-only PRs do not need a changelog fragment. (Except if it is a major docs bug, then one might be a good idea.) So everything's fine for this PR!

**Comment by felixfontein** [comment]
There's a `Co-authored-by: root <root@XXX.gent.be>` in one of the commit messages. If you want to get rid of that (in case it is potentially sensitive), feel free to rebase, otherwise I'll merge.

**Comment by gundalow** [comment]
Thank you for improving the documentation and reducing `tests/sanity/ignore-2.10.txt`

**Comment by tgoetheyn** [comment]
@felixfontein thanks for pointing out the 'root' in one of the commits.
I did a rebase so this is fixed now

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@tgoetheyn thanks a lot for fixing the sanity issues!

**Pull request merged**
