### PR TITLE
MH mh/mixins/deps.py: prevent deprecation warning when no deps are specified

### LINKED ISSUE #6639: The DependencyMixin is being deprecated.
### Summary

When I use the module to blacklist a kernel module, a warning appears.

### Issue Type

Bug Report

### Component Name

kernel_blacklist

### Ansible Version

```console (paste below)
$ansible --version
ansible [core 2.15.0]
  config file = None
  configured module search path = ['/home/bandura/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bandura/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/bandura/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/bandura/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Community.general Version

```console (paste below)
$ansible-galaxy collection list community.general

# /home/bandura/.local/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.0.1
```

### Configuration

```console (paste below)
$ansible-config dump --only-changed
CONFIG_FILE() = None
```

### OS / Environment

Debian 11-based

### Steps to Reproduce

```yaml (paste below)
- name: Blacklist old kernel module
  become: true
  community.general.kernel_blacklist:
    name: x_tables
```

### Expected Results

No warning

### Actual Results

Works, but with warning.
```console (paste below)
TASK [install-nftables : Blacklist old IPv4 kernel module] *********************
[DEPRECATION WARNING]: The DependencyMixin is being deprecated. Modules should 
use community.general.plugins.module_utils.deps instead. This feature will be 
removed from community.general in version 9.0.0. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY

Add test to deprecated `DependencyMixin` so that the deprecation warning only pops up when dependencies are actually specified.

Fixes #6639 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

plugins/module_utils/mh/mixins/deps.py

### CODE REVIEW

**Review by felixfontein — COMMENTED** [review]
Looks good! Can you add a changelog fragment?

(The third-party check failure is unrelated.)

**Comment by russoz** [comment]
Sure thing - busy day, I thought I had done it already.

**Comment by felixfontein** [comment]
No worries :) Thanks!

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@russoz thanks for fixing this!

**Pull request merged**
