### PR TITLE
adds rewrite module text workaround to apache2_module - #69750

### PR DESCRIPTION
**Pull request by jlariza**
##### SUMMARY

Fixes https://github.com/ansible/ansible/issues/69750 adding `rewrite` module to apache2_module text_workarounds list

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

apache2_module
##### ADDITIONAL INFORMATION

It is a quick fix based on https://github.com/ansible/ansible/issues/22635 and the PR that solved it https://github.com/ansible/ansible/pull/22649

### CODE REVIEW

**Comment by felixfontein** [comment]
I don't see how this PR actually helps. If `name` is `'rewrite'`, then the function already returns `rewrite_module`. So your PR should not change the behavior of the module at all. Or am I missing something?

**Comment by gundalow** [comment]
recheck

**Comment by n0trax** [comment]
Unfortunately I can't reproduce https://github.com/ansible/ansible/issues/69750 with Ubuntu 20.04 and as @felixfontein mentioned the module already appends '_module' to the module name.
@jlariza can you please describe the problem a little bit more in detail?

**Comment by Andersson007** [comment]
needs_info

**Comment by felixfontein** [comment]
Closing since there was never any clarification.

**Pull request closed without merging**
