### PR TITLE
django_manage module: add new maintainers

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
django_manage module: add new maintainers

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
`BOTMETA.yml`

### CODE REVIEW

**Comment by Andersson007** [comment]
Do not merge untill @russoz and @m-khvoinitsky approval

**Comment by russoz** [comment]
shipit

**Comment by Andersson007** [comment]
@m-khvoinitsky isn't around, so i'll merge @russoz after CI is green.
@m-khvoinitsky once you're ready to be a member, please let me know

**Comment by felixfontein** [comment]
Thanks @russoz for doing this!

**Comment by m-khvoinitsky** [comment]
@Andersson007, thank you for the suggestion. However, right now I maintain only one project in production which uses this module so I'm not sure that I'll be able to test it properly. But I will be happy to send you bugfixes if I find something.

**Comment by Andersson007** [comment]
@m-khvoinitsky ok, thanks! If once you want do become the module’s maintainer, please let me know

**Comment by felixfontein** [comment]
@Andersson007 you mean *a* module's maintainer, not *the* :)

**Comment by Andersson007** [comment]
@felixfontein not really.. i mean a maintainer but of the module:)

**Pull request merged**
