### PR TITLE
Add copy of ipaddress.py from ansible.netcommon

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
As discussed in #ansible-devel. This allows to drop the dependency on ansible.netcommon once all network modules have been moved out.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/module_utils/compat/ipaddress.py

### CODE REVIEW

**Comment by felixfontein** [comment]
I've skipped the F5 modules (bigip_firewall_address_list and bigip_security_address_list).

**Comment by jamescassell** [comment]
gotta say, I'd rather see a `community.common` collection for these trivial things that are used across collections, but don't want to be in ansible-base.

**Comment by felixfontein** [comment]
True. But we can still add that later, for now it's good to get rid of `ansible.netcommon` as a dependency as much as possible :)

**Comment by felixfontein** [comment]
@gundalow the YAML files are about the `ipaddr` plugin, not the `compat.ipaddress` module_utils.

As far as I understood it, the `ipaddr` plugin will stay in `netcommon`. So I guess we have to either rewrite the tests, or remove these parts from them.

The code in nios_fixed_address can be adjusted I guess. `compat.ipaddress` can be used to validate IP addresses.

I can take a look at this later.

**Comment by felixfontein** [comment]
I don't know how I managed to close this, but it definitely wasn't intentional :)

**Comment by felixfontein** [comment]
The `inventory_cloudscale` tests are marked as unsupported, so I guess we can keep the `netcommon.netcommon.ipaddr` usage in three. @gundalow what do you think?

**Comment by gundalow** [comment]
> @gundalow the YAML files are about the `ipaddr` plugin, not the `compat.ipaddress` module_utils.
> 
> As far as I understood it, the `ipaddr` plugin will stay in `netcommon`. So I guess we have to either rewrite the tests, or remove these parts from them.
> 
> The code in nios_fixed_address can be adjusted I guess. `compat.ipaddress` can be used to validate IP addresses.
> 
> I can take a look at this later.

If `plugins/modules/net_tools/nios/nios_fixed_address.py` is fixed then we can hopefully remove the runtime dependency on netcommon from galaxy.yml (once network content has been removed)

I'm not as worried about test dependencies.

**Comment by felixfontein** [comment]
@gundalow it is fixed, see e2cd9c07a8e3e19421ed6f24c04d6c4bfcb7f83e

**Comment by felixfontein** [comment]
Thanks for merging @gundalow!

**Pull request merged**
