### PR TITLE
cmd_runner_guide: docs improvements

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY

Some improvements in the docs after feedback.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

docs/docsite/rst/guide_cmdrunner.rst

### CODE REVIEW

**Comment by russoz** [comment]
@abakanovskii could you please review the improvements? TIA

**Comment by abakanovskii** [comment]
Thats a lot better than it was before :) 
Also could you please clarify about this https://github.com/ansible-collections/community.general/pull/8953#discussion_r1783885809 ?

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@russoz thanks!

**Comment by felixfontein** [comment]
@abakanovskii sorry I missed your comment somehow... @russoz please address it in another PR, sorry for the premature merge :)

**Comment by russoz** [comment]
> @abakanovskii sorry I missed your comment somehow... @russoz please address it in another PR, sorry for the premature merge :)

all good, it's possibly a bug in the arg formats, it is unlikely to cause a change in the docs, AFAICT

**Pull request merged**
