### PR TITLE
Update tss.py - multiline for an example

### PR DESCRIPTION
**Pull request by joelouthan**
Extended line runs past the side of the browser window

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by felixfontein** [comment]
Can you make the adjustments from #1597? Thanks.

**Review by joelouthan — COMMENTED** [review]
Moved multiline as instructed

**Comment by felixfontein** [comment]
Please make sure the diff looks the same as for https://github.com/ansible-collections/community.general/pull/1597/files

Right now, what you have will not execute in Ansible.

**Review by joelouthan — COMMENTED** [review]
Corrected with >

**Comment by felixfontein** [comment]
@joelouthan thanks. Do you want to keep it as-is, or format it a bit differently so it's easier to parse for humans?

**Comment by joelouthan** [comment]
@felixfontein keep it as is. I can read it.

**Comment by felixfontein** [comment]
@joelouthan thanks!

**Pull request merged**
