### PR TITLE
Add support for HashiCorp Vault JWT auth

### PR DESCRIPTION
**Pull request by mbrancato**
##### SUMMARY
This adds generic JWT authentication support for the HashiCorp Vault lookup plugin.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
hashi_vault

##### ADDITIONAL INFORMATION
The generic JWT auth API is used by the:

JWT auth - https://www.vaultproject.io/api-docs/auth/jwt#jwt-login
GCP auth - https://www.vaultproject.io/api-docs/auth/gcp#login
Kubernetes auth - https://www.vaultproject.io/api-docs/auth/kubernetes#login
even Azure and others...

### CODE REVIEW

**Comment by Akasurde** [comment]
@briantist Could you please review this? Thanks in advance.

**Comment by felixfontein** [comment]
This definitely needs the documentation and argument specifications updated.

**Comment by mbrancato** [comment]
Thanks for pointing that out. I've updated the docs for JWT support and added some other documentation improvements.

**Comment by felixfontein** [comment]
Let's hope there isn't too much overlap with the changes in #23 :)

**Comment by briantist** [comment]
Hi @mbrancato ! 

As @felixfontein suggested, there is some overlap with the changes in #23 .

In that PR I've refactored a lot of this plugin (and did some major documentation changes).

Part of that refactoring involved how the various auth methods are implemented (with separate methods for verification vs doing the authentication).

The best part I think is the revamp of plugin options, so you wouldn't need to do stuff like this anymore: `os.environ.get('VAULT_JWT', None)` (by defining it properly in documentation, the Ansible plugin framework does all the work; if it's appropriate the be defined in ansible.cfg it's just as easy to do that too with the INI options in the docs).



Anyway, whichever of these PRs lands first, the other would have some work ahead of them to resolve the conflicts and re-implement this method.

I may be biased but I think it's easier to add auth methods on top of #23 😄

---

That aside, here's some thoughts actually reviewing the PR:
- You're using the newer auth method class in hvac, but there's no fallback to the old method for support of earlier hvac versions. I've put in fallback support + warnings for older methods where possible in #23 so you can take a look there (there's also a comment that contains a makeshift list which hvac versions added new methods for with auth types)
- You're using the `gcp` auth method, since I guess under the hood hvac uses JWT for at least GCP/Azure/Kubernetes, but I don't think we should rely on the interface for a single auth method to remain generic JWT unless the project has committed to it. I see you opened https://github.com/hvac/hvac/issues/572 yesterday as well, so looking forward to where they land on that.
- Since JWT is not an actual supported auth method on its own (yet?), I would like to see the individual GCP/Azure/Kubernetes/??? auth methods added as options to the plugin, which each use their respective auth method in hvac. Maybe we would add JWT as well (relying on gcp or one of the underlying things), but I would document it as experimental. I might lean toward instead documenting that any of the aforementioned methods could be used for JWT instead.
- To that end, do you have any JWT use cases in mind that don't fall under the existing supported auth methods?

**Comment by mbrancato** [comment]
Hi @briantist - I agree that #23 should be merged first. I can try to rebase or merge in my branch since your PR is making so many changes.

As for JWT, it has long been its own auth method in Vault. There are some advantages to using it as it can be configured for any OIDC/JWT provider, including Azure and GCP. We use it with Azure because it is not dependent on MSI, meaning service principal identities may use JWT for authentication. This allows applications registered in AzureAD to access Vault.
https://www.vaultproject.io/api/auth/jwt

**Comment by briantist** [comment]
> Hi @briantist - I agree that #23 should be merged first. I can try to rebase or merge in my branch since your PR is making so many changes.
> 
> As for JWT, it has long been its own auth method in Vault. There are some advantages to using it as it can be configured for any OIDC/JWT provider, including Azure and GCP. We use it with Azure because it is not dependent on MSI, meaning service principal identities may use JWT for authentication. This allows applications registered in AzureAD to access Vault.
> https://www.vaultproject.io/api/auth/jwt

Yeah that does sound very useful, and I see from your link in the PR now that it's native in Vault itself. Seems like it's just that HVAC is missing it then? I hope they take your issue into consideration. It may help things along with them if you're able to submit a PR to HVAC for those changes.

I do think the re-use of methods is a real concern though; if we rely on the internal implementation of any one of those providers there's a higher risk of it breaking out from under us.

Any thoughts on the suggestion of adding in the individual JWT-using HVAC auth methods, and adding examples to documentation that explain those could be used for JWT in an ad-hoc way? 

One advantage of that is that if someone uses GCP in their playbook for another JWT purpose, and it breaks, they can switch it themselves to Azure or Kubernetes to try as a workaround (if it breaks in the library they're out of luck until the next collection release that includes a fix).

A higher lift alternative would be to implement the API calls separately from HVAC for the JWT auth method in this plugin until HVAC supports it. I don't particularly like reinventing the wheel but it would help keep `auth_method: jwt` stable.

In any case, not being someone terribly familiar with JWT, a few more examples in the docs (that are aimed at real world services) couldn't hurt.

JWT auth really seems like a useful feature so looking forward to some implementation of it!

**Comment by gundalow** [comment]
@mbrancato Thanks for this PR, looks like https://github.com/ansible-collections/community.general/pull/23 has been merged. Would you possibly be able to rebase this PR

**Comment by Andersson007** [comment]
@mbrancato any updates on this?
needs_info

**Comment by paulspiegel** [comment]
@mbrancato I'd like to use this functionality.  Is this PR still moving forward? Thanks!

**Comment by erikgb** [comment]
@mbrancato We would also love to see this feature added to the hashi_vault module. Can I assist in any way to get the PR ready to be merged?

**Comment by felixfontein** [comment]
Well, this PR needs to be rebased. In case the original author doesn't want to do it, it is probably good if someone else could do it. (They'd have to submit it as a PR under their name though. They can keep the original commit's author though to preserve ownership.)

**Comment by briantist** [comment]
See the previous discussion as well, I'd prefer to see better support in HVAC, request is here: https://github.com/hvac/hvac/issues/572

It also looks like that _may_ have solved in this PR https://github.com/hvac/hvac/pull/613 but I haven't looked too closely.

It would be great for this to be picked up again.

**Comment by erikgb** [comment]
@felixfontein @briantist I have created a WIP PR with a rebase of the original commits: https://github.com/ansible-collections/community.general/pull/1213. Please have a look so we can decide how to get this done.

**Comment by felixfontein** [comment]
Superseded by #1213.

**Pull request closed without merging**
