### PR TITLE
Handle negative integer values in osx_defaults

### LINKED ISSUE #134: osx_defaults integer type check is broken
##### SUMMARY

It's not possible to set negative value for using osx_defaults task.

```
  osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: -1
    state: present
```

It happens because of bad code in https://fossies.org/linux/ansible/lib/ansible/modules/system/osx_defaults.py:

```
       elif data_type in ["int", "integer"]:
          if not str(value).isdigit():
               raise OSXDefaultsException("Invalid integer value: {0}".format(repr(value)))
            return int(value)
```

related: https://github.com/ansible/ansible/issues/68772

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
osx_default

##### ANSIBLE VERSION
2.10

### PR DESCRIPTION
**Pull request by pshirshov**
See #134

### CODE REVIEW

**Comment by Akasurde** [comment]
@pshirshov Thanks for the contribution. Could you please add an integration test for this change in `tests/integration/targets/osx_defaults/tasks/main.yml` and changelog entry?

**Comment by gundalow** [comment]
@pshirshov Thanks for this bug fix.

Would you please be able to add a `changelog/fragment` file so we can merge this?

Do you think you'd be able to extend `tests/integration/targets/osx_defaults/tasks/main.yml` to include a test?

**Comment by pshirshov** [comment]
Nope, sorry. In case my fix is not up to your high standards you may just ignore it.

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.general/pull/676

**Comment by Andersson007** [comment]
@pshirshov thanks for fixing this

**Pull request closed without merging**
