### PR TITLE
osx_defaults: fix handling negative integers

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.general/issues/134

Completed copy of https://github.com/ansible-collections/community.general/pull/250 initially made by @pshirshov

osx_defaults: fix handling negative integers

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
osx_defaults

### CODE REVIEW

**Comment by Andersson007** [comment]
CC @Akasurde 
the alias file contains `skip docker`, is it ok? If yes, feel free to merge

**Comment by felixfontein** [comment]
@Andersson007 skip/docker is ok, since we don't want this to be run on Linux instances running inside docker. In fact, it should not be run anywhere except on macOS :)

**Comment by felixfontein** [comment]
@pshirshov @Andersson007 thanks for fixing this!

**Comment by Andersson007** [comment]
@felixfontein thanks for reviewing and merging!

**Pull request merged**
