### PR TITLE
Reading argument_specs from docs (attempt #3)

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
I have been trying to find a way to close the gap between the `DOCUMENTATION.options` yaml blob and the contents of  `argument_spec` when creating an `AnsibleModule`. The internal code in Ansible is off-limits for `modules`, `module_utils`, and even for `AnsibleModule` itself.

So, the next solution that came to my mind was to defer the responsibility of picking the YAML blobs to the user. This solution adds to `ModuleHelper`, and allows module developers to remove most (if not all) of the `argument_spec`, including `suboptions`/`options` for `type='dict'` (or `elements='dict'`).

Cases that cannot be imported from the documentation:
- deprecations
- `no_log`

As per the PR, this has been applied to three modules that use `ModuleHelper`, they are all passing the tests locally. This PR starts as a WIP exactly to check if that holds true in the CI.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
plugins/module_utils/mh/base.py
plugins/module_utils/mh/mixins/vars.py
plugins/module_utils/mh/module_helper.py
plugins/modules/packaging/language/cpanm.py
plugins/modules/system/xfconf.py
plugins/modules/web_infrastructure/jira.py

### CODE REVIEW

**Review by felixfontein — CHANGES_REQUESTED** [review]
Please note that such experiments will not get merged until such a procedure has been approved by the Ansible core team and/or by the Ansible Community Engineering Steering Committee.

I'm adding a negative review to avoid automatic merging by the bot.

**Comment by russoz** [comment]
I was waiting for something like this. 🙄

**Comment by felixfontein** [comment]
Well, a) it's a breaking change (the modules now need PyYAML installed), and b) ansible-core might eventually switch to another documentation system (which won't be compatible with this). There were already similar proposals before, and these should really be discussed in the proper venue, and this collection isn't that venue. Sorry for that :)

**Review by aminvakil — COMMENTED** [review]
:+1: on @felixfontein's notes.
Also I guess this brings confusion for later maintainers of these modules dealing with massive differences with modules in `ansible.builtin` or other modules from other collections.

**Comment by russoz** [comment]
@aminvakil my "evil" plan would be to promote this up to `ansible-core` one day. I think in the long run that would pay-off by potentially removing all the differences between docs and `argument_spec`. Right now we have two sources for that info, so of course we have discrepancies and synchronization issues. If we reduce that to one single source of truth, the problem should disappear and a whole bunch of checks in `validate-module` could go away.

**Comment by felixfontein** [comment]
That's something that should be discussed with the core team first IMO. They might already have a (mid- or long-term) plan for this.

**Comment by aminvakil** [comment]
> @aminvakil my "evil" plan would be to promote this up to `ansible-core` one day. I think in the long run that would pay-off by potentially removing all the differences between docs and `argument_spec`. Right now we have two sources for that info, so of course we have discrepancies and synchronization issues. If we reduce that to one single source of truth, the problem should disappear and a whole bunch of checks in `validate-module` could go away.

Aha, that would be appropriate. Although I'm not still sure about necessity of this at the end and if it adds more value than harm or not. I guess we'll have to see if you could convince core team ;)

**Comment by felixfontein** [comment]
I'll close this since this has no chance of being merged, needs a rebase, and has been inactive for some time. Thanks.

**Pull request closed without merging**
