### PR TITLE
Add check_and_failed option to pacemaker_cluster module

### PR DESCRIPTION
**Pull request by matbu**
In order to not set a state to a cluster while the
cluster in not in the expected state we need to check
it and fail, or poll until the cluster is in a required
state, example:
- name: Check pacemaker cluster running before upgrade
  pacemaker_cluster: state=online check_and_fail=true
  async: 30
  poll: 4

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by felixfontein** [comment]
Please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to) in changelogs/fragments/.

(You probably have to rebase with current `master` to see that directory. You can also simply create it yourself without rebasing; git does not care about directories, only about files.)

**Comment by matbu** [comment]
@felixfontein hm I rebased my fork, but I probably did mistake, I'm getting all commits from my last push :/

**Comment by felixfontein** [comment]
You need to update your local master first, probably, and then rebase against master. If you do `git rebase -i master`, remove all commits from the list which don't belong to your PR.

**Comment by gundalow** [comment]
bot_skip

**Comment by gundalow** [comment]
@matbu Git can be a pain sometimes, it's easy to get it into a confused state.

You should be able to `git pull --rebase upstream master`.

We have this guide for ansible/ansible https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html though remember that 

1) You'll need to refer to community.general instead
2) This is using the `master` branch, not `devel`

**Comment by Andersson007** [comment]
@matbu i'll close the PR. Feel free to create a new one instead (or claim to reopen this if you want to rebase), thanks!

**Pull request closed without merging**
