### PR TITLE
Fix command line construction in the puppet module

### PR DESCRIPTION
**Pull request by varesa**
##### SUMMARY
Fix command line construction in the `puppet` module related to check mode and using manifests directly

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
puppet

##### ADDITIONAL INFORMATION
Commit 69ead0ba7864b1e7367eb9755b51d30ecc0da0d2 in the ansible/ansible
repository introduced another if-statement in the middle of a if/elif pair,
which causes the elif to execute together with the original if
which created '--noop --no-noop' commands.

Another issue I noticed while fixing that was that if I apply an manifest directly, it tries to execute `--noop/path/manifest.pp` which fails.

**Test case 1**
```
---
- hosts: localhost
  tasks:
  - puppet:
```

Executed with:
```
ansible-playbook --check /test.yaml
```

Before change:
```
/usr/bin/puppet agent --onetime --no-daemonize --no-usecacheonfailure --no-splay --detailed-exitcodes --verbose --color 0 --noop --no-noop
```

After change:
```
/usr/bin/puppet agent --onetime --no-daemonize --no-usecacheonfailure --no-splay --detailed-exitcodes --verbose --color 0 --noop
```

**Test case 2**
```
---
- hosts: localhost
  tasks:
  - puppet:
      manifest: /test.pp
```

Executed with:
```
ansible-playbook --check /test.yaml
```

Before change (causes an error):
```
/usr/bin/puppet apply --detailed-exitcodes  --noop/test.pp
```

After change:
```
/usr/bin/puppet apply --detailed-exitcodes --noop  /test.pp
```

Tested with ansible 2.9.6

### CODE REVIEW

**Comment by felixfontein** [comment]
Please add a changelog fragment in `changelogs/fragments/`.

**Comment by gundalow** [comment]
@varesa Thank you for this bug fix. 

@brettmilford Hi, I wondered if you'd be able to take a look at this bugfix to Ansible’s `puppet` module, which builds on your improvement from https://github.com/ansible/ansible/pull/53095

cc @emonty @nibalizer I believe you are maintainers for the `puppet` module, would you be able to take a look at this bug fix?

**Comment by brettmilford** [comment]
@gundalow @varesa looks good to me. @varesa thanks for your commit :).

**Comment by gundalow** [comment]
@varesa Thank you for this improvement
@brettmilford Thank you for the prompt review

Merged, we will do a release of community.general to Galaxy towards the end of the month

**Pull request merged**
