### PR TITLE
Update postgresql_pg_hba.py

### LINKED ISSUE #1108: Module postgresql_pg_hba Throws KeyError When Setting Method Options
##### SUMMARY
Using Ansible embedded in Red Hat Satellite 6.6 receiving KeyError: 'options' for simple task to modify pg_hba.conf
**Note:** Hostname and User ID redacted.

If this has already been fixed in a later version, a back port (and possibly a Bugzilla) is needed to include in Red Hat Satellite.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_pg_hba

##### ANSIBLE VERSION

```paste below
ansible 2.8.16
  config file = /home/********/.ansible.cfg
  configured module search path = [u'/home/********/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 20 2020, 17:08:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/********/.ansible.cfg) = True
DEFAULT_HOST_LIST(/home/********/.ansible.cfg) = [u'/home/********/cpe-ansible/inventory']
DEFAULT_TIMEOUT(/home/********/.ansible.cfg) = 30
DEFAULT_VAULT_IDENTITY_LIST(/home/********/.ansible.cfg) = [u'satellite@~/ansible/.satellite', u'cache@~/ansible/.cache'
RETRY_FILES_ENABLED(/home/********/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux 7.9 (kernel: 3.10.0-1127.19.1.el7.x86_64)
Red Hat Satellite 6.6.3
FIPS mode enabled

##### STEPS TO REPRODUCE

```yaml
- name: configure user id map for local connections
  postgresql_pg_hba:
    dest:      "/var/lib/pgsql/10/data/pg_hba.conf"
    contype:   local
    databases: all
    method:    peer
    options:   "map=sysmap"
    users:     all
```
pg_hba.conf
```
local   replication     all     peer
local   all     all     peer
host    replication     all     127.0.0.1/32    scram-sha-256
host    replication     all     ::1/128 scram-sha-256
host    all     all     127.0.0.1/32    scram-sha-256
host    all     all     ::1/128 scram-sha-256
host    all     all     10.xxx.xx.0/23  scram-sha-256
```

##### EXPECTED RESULTS

```
TASK [CPE.postgresql : configure user id map for local connections] *********************************************************
ok: [********.vha.med.va.gov]
```

##### ACTUAL RESULTS

```paste below
TASK [CPE.postgresql : configure user id map for local connections] *********************************************************
task path: /home/********/.ansible/roles/CPE.postgresql/tasks/main.yml:70
Using module file /usr/lib/python2.7/site-packages/ansible/modules/database/postgresql/postgresql_pg_hba.py
Pipelining is enabled.
<********.vha.med.va.gov> ESTABLISH SSH CONNECTION FOR USER: None
<********.vha.med.va.gov> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 -o ControlPath=/home/********/.ansible/cp/6e7932688e ********.vha.med.va.gov '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-mjjreuqbecefkovouzbfqpmzeznirqju ; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<********.vha.med.va.gov> (1, '', 'FIPS mode initialized\r\nTraceback (most recent call last):\n  File "<stdin>", line 114, in <module>\n  File "<stdin>", line 106, in _ansiballz_main\n  File "<stdin>", line 49, in invoke_module\n  File "/tmp/ansible_postgresql_pg_hba_payload_eaUKvE/__main__.py", line 755, in <module>\n  File "/tmp/ansible_postgresql_pg_hba_payload_eaUKvE/__main__.py", line 727, in main\n  File "/tmp/ansible_postgresql_pg_hba_payload_eaUKvE/__main__.py", line 338, in add_rule\nKeyError: \'options\'\n')
<********.vha.med.va.gov> Failed to connect to the host via ssh: FIPS mode initialized
Traceback (most recent call last):
  File "<stdin>", line 114, in <module>
  File "<stdin>", line 106, in _ansiballz_main
  File "<stdin>", line 49, in invoke_module
  File "/tmp/ansible_postgresql_pg_hba_payload_eaUKvE/__main__.py", line 755, in <module>
  File "/tmp/ansible_postgresql_pg_hba_payload_eaUKvE/__main__.py", line 727, in main
  File "/tmp/ansible_postgresql_pg_hba_payload_eaUKvE/__main__.py", line 338, in add_rule
KeyError: 'options'
fatal: [********.vha.med.va.gov]: FAILED! => {
    "changed": false,
    "module_stderr": "FIPS mode initialized\r\nTraceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/tmp/ansible_postgresql_pg_hba_payload_eaUKvE/__main__.py\", line 755, in <module>\n  File \"/tmp/ansible_postgresql_pg_hba_payload_eaUKvE/__main__.py\", line 727, in main\n  File \"/tmp/ansible_postgresql_pg_hba_payload_eaUKvE/__main__.py\", line 338, in add_rule\nKeyError: 'options'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

### PR DESCRIPTION
**Pull request by sebasmannem**
Fixes #1108

##### SUMMARY
Fixes #1108

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
postgresql_pg_hba.py

##### ADDITIONAL INFORMATION
The module was accessing dict values using square brackets, and apparently in this case, the old rule did not have 'options' set, and new one has.
Using the .get method is safer (returns None if key not set).
With this change, if oldrule does not have options set, and rule does(or the other way around), a PgHbaRuleChanged is raised, which will replace the old rule for the new, which is as expected.

### CODE REVIEW

**Review by felixfontein — COMMENTED** [review]
Please add a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to).

**Comment by Andersson007** [comment]
@sebasmannem hi, thanks for the quick fix!
In addition to the changelog fragment @felixfontein mentioned, would be also nice to cover the case in tests, is this possible?

**Comment by sebasmannem** [comment]
I will add a changelog fragment and will look at a unit test.
But that needs a bit more time, so I need to see when I can pan that out.

**Comment by Andersson007** [comment]
@sebasmannem can't we just add the `options` case to the existing CI tests?

**Comment by Andersson007** [comment]
@sebasmannem please add `.yml` extension to the changelog fragment

**Comment by Andersson007** [comment]
I think the pr is ok without tests but if it's easy to add the case to the existing tests, it would be good

**Comment by sebasmannem** [comment]
I think I have a unit test. I will push it in first, to see it fail.
After that I will push with change to see it succeed.

**Comment by sebasmannem** [comment]
Yes, unittest fails. Now lets re add feature which should fix the unit test

**Comment by sebasmannem** [comment]
We are all good

**Review by Andersson007 — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@sebasmannem thanks for fixing this!
@felixfontein thanks for reviewing!

**Comment by sebasmannem** [comment]
@Andersson007 , @felixfontein , many thanks to the both of you :)

**Pull request merged**
