### PR TITLE
linode inventory plugin: fix default value of new option

### LINKED ISSUE #3337: In Linode dynamic inventory plugin, ip_style defaults to an invalid value
### Summary

After upgrading Ansible to 4.5.0 (from 4.3.0), I started getting this error when running any ansible playbook:

`[WARNING]:  * Failed to parse /home/oloryn/ansible/inventory/linode.yaml with
ansible_collections.community.general.plugins.inventory.linode plugin: Invalid type for configuration option
plugin_type: inventory plugin: ansible_collections.community.general.plugins.inventory.linode setting: ip_style :
Invalid type provided for "string": ['plain']
[WARNING]:  * Failed to parse /home/oloryn/ansible/inventory/linode.yaml with yaml plugin: Plugin configuration YAML
file, not YAML inventory
[WARNING]: Unable to parse /home/oloryn/ansible/inventory/linode.yaml as an inventory source`

 It would appear that ip_style is defaulting to a list, instead of to a string.  I've had to explicitly specify ip_style in my linode.yaml file to get around this.

### Issue Type

Bug Report

### Component Name

linode

### Ansible Version

ansible [core 2.11.4]
  config file = None
  configured module search path = ['/home/oloryn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/oloryn/ansible/.venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/oloryn/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/oloryn/ansible/.venv/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = True

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 20.04 under WSL

### Steps to Reproduce

When using the Linode inventory plugin, don't specify the ip_style parameter in the linode.yaml file - just let it use the default.

### Expected Results

Ansible should get the inventory list from Linode

### Actual Results

Ansible fails to get the linode inventory, and instead displays the following message:

`[WARNING]:  * Failed to parse /home/oloryn/ansible/inventory/linode.yaml with
ansible_collections.community.general.plugins.inventory.linode plugin: Invalid type for configuration option
plugin_type: inventory plugin: ansible_collections.community.general.plugins.inventory.linode setting: ip_style :
Invalid type provided for "string": ['plain']
[WARNING]:  * Failed to parse /home/oloryn/ansible/inventory/linode.yaml with yaml plugin: Plugin configuration YAML
file, not YAML inventory
[WARNING]: Unable to parse /home/oloryn/ansible/inventory/linode.yaml as an inventory source`

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #3337.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
linode inventory plugin

### CODE REVIEW

**Comment by russoz** [comment]
Hi @felixfontein , isn't that something that should have been picked up in the sanity test to begin with?

**Comment by russoz** [comment]
LGTM

**Comment by russoz** [comment]
Thanks for fixing this @felixfontein

**Comment by felixfontein** [comment]
@russoz thanks for reviewing and merging!

Yes, a sanity test would help, but that doesn't exist yet for non-modules - https://github.com/ansible/ansible/pull/71734 is still open...

**Pull request merged**
