### PR TITLE
Update to new Github account for notifications

### PR DESCRIPTION
**Pull request by florianpaulhoberg**
##### SUMMARY
Updating my authors name to my new account (for notifications regarding this module). Keeping this account for security reasons. 

##### ISSUE TYPE
- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by felixfontein** [comment]
@florianpaulhoberg thanks for this update! Can you approve this PR with your new account (@gyptazy)?

**Comment by felixfontein** [comment]
You will likely also have to update `.github/BOTMETA.yml`.

**Comment by gyptazy** [comment]
> @florianpaulhoberg thanks for this update! Can you approve this PR with your new account (@gyptazy)?

Confirmed.

> You will likely also have to update `.github/BOTMETA.yml`.

Thanks for the hint. Done.

**Comment by felixfontein** [comment]
@florianpaulhoberg / @gyptazy thanks a lot for fixing this :)

**Pull request merged**
