### PR TITLE
dig: remove support for the DLV record as the registry was decomissioned

### PR DESCRIPTION
**Pull request by jpmens**
##### SUMMARY
The DLV registry was decomissioned in 2017 (https://www.isc.org/blogs/dlv/) so it's high time we remove support for DLV records.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
dig

### CODE REVIEW

**Comment by felixfontein** [comment]
Right now querying for DLV records still works (it usually returns an empty result), so this is a breaking change that we cannot merge without a deprecation period.

**Comment by jpmens** [comment]
DLV’s deprecation period began in 2015, and all records from the ISC DLV zone [were removed in 2017](https://kb.isc.org/v1/docs/iscs-dnssec-look-aside-validation-registry).

The resource record type exists still, yes, but it is hugely unlikely that anybody uses it.

**Comment by felixfontein** [comment]
We still have a policy to deprecate features before removal. Someone could have forgotten a check for such a record somewhere in their playbooks which didn't fail so far. Removing the support without deprecation will break that playbook without advance warning.

**Comment by felixfontein** [comment]
I've created #4618 to deprecate it. Once stable-5 has been created this can be merged to `main`. (It will need to remove the deprecation added in #4618 as well though.) Also a `removed_features` [changelog fragment](https://docs.ansible.com/ansible/devel/community/collection_development_process.html#creating-a-changelog-fragment) is needed.

**Comment by felixfontein** [comment]
#4618 has been merged, so this needs to be rebased, the new `if` in https://github.com/ansible-collections/community.general/pull/4618/files#diff-b34c8245e0310c9b83d76a2f8e2c0815e13793f63b4aaebf682924a4204139eeR335 removed, and https://github.com/ansible-collections/community.general/pull/4618/files#diff-b34c8245e0310c9b83d76a2f8e2c0815e13793f63b4aaebf682924a4204139eeR34 updated to `C(DLV) has been removed in community.general 6.0.0.`. And of course it needs a `removed_feature` changelog fragment :)

**Comment by felixfontein** [comment]
@jpmens would you mind updating the PR? Then we can merge it now.

**Comment by jpmens** [comment]
I don't actually know how to, @felixfontein, because I created this patch in Github Web. I've no idea how to amend it to include a fragment.yml

**Comment by felixfontein** [comment]
@jpmens you probably need to resort to a proper git client then ;-)

In case you don't want to I can also make the changes, it seems you allowed me to push to your branch.

**Comment by jpmens** [comment]
Please be so kind as to make the necessary changes. Thank you!

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@jpmens thanks for preparing this PR! :)

**Comment by jpmens** [comment]
@felixfontein thank **you** for completing my homework. :-)

**Pull request merged**
