### PR TITLE
Can set session_prefix, node_prefix and service_prefix rules via consul_acl

### LINKED ISSUE #1085: Set session_prefix rule via consul_acl
##### SUMMARY
I can manually set in Consul:
```
session_prefix "" {
  policy = "write"
}
```

But via consul_acl I get errors.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
consul_acl

##### ADDITIONAL INFORMATION

```yaml
  - name: Create an acl with specific token with both key and service rules
    consul_acl:
      mgmt_token: "{{ consul_mgmt_token }}"
      name: Token for traefik
      token: "{{ consul_traefik_token }}"
      rules:
        - key: traefik
          policy: write
        - session: ""
          policy: write
        - session_prefix: ""
          policy: write
```

Error:
```
TASK [traefik : Create an acl with specific token with both key and service rules] *************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: A rule requires one of agent/event/key/keyring/node/operator/query/service/session and a policy.
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_consul_acl_payload_r7_luy0y/ansible_consul_acl_payload.zip/ansible/modules/clustering/consul_acl.py\", line 663, in <module>\n  File \"/tmp/ansible_consul_acl_payload_r7_luy0y/ansible_consul_acl_payload.zip/ansible/modules/clustering/consul_acl.py\", line 639, in main\n  File \"/tmp/ansible_consul_acl_payload_r7_luy0y/ansible_consul_acl_payload.zip/ansible/modules/clustering/consul_acl.py\", line 426, in decode_rules_as_yml\nValueError: A rule requires one of agent/event/key/keyring/node/operator/query/service/session and a policy.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### PR DESCRIPTION
**Pull request by 4n70w4**
##### SUMMARY
Fixes #1085

##### ISSUE TYPE

- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
consul_acl

### CODE REVIEW

**Comment by felixfontein** [comment]
You need a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to).

**Comment by 4n70w4** [comment]
@felixfontein no, I don't need it =) You can make it self if need.

**Comment by felixfontein** [comment]
Without a changelog fragment, your PR has no chance of getting merged. Sorry.

I don't use or know much about the consul modules, so I can't write it for you either.

**Comment by Andersson007** [comment]
@4n70w4 , will you add the changelog fragment @felixfontein mentioned? this is a requirement

**Comment by felixfontein** [comment]
needs_info

**Comment by felixfontein** [comment]
Closing since there was no more reaction. @4n70w4 if you're interested again in working on this, please ping me. If someone else is interested in continuing this PR, please also write it here so we can coordinate.

**Pull request closed without merging**
