### PR TITLE
Add inventory alicloud_ecs

### PR DESCRIPTION
**Pull request by lixue323**
##### SUMMARY
Add plugin alicloud_ecs

##### COMPONENT NAME
inventory/alicloud_ecs

### CODE REVIEW

**Comment by lixue323** [comment]
> Also, some kind of tests would be good. Maybe some integration tests (marked as `unsupported`)?
I didn't really understand the meaning of the last sentence, I guess it was for me to write a test case, should I understand it that way？

**Comment by lixue323** [comment]
> Adding "Request changes" review to make sure this isn't merged before #108
> 
> Also, some kind of tests would be good. Maybe some integration tests (marked as `unsupported`)?

@felixfontein I didn't really understand the meaning of the last sentence, I guess it was for me to write a test case, should I understand it that way

**Comment by felixfontein** [comment]
We started with a new rule for new plugins and modules in ansible/ansible last year that says that every new plugin/module must have tests (at least unit tests or integration tests; integration tests are allowed to be marked as `unsupported`, i.e. they are not run automatically in CI, if they require a special environment, such as accounts at cloud providers). IMO this should also be true for new plugins/modules in community.general and community.network.

BTW, unrelated to this, but since you created a large amount of new module/plugin PRs: have you thought about making a dedicated collection for alicloud? That has two big advantages:
1. You are independent from any restrictions on community.general, and you are free to set up your own (internal?) CI for the collection.
2. You can release your collection whenever you think a release is needed, and you can merge PRs at your own will.

(CC @gundalow)

**Comment by lixue323** [comment]
@felixfontein I want to know the  difference between making a collection under community like community.aws, community.network and making a collection elsewhere?

**Comment by felixfontein** [comment]
@lixue323 I think the difference is that `community.*` collections are not driven by a company, but by unrelated people from the community. For the alicloud modules, it probably makes sense to have them in a collection `alibaba.alicloud`. @gundalow are there some details I'm forgetting?

**Comment by lixue323** [comment]
1. how  to create a repository alibaba.alicloud  in Ansible [Collections](https://github.com/ansible-collections) 
2. I need to  publish them to galaxy later, right?  
3.  About the documentation, I do nothing, I make collection alibaba.alicloud under collections, the documentation will be automatically generated in ansible doc, right?

@felixfontein @gundalow Sorry i have a lot of questions because i am confused

**Comment by gundalow** [comment]
@lixue323 Hi,
We recommend that when someone wants to add a group of new modules they should generally go into their own collection. If that collection is owned by a company (rather than a set of unrelated community members) then the repo should be in the organizations GitHub repo.

So I suggest you create your collection under https://github.com/alibaba

**Comment by lixue323** [comment]
@gundalow I think you are right, but I still have a question. How to make the subsequent alicloud modules’s documentation  into the official ansible documentation [https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html](url)

**Comment by gundalow** [comment]
> @gundalow I think you are right, but I still have a question. How to make the subsequent alicloud modules’s documentation into the official ansible documentation [https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html](url)

Hi,
We don't have an answer to that today, though we should do in the next few weeks and months.

Given you've said you are happy to move to a Collection I'll close the other PRs.

**Comment by gundalow** [comment]
Are you still interested in setting up a dedicated collection for this?

**Comment by Akasurde** [comment]
@gundalow I think this is being handled in https://github.com/alibaba/alibaba.alicloud/pull/272. Thanks.

**Pull request closed without merging**
