### PR TITLE
unit test helper: big revamp

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY

Revamped the test helper to be able to support more than just `run_command()`. This PR makes the code more generic and expansible, allowing for easier tests in the future.

##### ISSUE TYPE

- Test Pull Request

##### COMPONENT NAME

tests/unit/plugins/modules/conftest.py
tests/unit/plugins/modules/helper.py
tests/unit/plugins/modules/test_cpanm.py
tests/unit/plugins/modules/test_cpanm.yaml
tests/unit/plugins/modules/test_django_check.py
tests/unit/plugins/modules/test_django_check.yaml
tests/unit/plugins/modules/test_django_check.yaml.license
tests/unit/plugins/modules/test_django_command.py
tests/unit/plugins/modules/test_django_command.yaml
tests/unit/plugins/modules/test_django_createcachetable.py
tests/unit/plugins/modules/test_django_createcachetable.yaml
tests/unit/plugins/modules/test_facter_facts.py
tests/unit/plugins/modules/test_facter_facts.yaml
tests/unit/plugins/modules/test_gconftool2.py
tests/unit/plugins/modules/test_gconftool2.yaml
tests/unit/plugins/modules/test_gconftool2_info.py
tests/unit/plugins/modules/test_gconftool2_info.yaml
tests/unit/plugins/modules/test_gio_mime.py
tests/unit/plugins/modules/test_gio_mime.yaml
tests/unit/plugins/modules/test_opkg.py
tests/unit/plugins/modules/test_opkg.yaml
tests/unit/plugins/modules/test_puppet.py
tests/unit/plugins/modules/test_puppet.yaml
tests/unit/plugins/modules/test_snap.py
tests/unit/plugins/modules/test_xfconf.py
tests/unit/plugins/modules/test_xfconf.yaml
tests/unit/plugins/modules/test_xfconf_info.py
tests/unit/plugins/modules/test_xfconf_info.yaml

### CODE REVIEW

**Comment by russoz** [comment]
The CI error seems to be unrelated with the change. @felixfontein could you please confirm? TIA

**Review by felixfontein — APPROVED** [review]

**Review by felixfontein — COMMENTED** [review]
It seems that somewhere the order of the tests comes from a dictionary. In Python 3.5 (where the tests fail) the order is 'random', while in Python 3.6+ it is insertion order. (No idea why it works in 2.7 since there it should be 'random' as well...)

**Comment by russoz** [comment]
> It seems that somewhere the order of the tests comes from a dictionary. In Python 3.5 (where the tests fail) the order is 'random', while in Python 3.6+ it is insertion order. (No idea why it works in 2.7 since there it should be 'random' as well...)

I do recall something about that: in 2.7 it was "random" but the seed to the random generator was kinda fixed, so the order of the keys was deterministic across multiple runs of the script. They improved that with 3.5, and I had not kept track, I did not know 3.6 onwards was using insertion order. Anyways, it is not something to rely on.

**Comment by russoz** [comment]
hi @felixfontein anything else I need to adjust in this one? TIA

**Comment by russoz** [comment]
> It seems that somewhere the order of the tests comes from a dictionary. In Python 3.5 (where the tests fail) the order is 'random', while in Python 3.6+ it is insertion order. (No idea why it works in 2.7 since there it should be 'random' as well...)

Yup, I gave it another look. I think I know what it is: the order of the tests, in the code, is a `list`, but as the test functions are dynamically added to the module, they are included into the underlying `dict` that supports the module's attributes. Not sure it does explain it.

I chose not parameterizing the test function so that fixtures could be used (with pytest.mark.usefixtures) per test function, rather than for all test cases.

Anyways, whatever test code is performing this comparison between collected tests is clearly relying on the order provided by the module. I guess for the time being the only option I have is to create one single function and parameterize it. This will become a problem if developers use the test helper and create extra tests within the same test_module. Anyway I can skip Python 3.5?

**Comment by russoz** [comment]
the problem lies in the pytest-xdist plugin used here:

**Comment by felixfontein** [comment]
> hi @felixfontein anything else I need to adjust in this one? TIA

The tests were failing on Python 3.5, as you probably noticed :)

community.general 11.0.0 will drop support for Python 3.5 (though not for 2.7), and 12.0.0 will drop support for Python 2.7 as well, so at that point you can do this again :)

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@russoz thanks for your contribution!

**Pull request merged**
