### PR TITLE
[FIX] proxmox_kvm: fetch vm status from node-specific API endpoint to ensure fresh state

### LINKED ISSUE #7817: Proxmox_kvm status check wrong info
### Summary

When proxmox_kvm want to change the state, it's check the vm current status:

        vm = proxmox.get_vm(vmid)
        status['status'] = vm['status']
        if vm['status'] == 'running':
            module.exit_json(changed=False, vmid=vmid, msg="VM %s is already running" % vmid, **status)

the get_vm() func use cluster/resources api call, but that is sometimes not fresh status (laggy), confirmed by proxmox dev: https://forum.proxmox.com/threads/inconsistent-vm-status.139390/post-622623

The check sould use the right api call:

        current = proxmox.proxmox_api.nodes(vm['node']).qemu(vmid).status.current.get()['status']
        status['status'] = current
        if current == 'running':
            module.exit_json(changed=False, vmid=vmid, msg="VM %s is already running" % vmid, **status)

### Issue Type

Bug Report

### Component Name

proxmox_kvm

### Ansible Version

2.14.2

### Community.general Version

8.2.0

### Configuration

_No response_

### OS / Environment

Ubuntu Jammy

### Steps to Reproduce

    - name: Stop VM
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: secret
        api_host: helldorado
        name: spynal
        node: sabrewulf
        state: stopped

    - name: Reconfigure VM (remove ide2, etc)

    - name: Start VM
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: secret
        api_host: helldorado
        name: spynal
        node: sabrewulf
        state: started

### Expected Results

VM started again

### Actual Results

error with: "VM 42 is already running"

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by nxet**
##### SUMMARY

Following up on https://github.com/ansible-collections/community.general/issues/7817 and the changes suggested by OP.
Fixes #7817

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
proxmox_kvm

##### ADDITIONAL INFORMATION
Simply implemented changes suggested by OP, for more details see original issue #7817

### CODE REVIEW

**Comment by nxet** [comment]
I'm sorry to bother but I'm struggling to understand what went wrong with the failed test.
Is there's anything I can do to get this straight? Because from the output it would seem there's a lot more than my tiny patch.

**Review by felixfontein — COMMENTED** [review]
Thanks for your contribution! Please ignore the failing third-party-check test, it's quite flaky, and unfortunately it doesn't seem to be easy enough to get rid of it that I managed yet :)

**Review by krauthosting — APPROVED** [review]
LGTM :+1:

**Comment by felixfontein** [comment]
@nxet thanks a lot for your contribution!
@krauthosting thanks for reviewing this!

**Pull request merged**
