### PR TITLE
[WIP] Tidy up validate-modules:doc-choices-do-not-match-spec

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
Tidy up on sanity tests' ignore files, removing lines with validation-modules for these modules.

The focus was to pass the tests so no code was changed other than adjusting argument_spec for missing types or inconsistencies with the docs. The priority has been not to change any functionality, but to ensure that code and docs are synchronized.

Some lines were added back to the files, but a total of 59 lines were removed (among 2.9, 2.10 and 2.11).

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
plugins/modules/remote_management/stacki/stacki_host.py
plugins/modules/remote_management/manageiq/manageiq_provider.py
plugins/modules/remote_management/ipmi/ipmi_power.py
plugins/modules/remote_management/ipmi/ipmi_boot.py
plugins/modules/remote_management/hpilo/hpilo_boot.py
plugins/modules/clustering/znode.py
plugins/modules/clustering/etcd3.py
plugins/modules/cloud/univention/udm_user.py
plugins/modules/cloud/univention/udm_share.py
plugins/modules/cloud/univention/udm_dns_zone.py
plugins/modules/cloud/univention/udm_dns_record.py
plugins/modules/cloud/spotinst/spotinst_aws_elastigroup.py
plugins/modules/cloud/smartos/vmadm.py
plugins/modules/cloud/lxc/lxc_container.py

### CODE REVIEW

**Comment by russoz** [comment]
+WIP

**Comment by russoz** [comment]
+label WIP

**Comment by russoz** [comment]
Rebase hell is in place. Will close this PR and raise another one.

**Comment by russoz** [comment]
close_me Brave Sir Robin chickened out

**Review by keachi — COMMENTED** [review]
udm_* lgtm

**Pull request closed without merging**
