### PR TITLE
[WIP] etcd3 : re-enable tests

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
tests/integration/targets/lookup_etcd3/aliases

### CODE REVIEW

**Comment by russoz** [comment]
hi @Akasurde are we waiting for some other PR on this case?

**Comment by felixfontein** [comment]
@Akasurde are you still working on this?

needs_info

**Comment by felixfontein** [comment]
@Akasurde ping

**Comment by Akasurde** [comment]
I am no longer working on this.

**Pull request closed without merging**
