### PR TITLE
[WIP] [stable-1] Add information on docker module migration

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Documents the upcoming docker content removal for community.general 2.0.0.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
collection

### CODE REVIEW

**Comment by felixfontein** [comment]
My idea is to merge this once community.docker 1.0.0 has been released and is included in [ansible.in](https://github.com/ansible-community/ansible-build-data/blob/main/2.10/ansible.in).

Let's polish this one so we can use it as a template for other content (community.routeros, community.postgresql, ...).

**Comment by felixfontein** [comment]
Note that this PR is for stable-1 directly, so this announcement will show up in the 1.3.0 changelog, but *not* in the 2.0.0 changelog.

**Review by gundalow — APPROVED** [review]
Wording and examples are great. Thank you.

**Review by dmsimard — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@acozine @gundalow @dmsimard thanks a lot for reviewing this!

**Pull request merged**
