### PR TITLE
Removal of myself as maintainer

### PR DESCRIPTION
**Pull request by dj-wasabi**
##### SUMMARY

Removal of myself as a maintainer for gitlab related modules.

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by felixfontein** [comment]
Thank you very much for maintaining the modules and creating some of them!

To make the sanity tests happy, you need to add `ignore: dj-wasabi` roughly here: https://github.com/ansible-collections/community.general/blob/c9a87b40cb9242b32bdb62bad0de6e649c58e1a0/.github/BOTMETA.yml#L533 - that tells the sanity check that while you're an author of some of the modules, it should ignore that you don't show up as a maintainer.

**Comment by dj-wasabi** [comment]
> Thank you very much for maintaining the modules and creating some of them!
> 
> To make the sanity tests happy, you need to add `ignore: dj-wasabi` roughly here:
> 
> https://github.com/ansible-collections/community.general/blob/c9a87b40cb9242b32bdb62bad0de6e649c58e1a0/.github/BOTMETA.yml#L533
> 
> - that tells the sanity check that while you're an author of some of the modules, it should ignore that you don't show up as a maintainer.

Thank you! I have updated the PR.

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@dj-wasabi thanks again for all that you did for the Ansible community :)

**Comment by dj-wasabi** [comment]
@felixfontein  Thank you, that is really nice to hear ❤️ .  I had a really great time with working on new and improving modules and of course, Ansible in general!

**Pull request merged**
