### PR TITLE
Add myself to commit-rights.md

### PR DESCRIPTION
**Pull request by aminvakil**
##### SUMMARY
See title :tada: !

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
LGTM, thank you for the great and regular contribution!
at least 152 merged PRs to the ansible-collections org, 3 open, and great review history is definitely a great achievement!

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@aminvakil thanks for joining the team! :)
@Andersson007 thanks for organizing this!

**Comment by Andersson007** [comment]
@aminvakil you're with `triage` -> `write`. BTW you can remove your login from `supershipit` at the top (IIRC) of BOTMETA.yml because it's no longer needed.

**Comment by Andersson007** [comment]
cc @russoz I wrote to you in IRC but in case you'll miss it, feel free to create the same PR for yourself!
Please let me know after

**Pull request merged**
