### PR TITLE
BOTMETA: hashids plugin - add a maintainer

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/community.general/pull/2244

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
BOTMETA.yml

### CODE REVIEW

**Comment by felixfontein** [comment]
@Andersson007 thanks for all the PRs! This one unfortunately now has a conflict... Can you please rebase? Thanks :)

**Comment by Andersson007** [comment]
@felixfontein done, thanks for pointing out!

**Comment by felixfontein** [comment]
@Andersson007 thanks for the PR!

**Comment by Andersson007** [comment]
@felixfontein thanks for reviewing and merging!

**Pull request merged**
