### PR TITLE
add Redfish VirtualMediaInsert and VirtualMediaEject commands

### LINKED ISSUE #493: Redfish: support Virtual Media configuration
##### SUMMARY

Add support for Virtual Media configuration

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

redfish_command

##### ADDITIONAL INFORMATION

The feature will be used for configuration of Virtual Media:

- insert an ISO image as a CD, DVD or USB device
- eject the virtual media

See additional discussion in the original issue here:
https://github.com/ansible/ansible/issues/58941

### PR DESCRIPTION
**Pull request by billdodd**
##### SUMMARY

This PR adds commands to insert and eject virtual media on a Redfish service. This enables, for example, the ability to "insert" a bootable image from a URL into a virtual drive and then boot from that drive into the OS on the image.

[Note: This PR manually migrated from ansible/ansible/pull/68053]

Fixes #493 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

redfish_utils.py
redfish_command.py

##### ADDITIONAL INFORMATION

Example playbook snippets for the new VirtualMediaInsert and VirtualMediaEject commands:

```
 - name: Insert Virtual Media
    redfish_command:
      category: Manager
      command: VirtualMediaInsert
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      virtual_media:
        image_url: 'http://example.com/images/SomeLinux-current.iso'
        media_types:
          - CD
          - DVD
      resource_id: BMC
```

```
 - name: Eject Virtual Media
    redfish_command:
      category: Manager
      command: VirtualMediaEject
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      virtual_media:
        image_url: 'http://example.com/images/SomeLinux-current.iso'
      resource_id: BMC
```

Output for the new commands:

```paste below
$ ansible-playbook -i myinventory.yml playbooks/manager/ilo/insert_virtual_media.yml
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.

PLAY [Insert Virtual Media] ****************************************************

TASK [Insert Virtual Media] ****************************************************
changed: [ilo]

PLAY RECAP *********************************************************************
ilo                        : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

```
$ ansible-playbook -i myinventory.yml playbooks/manager/ilo/eject_virtual_media.yml
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.

PLAY [Eject Virtual Media] *****************************************************

TASK [Eject Virtual Media] *****************************************************
changed: [ilo]

PLAY RECAP *********************************************************************
ilo                        : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### CODE REVIEW

**Comment by mraineri** [comment]
shipit

**Comment by billdodd** [comment]
@felixfontein When convenient, this is ready to merge. Thanks again.

**Comment by felixfontein** [comment]
@billdodd thanks for implementing this!
@mraineri thanks for reviewing!

**Comment by rlopez133** [comment]
Hi @billdodd , I'm trying to get this to work and no luck so far. Scrubbing creds but basically this is what I'm trying

```
- name: Insert Virtual Media
  redfish_command:
    category: Manager
    command: VirtualMediaInsert
    baseuri: "192.168.0.2"
    username: "user"
    password: "password"
    virtual_media:
      image_url: 'http://{{ ansible_default_ipv4.address }}:8080/installer-image.iso'
      media_types:
      - CD
      - DVD
    resource_id: BMC
```

If I leave `resource_id: BMC` I get `"msg": "Manager resource BMC not found"`. 

If I remove `resource_id : BMC` , I get `"msg": "Unable to find an available VirtualMedia resource supporting ['CD', 'DVD']"`

There is one caveat to all this that I'm trying is that I'm attempting to use this on Ansible 2.9. I'm still wrapping my head around collections and just wanted to _try_ this out. 

What I did:
- In my roles dir, I have a library and module_utils dir where I placed redfish_command.py in library and redfish_utils.py in the module_utils with your patches. I then went off and modified the from statement that had

```
#from ansible_collections.community.general.plugins.module_utils.redfish_utils import RedfishUtils
```
to:
```
from ansible.module_utils.redfish_utils import RedfishUtils
```
And this allows me to run the module. 

I'm running this on a Dell PowerEdge R730xd. 

Thanks,
Roger

**Comment by billdodd** [comment]
> If I remove `resource_id : BMC` , I get `"msg": "Unable to find an available VirtualMedia resource supporting ['CD', 'DVD']"`

What do the JSON payloads of your available VirtualMedia resources look like? Look at the VirtualMedia collection to find those URIs.

The VirtualMedia collection URI should be at a location like this: 

`/redfish/v1/Managers/{ManagerId}/VirtualMedia`

And the VirtualMedia resource URIs should be like this:

`/redfish/v1/Managers/{ManagerId}/VirtualMedia/{VirtualMediaId}`

**Comment by rlopez133** [comment]
@billdodd thanks for the tips!

A couple things for someone in the future googling :) 

the resource_id for my Dell hardware was `iDRAC.Embedded.1` so you need it to look like
```
resource_id: iDRAC.Embedded.1
```

I ran into an issue where I had a previous ISO mounted and didn't realize thus my Insert Virtual Media would not work. My advice is to always disconnected prior to attempting to connect so I added the following:
```
- name: Eject Virtual Media
  redfish_command:
    category: Manager
    command: VirtualMediaEject
    baseuri: "192.168.0.2"
    username: "user"
    password: "password"
    virtual_media:
      image_url: 'http://{{ ansible_default_ipv4.address }}:8080/installer-image.iso'
    resource_id: BMC
```

**Comment by billdodd** [comment]
@rlopez133 Ah, that makes sense. Glad you were able to get it working!

**Comment by rlopez133** [comment]
@billdodd one last question for ya :) Is there an easy way to then set One time boot to virtual media?

example from: 

```
- name: Set one-time boot device to {{ bootdevice }}
  redfish_command:
    category: Systems
    command: SetOneTimeBoot
    bootdevice: "{{ bootdevice }}"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
```

Attempted to use "Cd" for bootdevice and a no go. The options available are: 
```
allowable values (['None', 'Pxe', 'Cd', 'Floppy', 'Hdd', 'BiosSetup', 'Utilities', 'UefiTarget', 'SDCard', 'UefiHttp'])"}
```
I didn't see virtual media as an option. I'm looking for a generic way to set the one time boot device to mount the ISO on any server do its install then eject it later on. Appreciate all the help!

**Comment by billdodd** [comment]
Hmm. I haven't tried that. I would assume that 'Cd' would be the appropriate choice. What was the error or behavior when you tried that?

**Comment by rlopez133** [comment]
@billdodd it actually attempts to boot into a real Cd, can't and then just boots into its existing OS

**Comment by rlopez133** [comment]
Looking at racadm it shows
```
racadm help iDRAC.ServerBoot.FirstBootDevice
FirstBootDevice           -- Configures the first boot device
Usage                     -- Normal;
				PXE;
				HDD (Hard Disk Drive);
				CD-DVD (Local CD/DVD);
				BIOS (BIOS Setup);
				vFDD (Virtual Floppy);
				VCD-DVD (Virtual CD/DVD/ISO);
				FDD (Local Floppy/Primary Removable Media);
				SD (Local SD Card);
				F10 (Lifecycle Controller);
				F11 (BIOS Boot Manager);
				UEFIDevicePath;
				Attached vFlash Partition Label
Required License          -- RACADM
Dependency                -- None
```
So if I could somehow add VCD-DVD as a media type, this likely would work.

**Comment by billdodd** [comment]
Yes, it looks like this is a limitation on the iDRAC. I came across this script that uses an Oem action to specify a virtual media device:

https://github.com/dell/iDRAC-Redfish-Scripting/blob/master/Redfish%20Python/SetNextOneTimeBootVirtualMediaDeviceOemREDFISH.py

But I don't see a non-Oem Redfish way to do it currently.

**Comment by rlopez133** [comment]
Thanks for that. 

Was trying something like the below but yet to find the solution. Was reading https://github.com/dell/iDRAC-Redfish-Scripting/issues/90 more details but couldn't find the 503 issue. They get it because there is a job in the queue but mine doesn't have a job in the queue.  Anyway appreciate all the help! 

```
- name: Set Boot Override to VirtualMedia
  uri:
    url: "https://192.168.0.2/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration"
    validate_certs: no
    method: POST
    user: "ADMIN"
    password: "PASSWORD"
    headers:
      accept: application/json
      content-type: application/json
    body: '{"ShareParameters":{"Target":"ALL"},"ImportBuffer":"<SystemConfiguration><Component FQDD=\"iDRAC.Embedded.1\"><Attribute Name=\"ServerBoot.1#BootOnce\">Enabled</Attribute><Attribute Name=\"ServerBoot.1#FirstBootDevice\">VCD-DVD</Attribute></Component></SystemConfiguration>"}'
```

```
TASK [install : Set Boot Override to VirtualMedia] ****************************************************************************
FAILED! => {"accept_ranges": "bytes", "cache_control": "no-cache", "changed": false, "connection": "close", "content": "", "content_type": "application/json; charset=utf-8", "date": "Tue, 23 Jun 2020 21:41:27 GMT", "elapsed": 4, "msg": "Status code was 503 and not [200]: HTTP Error 503: Service Unavailable", "redirected": false, "server": "iDRAC/8", "status": 503, "strict_transport_security": "max-age=63072000", "transfer_encoding": "chunked", "url": "https://192.168.0.2/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration", "vary": "Accept-Encoding"}
```

**Comment by billdodd** [comment]
I'll bring this up in our tools meeting on Thursday and see if I can get some more insight.

**Comment by rlopez133** [comment]
@billdodd In other news, attempted exactly what I had which does mount on say ServerA, ran it now on ServerB and it complains about CD,DVD. Same server type, same firmware on both :( 

Bios: 2.11.0
iDRAC FW: 2.70.70.70
PowerEdge R730xd

I figured I'd share that. 

```
FAILED! => {"changed": false, "msg": "Unable to find an available VirtualMedia resource supporting ['CD', 'DVD']"}
```
And what my task looks like

```
- name: Insert Virtual Media
  redfish_command:
    category: Manager
    command: VirtualMediaInsert
    baseuri: "192.168.0.2"
    username: "ADMIN"
    password: "PASSWORD"
    virtual_media:
      image_url: "http://{{ ansible_default_ipv4.address }}:8080/installer-image.iso"
      media_types:
      - CD
      - DVD
    resource_id: iDRAC.Embedded.1

```

**Comment by plemelin** [comment]
> > If I remove `resource_id : BMC` , I get `"msg": "Unable to find an available VirtualMedia resource supporting ['CD', 'DVD']"`
> 
> What do the JSON payloads of your available VirtualMedia resources look like? Look at the VirtualMedia collection to find those URIs.
> 
> The VirtualMedia collection URI should be at a location like this:
> 
> `/redfish/v1/Managers/{ManagerId}/VirtualMedia`
> 
> And the VirtualMedia resource URIs should be like this:
> 
> `/redfish/v1/Managers/{ManagerId}/VirtualMedia/{VirtualMediaId}`

First of all, very sorry to bump this ages after it was closed.

If you search for `"Unable to find an available VirtualMedia resource supporting ['CD', 'DVD']"` in Google, you will end up in this thread. 

One of the reason you will also get this message if your target is unable to download the resources you set for `image_url`. 

In my case, my iDrac was on a different network than my server. My iDrac did not have access to my web server with the ISO I was trying to load.

**Comment by eGGnogSC** [comment]
This thread may be dead, but is it possible to use the VirtualMediaEject without an image_url? I would image it is not an uncommon use case to eject ANY VirtualMedia prior to doing a VirtualMediaInsert. In the case where multiple isos may be used for various uses, the user may not know what VirtualMedia is currently Inserted. I suppose you could run a task to get the virtual media that is currently inserted and use it as a var for the eject, but it would be useful to have the ability to eject whatever media is inserted.

**Comment by mraineri** [comment]
From a Redfish perspective, you're correct in that the image URI is not needed. The image URI from Ansible is used to find the instance to eject, so if you want to support your use case of having multiple virtual media instances mounting the same image, there would need to be another parameter used to identify which virtual media instance to eject (perhaps the resource Id of the virtual media).

**Comment by pavol-ipoth** [comment]
@rlopez133 i have same problem 4 servers with same firmware work and 5-th booting from physical CD...

**Pull request merged**
