### PR TITLE
Grant supershipit to new maintainers

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Grant supershipit to new maintainers

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
BOTMETA.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
recheck

**Comment by Andersson007** [comment]
@aminvakil as a downside, you will receive notifications about all issue / PRs but as I can see you're subscribed, so if you're ok with it, please approve (if once you decide to unsubscribe, let us know to remove this line). Thanks!

**Comment by Andersson007** [comment]
@russoz please approve as well if it's fine for you (if you decide to unsubscribe once, please let us know too, we'll remove your login).

**Review by aminvakil — APPROVED** [review]
Yes, receiving notifications if fine for me, I added a filter on my mail client to move c.g. emails to a specific folder, therefore my inbox doesn't get full :)

**Comment by russoz** [comment]
shipit

**Review by russoz — APPROVED** [review]

**Comment by felixfontein** [comment]
@aminvakil @russoz thanks a lot for stepping up! :)

With supershipit, you should be able to merge most PRs with `shipit`, so be careful when writing it ;) Supershipit gives your `shipit` special powers, so you can also merge stuff without a second person involved. (I haven't used it for a while, it might be that you have to write it another time if no other maintainer wrote `shipit`. I guess you'll figure out!) If you are not sure whether PRs should be merged, you can always ping me, then I can take a look.

(Also please don't add `shipit` on PRs which target other branches than `main`, like `stable-x`.)

**Pull request merged**
