### PR TITLE
Fix pylint errors

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
ansible-core devel's ansible-test is using a newer pylint, which makes CI fail. This fixes the problems it exposes.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Review by kristianheljas — APPROVED** [review]
All good!

**Review by mariolenz — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@kristianheljas @mariolenz thanks a lot for reviewing this!

**Comment by felixfontein** [comment]
@kristianheljas @mariolenz thanks a lot!

**Pull request merged**
