### PR TITLE
BOTMETA.yml: add a new maintainer of facter module

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/community.general/pull/768

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
BOTMETA.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
@gamethis could you please approve this PR?

**Comment by Andersson007** [comment]
@gamethis if you're still happy to be added as a maintainer, please approve the PR:)

**Review by gamethis — APPROVED** [review]

**Review by gamethis — APPROVED** [review]
looks good happy to help

**Comment by felixfontein** [comment]
@gamethis thanks!

**Review by felixfontein — APPROVED** [review]

**Pull request merged**
