### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Adjusts the README to follow the [template's README](https://github.com/ansible-collections/collection_template/blob/master/README.md).

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
README.md

### CODE REVIEW

**Comment by felixfontein** [comment]
@Andersson007 you mean for the collection? That would be the issue linked in the README under Roadmap (#582). Or do you mean for Ansible (as in ACD) itself?

**Comment by gundalow** [comment]
I think having dates in README.md could be confusing as they will be stored & displayed in galaxy.ansible.com.
I like having these details in #582 which we can link to

**Comment by Andersson007** [comment]
@felixfontein ok (i don't mean ACD:)

**Comment by felixfontein** [comment]
@Andersson007 @gundalow thanks for reviewing!

**Pull request merged**
