### PR TITLE
Add sops vars plugin

### PR DESCRIPTION
**Pull request by mhumeSF**
##### SUMMARY
Migrating PR https://github.com/ansible/ansible/pull/59641/ to here.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
Vars plugin using sops encryption

### CODE REVIEW

**Comment by felixfontein** [comment]
This plugin is placed one level too deep (must be in `plugins/vars`, not in `plugins/vars/vars`).

**Comment by mhumeSF** [comment]
@felixfontein Can share the tests that the lookup plugin is using?

**Comment by felixfontein** [comment]
Yes, they can. You can use the common code from `setup_sops` to set up sops. Inventory tests are bit more complicated, you need the `runme.sh` schema. Also note that there were still some problems with the inventory plugin in ansible/ansible#59641; did you already adjusted the plugin?

**Comment by felixfontein** [comment]
Please update your `master` branch and rebase this PR accordingly. Do you want to do the changes and/or the tests yourself, or do you need help?

**Comment by mhumeSF** [comment]
I'll rebase, update and look at implementing testing. Thanks for all your help with this!

**Comment by felixfontein** [comment]
This needs to be re-created here: https://github.com/ansible-collections/community.sops

**Pull request closed without merging**
