### PR TITLE
mysql_info: Add parameter for __collect method

### PR DESCRIPTION
**Pull request by lyvivian0077**
##### SUMMARY

Add parameter for `__collect` method

By default the class `MySQL_Info` get all MySQL instance information,
add  parameter for `__collect` to  get only what wants to know(information)

##### ISSUE TYPE

Feature Pull Request

##### COMPONENT NAME

lib/ansible/modules/database/mysql/mysql_info.py

### CODE REVIEW

**Comment by Andersson007** [comment]
@lyvivian0077 let's wait a bit, maybe anybody else will want to review it.
(FYI we have some issues to fix / prs to rewrite in old place https://github.com/ansible/ansible/labels/mysql that haven't been moved to here yet. If you decide to implement one of them, please let me know previously:)

**Comment by Xyon** [comment]
Sensible optimisation to me, big fan of pulling only what's needed. shipit

**Comment by Andersson007** [comment]
oh, @lyvivian0077 we need a changelog fragment https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#changelogs. 
Please create one in ./changelogs and add the lines below
```
bugfixes:
- mysql_info - add parameter for __collect to get only what are wanted (https://github.com/ansible-collections/community.general/pull/136).
```

**Comment by lyvivian0077** [comment]
@Andersson007 
Add changelog, please check it.

**Comment by Andersson007** [comment]
@lyvivian0077 merged, thanks for the PR!
@bmalynovytch thanks for reviewing!

**Comment by Andersson007** [comment]
@Xyon thanks for reviewing!

**Pull request merged**
