### PR TITLE
postgresql_privs: fix module fails when passing roles containing hyphens

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.general/issues/1058

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`plugins/modules/database/postgresql/postgresql_privs.py`

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
bot_status

**Comment by kostiantyn-nemchenko** [comment]
shipit

**Comment by Andersson007** [comment]
@MannerMan thanks for reporting the bug!
@kostiantyn-nemchenko thanks for reviewing!

**Comment by Andersson007** [comment]
bot_status

**Pull request merged**
