### PR TITLE
DO NOT MERGE: snap test for issue 7265

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY

Created a test case using the exact same tasks described in #7265 , but had no success replicating the error locally in Ubuntu 22.04.

Running a PR to ensure broader coverage.

##### ISSUE TYPE

- Test Pull Request

##### COMPONENT NAME

snap

### CODE REVIEW

**Comment by russoz** [comment]
@felixfontein could you please review this PR as "request changes" to prevent it from being merged by mistake? If we actually find a bug that needs fixing, this will eventually get merged. Otherwise, it will be discarded.

**Review by felixfontein — CHANGES_REQUESTED** [review]
Don't merge yet ;-)

**Comment by felixfontein** [comment]
I also converted the PR to a draft, which actively the Merge button for all committers until the PR is converted back with "ready for review".

**Comment by russoz** [comment]
The test in this PR was never able to prove anything. Cancelling the PR.

**Pull request closed without merging**
