### PR TITLE
Fixes #4: Remove mistakenly-added kubectl connection plugin.

### LINKED ISSUE #4: Remove mistakenly-added kubectl connection plugin
The kubectl connection plugin should've pointed at the community.kubernetes collection, instead of this one.

So for this collection, we need to delete the kubectl.py plugin, as it shouldn't have been in here in the first place.

Related issues:

ansible/ansible#68121
ansible-collections/kubernetes#49

### PR DESCRIPTION
**Pull request by geerlingguy**
##### SUMMARY

Closes #4.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

The Great Collection Migration

##### ADDITIONAL INFORMATION

N/A

### CODE REVIEW

**Comment by gundalow** [comment]
Happy to merge as `community.general` hasn't been released (not published to Galaxy)

**Comment by AlanCoding** [comment]
@geerlingguy Does this now make

https://github.com/ansible-collections/community.general/blob/1a87822704e6a2bc272e7542becc3b714093fc72/plugins/connection/oc.py#L150

a bug?

**Comment by felixfontein** [comment]
Yes. The plugin never was in a proper release of community.general. It might have worked in the past if you used one of the bootstrap releases of community.general.

**Comment by AlanCoding** [comment]
Actually this isn't as bad as I thought since `community.kubernetes` is a dependency here:

https://github.com/ansible-collections/community.general/blob/9142c75c845b0bf189ed5af70a627e4cbadfd56e/galaxy.yml#L14

So we can just switch the import.

**Comment by felixfontein** [comment]
@AlanCoding if you need to import it, better add community.kubernetes to your own dependencies. It could happen that eventually community.general will drop this dependency (in case the kubevirt modules/plugins are moved somewhere else - these are the only reason for the dependency at the moment).

**Comment by AlanCoding** [comment]
My issue here is with the `community.general` content. I put up what I described at #577

**Comment by felixfontein** [comment]
Ah, sorry, I didn't notice that the line you quoted was from this repo.

**Pull request merged**
