### PR TITLE
CI: Add ArchLinux, Debian Bullseye, CentOS Stream 8, and Alpine 3

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Similar to https://github.com/ansible-collections/community.crypto/pull/404 and https://github.com/ansible-collections/community.docker/pull/301.

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by felixfontein** [comment]
Wow, finally passing! :)

**Comment by felixfontein** [comment]
Ok, looks like I broke some other platforms with 652ed43d851b41f298257be8cc64f45207aacf47...

**Comment by felixfontein** [comment]
@gundalow this adds 9 (three groups with three OS containers) new CI jobs. Is this ok?

**Comment by felixfontein** [comment]
Things that I had to disable because they were not working for some reason:

- [ ] alternatives: ArchLinux support?
- [ ] cloud_init_data: ArchLinux support?
- [ ] filesystem: vfat fails on Debian Bullseye, vfat and btrfs fail on ArchLinux
- [ ] homectl: fails on ArchLinux
- [ ] odbc: correct driver needs to be chosen/installed on ArchLinux (postgres setup works)
- [ ] shutdown: doesn't work on systemd systems without systemd-sysv installed! (this was already the case for Ubuntu 18.04 and 20.04, now it's also the case for Debian Bullseye and ArchLinux)

**Comment by felixfontein** [comment]
bot_skip

**Comment by felixfontein** [comment]
Ok, I've added Alpine to the matrix as well. This has 3+2 new CI nodes (3 groups for devel, 2 groups for 2.11).

More things that are disabled:

- [ ] alternatives: Alpine support?
- [ ] cloud_init_ata_facts: Alpine support?
- [ ] cronvar: support for Alpine < 3.15 (i.e. the `alpine3` images coming with ansible-core 2.11)
- [ ] filesize: sparse not working with Alpine?
- [ ] filesystem: something seems to be wrong with Alpine
- [ ] gem: Alpine support?
- [ ] nomad: Alpine support?
- [ ] npm: Alpine support?
- [ ] pids: Alpine support?
- [ ] timezone: Alpine support?
- [ ] yarn: Alpine support?

**Comment by felixfontein** [comment]
(The sanity failure is due to a problem with ansible-core 2.11's ansible-test, that will be fixed next week. It's unrelated to this PR.)

**Review by gundalow — APPROVED** [review]
Thanks for this. I've been through all the changes and they seem sensible.

**Comment by felixfontein** [comment]
@gundalow thanks for reviewing this!

**Comment by felixfontein** [comment]
I'll create issues for the non-working things resp. potential issues the tests have shown during the next days.

**Pull request merged**
