### PR TITLE
proxmox_kvm: add integration tests

### PR DESCRIPTION
**Pull request by Aversiste**
##### SUMMARY

Minimal integration tests for the module `proxmox_kvm`: create, start, stop then destroy.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

proxmox_kvm

##### ADDITIONAL INFORMATION

~~Need PR #1847 and~~ will unlock PR #1422.

### CODE REVIEW

**Comment by Aversiste** [comment]
Updated.

**Comment by felixfontein** [comment]
@Aversiste do these tests apply also for the version in the stable-1 branch? I would guess so, but it would be great if you could confirm that :)

**Comment by Aversiste** [comment]
I just ran the tests against stable-1 and confirm they work.

**Comment by felixfontein** [comment]
@Aversiste thanks a lot!

**Pull request merged**
