### PR TITLE
module_helper - fixed decorator cause_changes

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
The decorator `cause_changes` never really worked before. This PR fixes that and add unit tests for it.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/module_utils/module_helper.py
tests/unit/plugins/module_utils/test_module_helper.py

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@russoz thanks for fixing this!

**Comment by felixfontein** [comment]
@russoz the automatic backport to stable-1 failed. Can you check whether it is needed, and if it is, create it manually?

**Comment by russoz** [comment]
@felixfontein on it - for this change it should be quite straightforward, but keep in mind that stable-1 is lagging behind main for quite a number of tickets now (regardless of the ticket type).

**Comment by russoz** [comment]
@felixfontein  #2209

**Comment by felixfontein** [comment]
> @felixfontein on it - for this change it should be quite straightforward, but keep in mind that stable-1 is lagging behind main for quite a number of tickets now (regardless of the ticket type).

We are only backporting bugfixes to stable-1, so it's definitely lagging. The main question for backporting bugfixes is always cost vs. effort - if the bot can backport them, that's very cheap, but in some cases the bot can't. Then it depends on how important the fix is. I think in this case it is good to have it backported, since the module helper could also be used by modules from other collections. (Probably not so far, but who knows... :) )

**Pull request merged**
