### PR TITLE
Use semantic markup (modules o-p)

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
For information on semantic markup, see https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#semantic-markup-within-module-documentation.

Ref: #6627

(Note: I'm only considering modules containing `I(` for now.)

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
modules starting with o-p

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @overhacked @parfeon @pubnub @rohitChaware @rosowiecki @rsmontero @russoz @saranyasridharan @scathatheworm @srvg @suprememoocow @sysadmind @t0mk @tchernomax @teebes @thaumos @tleguern @troy2914 @tuxillo @willthames @willybarro @xen0l @xorel @zanssa

**Comment by felixfontein** [comment]
I'll merge this by tomorrow evening if nobody objects.

**Review by UnderGreen — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@UnderGreen thanks!

**Pull request merged**
