### PR TITLE
Adding myself to commit-rights.md / removing supershipit in BOTMETA

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
Some folks believe I can do it. :P

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
LGTM!

**Comment by Andersson007** [comment]
cc @felixfontein @aminvakil

**Comment by felixfontein** [comment]
@russoz thanks a lot for signing up for this! :)

**Comment by Andersson007** [comment]
@russoz just changed "triage" -> "write", thanks for the great contribution!!!

**Comment by russoz** [comment]
Thanks folks for being an amazing crew to work with!

**Pull request merged**
