### PR TITLE
[stable-3] Revert reverted changes for 3.1.0

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This PR reverts all feature commits that were reverted for 3.0.x releases before 3.1.0.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
various

### CODE REVIEW

**Comment by russoz** [comment]
This is looking familiar :-) and good to me :-)

**Review by russoz — APPROVED** [review]

**Comment by aminvakil** [comment]
Does this https://github.com/ansible-collections/community.general/commit/007333dbfe05961aeb0334112b3e88279b85dc99 count as bugfix technically? Or 3.0.1 can include bugfixes and doc additions which don't touch code?

**Comment by felixfontein** [comment]
@aminvakil ansible traditionally accepts doc fixes in all releases (well, almost: between RCs and final releases this is not always true).

**Review by aminvakil — APPROVED** [review]
@felixfontein Thanks for clarification!

LGTM

**Comment by felixfontein** [comment]
@russoz @aminvakil thanks for reviewing!

**Pull request merged**
