### PR TITLE
BOTMETA.yml: terraform - add a new maintainer

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/community.general/pull/2246#issuecomment-822713047

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
BOTMETA.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
@rainerleber could you please approve it?

**Comment by felixfontein** [comment]
@rainerleber ping

**Review by rainerleber — APPROVED** [review]

**Comment by rainerleber** [comment]
Sry for the delay

**Comment by felixfontein** [comment]
@rainerleber thanks! :)

**Pull request merged**
