### PR TITLE
BOTMETA.yml: add new maintainer to gitlab team

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
BOTMETA.yml: add new maintainer to gitlab team

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
.github/BOTMETA.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
Hi @suukit ! Thank you for your great contribution to GitLab related modules.
Would you like to become a team member in BOTMETA.yml?
It means that you'll get indirect commit to the related stuff via Andible Bot.
Your `shiptit`, `LGTM`, `+1` will be counted by the bot for automerge (2 votes from the team members are required).
The bot will also notify you via email when GitLab-related issues / PRs are created, so you don't miss the opportunity to say your opinion on them:)
What do you think?
If it sounds interesting, please approve this PR.
If you're not interested, please say it and we close the issue.

Thanks once more for the regular and great contribution!

**Comment by Andersson007** [comment]
cc @suukit ^

**Comment by felixfontein** [comment]
Closing due to apparent lack of interest.

**Comment by felixfontein** [comment]
Hi @suukit, sure, that's possible! Thanks for your interest!
@Andersson007 can you please rebase this PR?

**Review by suukit — APPROVED** [review]

**Comment by felixfontein** [comment]
@Andersson007 can you please rebase this? Thanks.

**Comment by Andersson007** [comment]
@felixfontein done, thanks!

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@suukit thanks a lot for stepping up!
@Andersson007 thanks for suggesting and helping!

**Pull request merged**
