### PR TITLE
Pass absolute paths to atomic_move()

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Ref: https://github.com/ansible/ansible/issues/83950
Ref: https://github.com/ansible/ansible/pull/83951/files

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
various

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @bcoca

**Comment by bcoca** [comment]
It might be better to add something like unfrackpath/abspath to the path type. which already has `expandvars+ expanduser`

**Comment by felixfontein** [comment]
True, but that won't get backported :)

**Comment by bcoca** [comment]
depends, need to convince people it is a 'bugfix'

**Comment by felixfontein** [comment]
If nobody objects, I'll merge this next week.

**Comment by felixfontein** [comment]
@bcoca thanks for taking a look!

**Pull request merged**
