### PR TITLE
YAML callback: do not remove non-ASCII Unicode from multi-line string output

### LINKED ISSUE #1519: Issue with mutlliline yaml variables
##### SUMMARY
It seems to me that the following issues are still presnet in Ansible 2.10 (tested on 2.10.4)
- https://github.com/ansible/ansible/issues/62841
- https://github.com/ansible/ansible/issues/65843

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
YAML callback

##### ANSIBLE VERSION
```
ansible 2.10.4
  config file = $HOME/.ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible
  python version = 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) [Clang 6.0 (clang-600.0.57)]
```

##### CONFIGURATION
```
DEFAULT_STDOUT_CALLBACK($HOME/.ansible.cfg) = yaml
DEFAULT_TIMEOUT($HOME/.ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE($HOME/.ansible.cfg) = /some/path/to/My-Keystore
```

##### OS / ENVIRONMENT
MacOS

##### STEPS TO REPRODUCE

Sample to reproduce :

`inventories/dev/group_vars/all.yml`:
```yaml
accent_issue:
  ko: 'Cette chaîne avec un saut de ligne ne contient pas d''accents (éèê)

  Quel dommage'
  ko_2: "Cette chaîne avec un saut de ligne ne contient pas d'accents (éèê)\nQuel dommage"
  ko_3: |-
    Cette chaîne avec un saut de ligne ne contient pas d'accents (éèê)`
    Quel dommage
  ok: 'Cette chaîne contient bien des accents (éèê)'
```

Sample playbook:
```yaml
---
- hosts: 127.0.0.1
  tasks:
  - debug:
      var: accent_issue
```

##### EXPECTED RESULTS
From given steps, I expect accents to be present in each variable.

##### ACTUAL RESULTS
Output - we can see that for each `ko*`param, accents are removed

```
ansible-playbook -i environments/dev/ monitor-debug.yml
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [127.0.0.1] ********************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [debug] ************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] =>
  accent_issue:
    ko: |-
      Cette chane avec un saut de ligne ne contient pas d'accents ()
      Quel dommage
    ko_2: |-
      Cette chane avec un saut de ligne ne contient pas d'accents ()
      Quel dommage
    ko_3: |-
      Cette chane avec un saut de ligne ne contient pas d'accents ()`
      Quel dommage
    ok: Cette chaîne contient bien des accents (éèê)

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #1519.

Also adds tests for YAML callback, and generalizes DIY callback tests to generic callback tests which are used by the DIY and YAML callbacks.

##### ISSUE TYPE
- Bugfix Pull Request
- Test Pull Request

##### COMPONENT NAME
YAML callback

### CODE REVIEW

**Comment by felixfontein** [comment]
CI failures will be fixed by ansible/ansible#73044.

**Review by Andersson007 — APPROVED** [review]
Looks like a great work!

**Comment by felixfontein** [comment]
@Andersson007 thanks! It's mainly a generalization of @theque5t's work for the integration tests for the `diy` callback, so he deserves a large chunk of the credits as well :)

**Comment by felixfontein** [comment]
@Andersson007 thanks for reviewing!

**Comment by Andersson007** [comment]
@felixfontein ah, thanks for clarifying! @theque5t thanks for your work on the tests!:)

**Comment by theque5t** [comment]
> @felixfontein ah, thanks for clarifying! @theque5t thanks for your work on the tests!:)

My pleasure! Thank you both for the kind remarks @felixfontein @Andersson007

**Comment by theque5t** [comment]
One more thing, @felixfontein @Andersson007 if you like those tests, you may find this project interesting: https://github.com/theque5t/ansible-playbook-execute

**Comment by Andersson007** [comment]
@theque5t thanks! will see

**Comment by felixfontein** [comment]
@theque5t looks interesting! BTW, do you know about execution environments? I don't really (I only heard about them being mentioned at the last Ansible Fest), but they might be related to what you're doing. Links I found when quickly searching for them: https://ansible-runner.readthedocs.io/en/latest/execution_environments.html https://ansible-builder.readthedocs.io/en/latest/definition.html

**Comment by theque5t** [comment]
> @theque5t looks interesting! BTW, do you know about execution environments? I don't really (I only heard about them being mentioned at the last Ansible Fest), but they might be related to what you're doing. Links I found when quickly searching for them: https://ansible-runner.readthedocs.io/en/latest/execution_environments.html https://ansible-builder.readthedocs.io/en/latest/definition.html

@felixfontein I heard about them in this last Ansible Fest as well, and I agree, they seem closely related to my efforts with `execution_manager`. Collections are also very closely related to my efforts with `dependency_manager`. Happy to chat more with you outside of this PR if you send me your contact info. My LinkedIn is https://www.linkedin.com/in/trevor-highfill if you want to connect with me on there.

**Comment by felixfontein** [comment]
@theque5t connection request send ;) Though you can also grad my email address from my commits. I haven't spend much time with neither execution environments nor your framework yet though, and probably won't have much chance to look at them anytime soon. But eventually (maybe mid next year, when Ansible 4.0.0 is mostly done) I really want to look at all that...

**Pull request merged**
