### PR TITLE
New Infoblox lookup plugin: nios_next_vlanid

### PR DESCRIPTION
**Pull request by traittinen**
##### SUMMARY

This new lookup plugin gets next avalable VLAN ID for given VLAN view and range.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

nios_next_vlanid.py

##### ADDITIONAL INFORMATION

```paste below
[tomi@netdev2 infoblox]$ ansible-playbook -i lab-ipam.ini vlan_lookup.yml

PLAY [Register VLAN] ***************************************************************************************************************************************************************************

TASK [Lookup Debug] ****************************************************************************************************************************************************************************
ok: [ipam.lab.xoxo.com] => {
    "msg": "106"
}

PLAY RECAP *************************************************************************************************************************************************************************************
ipam.lab.xoxo.com         : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### CODE REVIEW

**Comment by traittinen** [comment]
I no longer have ability to work on this. If someone wants to continue from here that would be appreciated.

**Comment by Vaishnavi-infoblox** [comment]
Hi,

Could you please raise this PR in https://github.com/infobloxopen/infoblox-ansible.

Thank you,
Vaishnavi T R(Infoblox)

**Comment by Andersson007** [comment]
@traittinen could you create a new PR in the other repo as suggested?

**Comment by gundalow** [comment]
@traittinen As mentioned above, could you please create this as a PR in https://github.com/infobloxopen/infoblox-ansible

**Pull request closed without merging**
