### PR TITLE
mysql_db: add config_overrides_defaults parameter

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
fixes: https://github.com/ansible/ansible/issues/26919

mysql_db: add config_overrides_defaults parameter

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
mysql_db

### CODE REVIEW

**Comment by felixfontein** [comment]
Needs a changelog fragment. :)

**Comment by Andersson007** [comment]
@felixfontein yep, i has:) it was `WIP`, i added the fragment this morning:)

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
@bmalynovytch hey, would be great if you make time to look at this. no rush, thanks for your support.
I'm not sure it's worth solving this because there was no reaction in the issue and maybe it's not a big problem actually

**Comment by bmalynovytch** [comment]
@Andersson007 Hi mate !
What's the use case of this one. I don't get it 🤔 🙂

**Comment by Andersson007** [comment]
@bmalynovytch thanks for reviewing!

**Comment by Andersson007** [comment]
merged https://github.com/ansible-collections/community.general/pull/513 into master

**Comment by Jorge-Rodriguez** [comment]
@Andersson007 the shippable build job for this seems to be stuck

**Pull request merged**
