### PR TITLE
New module nios_vlan

### PR DESCRIPTION
**Pull request by traittinen**
##### SUMMARY

New module nios_vlan for handling Infoblox VLAN objects.

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

nios_vlan.py

##### ADDITIONAL INFORMATION

This new module allows to create/modify/delete Infoblox VLAN objects. Module returns object reference.

```paste below
[tomi@netdev2 infoblox]$ ansible-playbook -i lab-ipam.ini create_vlan.yml

PLAY [Register VLAN] ***************************************************************************************************************************************************************************

TASK [Configure a vlan] ************************************************************************************************************************************************************************
changed: [ipam.lab.xoxo.com]

TASK [Debug ref] *******************************************************************************************************************************************************************************
ok: [ipam.lab.xoxo.com] => {
    "msg": "vlan/ZG5zLnZsYW4kLmNvbS5pbmZvYmxveC5kbnMudmxhbl9yYW5nZSR0ZXN0LjEuNDA5NC5jb3JlMS4xMDAuMTk5LjEwNQ:test/core1/vlan105/105"
}

PLAY RECAP *************************************************************************************************************************************************************************************
ipam.lab.xoxo.com         : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

### CODE REVIEW

**Comment by felixfontein** [comment]
Quick comment: the module needs to be put into the correct subdirectory of `plugins/modules/`, and a symlink needs to be added where you have the module now, pointing to the real module file.

**Comment by felixfontein** [comment]
I think the message "this PR contains more than one new module." is wrong. @traittinen please note that the bot is currently in adjusted for collections, so things like this can unfortunately happen. It will get better soon :)

**Comment by felixfontein** [comment]
Please check the failed sanity tests. (I've restarted CI, you now have proper results.)

Also, all new modules should have tests (unit and/or integration).

**Comment by traittinen** [comment]
I no longer have ability to work on this. If someone wants to continue from here that would be appreciated.

Module should be working fine but tests are still missing.

**Comment by Vaishnavi-infoblox** [comment]
Hi,

Could you please raise this PR in https://github.com/infobloxopen/infoblox-ansible.

Thank you,
Vaishnavi T R(Infoblox)

**Comment by Andersson007** [comment]
@traittinen could you please just create a new one in the other repository as suggested in the comment above?

**Comment by Andersson007** [comment]
closed via Vaishnavi-infoblox's comment. @traittinen if you're interested in the module, please create a new pr in the mentioned repo

**Pull request closed without merging**
