### PR TITLE
Re-enable snap tests

### LINKED ISSUE #3925: Snap tests are disabled
### Summary

They were constantly failing (long timeouts) since the weekend.

Disabled in #3922.

### Issue Type

Bug Report

### Component Name

snap
snap_alias

### Ansible Version

all

### Community.general Version

stable-3
stable-4
main

### Configuration

_No response_

### OS / Environment

_No response_

### Steps to Reproduce

-

### Expected Results

-

### Actual Results

_No response_

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Let's see whether that works.

Fixes #3925.

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
snap tests

### CODE REVIEW

**Comment by felixfontein** [comment]
According to https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-e2d02fdf27 and https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-38fd34170a the updates have been pushed to stable some hours ago. It seems that some mirrors aren't yet synced, as every time I rerun the failing tests, some more pass. I will try again later, and if it succeeds, remove te `WIP` marker and restart **all** tests.

**Comment by felixfontein** [comment]
Maybe it is also just not working on RHEL 8.2 and 8.3? If it continues to fail, I'll add code which skips these tests on RHEL 8.2 and 8.3.

**Review by tadeboro — APPROVED** [review]

**Comment by felixfontein** [comment]
@tadeboro thanks for reviewing this!

**Comment by felixfontein** [comment]
Manual backport to stable-3 in #3982.

**Pull request merged**
