### PR TITLE
BOTMETA.yml: supershipit to quidame

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
BOTMETA.yml: supershipit to quidame

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
BOTMETA.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
@quidame
1) if you OK with this, please approve. If it gets overwhelming to get the notifications I mentioned, we can remove the grant.
2) `triage` has been granted.

cc @felixfontein

**Review by felixfontein — APPROVED** [review]

**Review by aminvakil — APPROVED** [review]

**Review by quidame — APPROVED** [review]

**Comment by felixfontein** [comment]
@quidame thanks a lot for joining the team! :)

**Comment by aminvakil** [comment]
@quidame Thank you for helping !

**Comment by russoz** [comment]
Welcome @quidame !!!

**Comment by quidame** [comment]
@Andersson007 @felixfontein @aminvakil @russoz thank you all for your welcome ! I'm happy to join the team :)

**Pull request merged**
