### PR TITLE
Update BOTMETA.yml

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Add terraform module maintainer.
DO NOT merge this until @m-yosefpor 's approval

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
BOTMETA.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
I figured out that there's no maintainers for `terraform` module
@m-yosefpor you improved the module and reviewed others PRs, if you'd like to be a maintainer, please put `shipit` here.
Maintainers get notifications from the bot about related events (issues/prs) and also their shipit-s are counted by the bot for automerge. If you disagree, please write about this, so i'll close the PR.

**Comment by m-yosefpor** [comment]
Great. Thanks @Andersson007 . I'm willingly taking the responsibility.

**Comment by m-yosefpor** [comment]
shipit

**Comment by felixfontein** [comment]
@m-yosefpor thanks a lot for becoming a maintainer for the terraform module! :)

**Comment by Andersson007** [comment]
@m-yosefpor thanks! It's becoming more and more popular

**Comment by aminvakil** [comment]
@m-yosefpor Congratulations!

**Comment by m-yosefpor** [comment]
@aminvakil Thanks Amin ;)

**Pull request merged**
