### PR TITLE
linode_v4 - fixed error message

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
Error message referred to Ansible's bugtracker URL in github. Changing to c.g.'s one.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/modules/cloud/linode/linode_v4.py

### CODE REVIEW

**Comment by aminvakil** [comment]
Thanks for fixing these!

Using `git grep ansible/ansible`, I've found some other broken references:
```
scripts/inventory/rudder.py:# https://github.com/ansible/ansible/blob/devel/contrib/inventory/ec2.py
scripts/vault/azure_vault.py:# https://github.com/ansible/ansible/blob/devel/contrib/inventory/azure_rm.py
```
Could you please check all others, too?

**Comment by russoz** [comment]
> Thanks for fixing these!
> 
> Using `git grep ansible/ansible`, I've found some other broken references:
> 
> ```
> scripts/inventory/rudder.py:# https://github.com/ansible/ansible/blob/devel/contrib/inventory/ec2.py
> scripts/vault/azure_vault.py:# https://github.com/ansible/ansible/blob/devel/contrib/inventory/azure_rm.py
> ```
> 
> Could you please check all others, too?

Those are more like historical references, I think they should stay.

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@russoz thanks for fixing this!
@aminvakil thanks for reviewing!

**Comment by aminvakil** [comment]
> > Thanks for fixing these!
> > Using `git grep ansible/ansible`, I've found some other broken references:
> > ```
> > scripts/inventory/rudder.py:# https://github.com/ansible/ansible/blob/devel/contrib/inventory/ec2.py
> > scripts/vault/azure_vault.py:# https://github.com/ansible/ansible/blob/devel/contrib/inventory/azure_rm.py
> > ```
> > 
> > 
> > Could you please check all others, too?
> 
> Those are more like historical references, I think they should stay.

@russoz Aha, I didn't checked them through, thanks for clarifying!

**Pull request merged**
