### PR TITLE
[stable-2] Typo fix in changelog

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
changelogs/changelog.yaml

### CODE REVIEW

**Review by aminvakil — APPROVED** [review]
Thanks for fixing this!
I always make this typo :)

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
BTW: one of these typos also exists in the stable-1 changelog.

**Comment by felixfontein** [comment]
@Akasurde thanks for fixing this!
@aminvakil thanks for reviewing!

Anyone wants to create a PR for stable-1 to fix the typo there?

**Comment by Akasurde** [comment]
I can.

**Pull request merged**
