### PR TITLE
awall: revamp the module

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY

Revamp of the module using `ModuleHelper` and `CmdRunner`.

##### ISSUE TYPE

- Refactoring Pull Request

##### COMPONENT NAME

awall

### CODE REVIEW

**Comment by felixfontein** [comment]
@russoz did you test whether your rewrite still works?

**Comment by russoz** [comment]
Not tested

**Comment by felixfontein** [comment]
Since we now do have Alpine VMs in CI, it should be possible to add some basic integration tests that run in CI. With such tests present I'm at lot less hesitant to merge this :)

**Comment by russoz** [comment]
True. As I have never worked with awall before, *I am* a bit hesitant to add the tests ;-)

Will either get there some day, or maybe someone else will.

**Comment by felixfontein** [comment]
I also never used it. Just make sure you enable SSH access before enabling the firewall, otherwise ansible won't be able to connect to the VM anymore :)

**Comment by felixfontein** [comment]
(Or enable it with "allow everything".)

**Comment by russoz** [comment]
Closing this one for the time being, but will keep the branch active on my side. Eventually I will bake some tests into it.

**Pull request closed without merging**
