### PR TITLE
Try to fix unit some relative unit test imports

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Hopefull make unit tests ~~run though.~~ fail less badly than before ([like here](https://app.shippable.com/github/ansible-collections/community.general/runs/81/7/console)).

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
tests/unit/module_utils/xenserver/
tests/unit/modules/cloud/xenserver/conftest.py

### CODE REVIEW

**Comment by felixfontein** [comment]
Hopefully fixes problem in https://app.shippable.com/github/ansible-collections/community.general/runs/81/7/console

**Comment by felixfontein** [comment]
Looks like it fixes that problem. Doesn't solve the problem that collection dependencies have not been installed though.

**Comment by gundalow** [comment]
Should I merge this as is?

**Comment by felixfontein** [comment]
@gundalow I think so. It seems to improve the situation, and there's not much more that can be done right now I think.

**Comment by felixfontein** [comment]
@gundalow thanks for merging!

**Comment by gundalow** [comment]
Thanks for the investigation and the fixes!

**Pull request merged**
