### PR TITLE
remove codeql analysis since it havent worked for 7 months

### PR DESCRIPTION
**Pull request by konstruktoid**
Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

##### SUMMARY

remove codeql analysis since it havent worked for 7 months, it doesn't seem to be missed.
what should it be replaced with, if anything?

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by felixfontein** [comment]
Let's try #5546 first.

**Comment by konstruktoid** [comment]
Sure, but what are we actually building?
https://github.com/ansible-collections/community.general/actions/runs/3464564298

**Comment by felixfontein** [comment]
I don't think we ever built anything.

**Comment by konstruktoid** [comment]
messed up rebase, will open again if https://github.com/ansible-collections/community.general/actions/workflows/codeql-analysis.yml fails.

**Comment by felixfontein** [comment]
@konstruktoid thanks for the PR!

**Pull request closed without merging**
