### PR TITLE
[WIP] pipx: alpine tests

### LINKED ISSUE #6878: pipx/pipx_info tests need to be fixed and re-enabled
### Summary

See #6874.

### Issue Type

Bug Report

### Component Name

pipx
pipx_info

### Ansible Version

latest

### Community.general Version

latest

### Configuration

_No response_

### OS / Environment

_No response_

### Steps to Reproduce

-

### Expected Results

-

### Actual Results

_No response_

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY

Trying to fix the alpine tests

Fixes #6878 

##### ISSUE TYPE

- Test Pull Request

##### COMPONENT NAME

pipx

### CODE REVIEW

**Comment by felixfontein** [comment]
It's not only related to Alpine, as it also fails on FreeBSD (https://dev.azure.com/ansible/community.general/_build/results?buildId=82747&view=results, https://dev.azure.com/ansible/community.general/_build/results?buildId=82780&view=results).

It imght be better to avoid installing something that requires Rust though, instead of making CI able to compile Rust packages. That a) is faster and b) will require less maintenance in the future.

**Comment by russoz** [comment]
@felixfontein one thing is not making sense to me: shouldn't this PR be failing the integration tests on FreeBSD then?

**Comment by russoz** [comment]
Another point is: given that `cryptography` is relying on rust, and that package is a direct or indirect dependency to pretty much a lot of things, I think it is not very productive to try and "run away" from building it. I think we should embrace it fully and add `rust` to all the CI containers/VMs.

**Comment by felixfontein** [comment]
> @felixfontein one thing is not making sense to me: shouldn't this PR be failing the integration tests on FreeBSD then?

That's a *very* good question, I've been wondering about that as well...

**Comment by felixfontein** [comment]
> Another point is: given that `cryptography` is relying on rust, and that package is a direct or indirect dependency to pretty much a lot of things, I think it is not very productive to try and "run away" from building it. I think we should embrace it fully and add `rust` to all the CI containers/VMs.

There are some differences: a) cryptography comes with wheels. So no building of rust libraries is needed on most platforms; b) some version of cryptography is already installed in the images and VMs, so there's no need to actually install it.

And my main point remains: CI cycles shouldn't be wasted on things that aren't needed, like building libraries that are built just so that some dependency of a program can be installed while that program is not actually needed.

**Comment by felixfontein** [comment]
> That's a _very_ good question, I've been wondering about that as well...

The most likely reason is that it depends on something that ran before these tests in the same CI run. The failures happened during nightly, when everything is run.

**Comment by felixfontein** [comment]
Ok, I guess I know the answer: the tests don't fail because **they don't run in CI**. You didn't remove the `disabled` in `aliases` :)

See also #6900.

**Comment by felixfontein** [comment]
#6937 fixes the sanity test error.

**Comment by russoz** [comment]
It seems there is a rust dependency every corner. Giving up for now.

**Pull request closed without merging**
