### PR TITLE
postgresql_query: add search_path parameter

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
fixes: https://github.com/ansible-collections/community.general/issues/625

postgresql_query: add search_path parameter

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
postgresql_query

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
CC @placaze

**Comment by tcraxs** [comment]
Hey @Andersson007 I just checked your PR, but only the code, did not run it. But I have a question regarding the search_path. As I know, this setting could be set for a connection. It looks to me, that this is the case in your PR. So I guess, as long as the connection is open, the newly set search_path will be used. Did you test something like this:
```
- name: postgresql_query - insert data
  become_user: '{{ pg_user }}'
  become: true
  postgresql_query:
    login_user: '{{ pg_user }}'
    login_db: postgres
    query: 'INSERT INTO {{ item }} (id) VALUES (1)'
    search_path:
    - query_test1
    - query_test2
  loop:
  - test1
  - test2

- name: postgresql_query - insert data
  become_user: '{{ pg_user }}'
  become: true
  postgresql_query:
    login_user: '{{ pg_user }}'
    login_db: postgres
    query: 'INSERT INTO {{ item }} (id) VALUES (1)'
  loop:
  - test2
  - test1
```
With that, I will prove, that the search_path will be "reset" for the next module execution. My feeling is, that this will be okay, because the module will run again, and therefore it will create a new connection to postgresql, but I'm not sure, and maybe this could be added as a test to the PR?

**Comment by Andersson007** [comment]
@tcraxs hey, thanks for pointing this out!
I added that case but probably forgot to push. Will se.

**Comment by Andersson007** [comment]
@tcraxs done, thanks!
ready_for_review

**Comment by Andersson007** [comment]
I thinks CI tests cover all cases and they passed, so
merged https://github.com/ansible-collections/community.general/pull/653 into main

**Comment by Andersson007** [comment]
@tcraxs thanks for reviewing!

**Comment by Andersson007** [comment]
@placaze thanks for reporting the issue!

**Pull request merged**
