### PR TITLE
BOTMETA.yml: add maintainers of proxmox_snap module

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/community.general/pull/1135

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
`BOTMETA.yml`

### CODE REVIEW

**Comment by Andersson007** [comment]
@Thulium-Drake i'm going to add your module and you as its maintainer to `BOTMETA.yml`, a special file for our bot.
The bot will notify you about related issues/PRs.
Also your `shipit`/`LGTM`/`+1` will be counted for automerge bugfixes / new features.

Would you like to be added to proxmox_team and get the permissions above for all the `proxmox_*` modules?

**Comment by Thulium-Drake** [comment]
Hi @Andersson007,

Sure! No problem, I know my way around them now ;-)

**Comment by Andersson007** [comment]
@Thulium-Drake cool, thanks for becoming a team member:) Once the tests passed, we'll merge the PR

**Review by gundalow — APPROVED** [review]
@Thulium-Drake welcome to the team!

**Review by felixfontein — APPROVED** [review]

**Pull request merged**
