### PR TITLE
Bugfix/keycloak userfed idempotency

### LINKED ISSUE #4664: community.general.keycloak_user_federation is not idempotent
### Summary

When running the 'community.general.keycloak_user_federation' module it keeps adding more entries of ldap user federations every time it is run instead of recognizing it is already there.

At the same time if a mapper is defined and happens to be the same as one that already exists it just gets added as a second mapper instead of updating the one that is auto created.

If mappers are defined when creating a user federation it would be good to delete the mappers that are auto created as there is no good way to clean those up using this module.

### Issue Type

Bug Report

### Component Name

community.general.keycloak_user_federation

### Ansible Version

```console (paste below)
ansible [core 2.12.5]
  config file = /home/user/repo/ansible/control_example-com/ansible.cfg
  configured module search path = ['/home/user/repo/ansible/control_example-org/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/repo/ansible/control_example-com/plugins/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

### Community.general Version

```console (paste below)
# /usr/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.8.0  
```

### Configuration

```console (paste below)
ANSIBLE_NOCOWS(/home/repo/ansible/control_example-com/ansible.cfg) = True
CACHE_PLUGIN(/home/repo/ansible/control_example-com/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/repo/ansible/control_example-com/ansible.cfg) = ~/.ansible/dev_cache
CACHE_PLUGIN_TIMEOUT(/home/repo/ansible/control_example-com/ansible.cfg) = 6000
COLLECTIONS_PATHS(/home/repo/ansible/control_example-com/ansible.cfg) = ['/home/repo/ansible/control_example-com/plugins/collections']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/repo/ansible/control_example-com/ansible.cfg) = ['/home/user/.local/lib/python3.7/site-packages/ara/plugins/callback']
DEFAULT_FILTER_PLUGIN_PATH(/home/repo/ansible/control_example-com/ansible.cfg) = ['/home/repo/ansible/control_example-com/plugins/filter']
DEFAULT_GATHERING(/home/repo/ansible/control_example-com/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/repo/ansible/control_example-com/ansible.cfg) = ['/home/repo/ansible/control_example-com/inventories/development']
DEFAULT_LOOKUP_PLUGIN_PATH(/home/repo/ansible/control_example-com/ansible.cfg) = ['/home/repo/ansible/control_example-com/plugins/lookup']
DEFAULT_MANAGED_STR(/home/repo/ansible/control_example-com/ansible.cfg) = File is managed by Ansible. Do not edit.
DEFAULT_MODULE_PATH(/home/repo/ansible/control_example-com/ansible.cfg) = ['/home/repo/ansible/control_example-com/plugins/modules']
DEFAULT_PRIVATE_KEY_FILE(/home/repo/ansible/control_example-com/ansible.cfg) = /home/repo/ansible/control_example-com/.private/key.rsa
DEFAULT_PRIVATE_ROLE_VARS(/home/repo/ansible/control_example-com/ansible.cfg) = True
DEFAULT_REMOTE_USER(/home/repo/ansible/control_example-com/ansible.cfg) = ansibler
DEFAULT_ROLES_PATH(/home/repo/ansible/control_example-com/ansible.cfg) = ['/home/repo/ansible/control_example-com/.containers', '/home/repo/ansible/control_example-com/.containers_old', '/home/repo/ansible/control_example-com/roles', '/home/repo/ansible/control_example-com/.roles']
DEFAULT_STDOUT_CALLBACK(/home/repo/ansible/control_example-com/ansible.cfg) = yaml
DEFAULT_UNDEFINED_VAR_BEHAVIOR(/home/repo/ansible/control_example-com/ansible.cfg) = True
DEFAULT_VARS_PLUGIN_PATH(/home/repo/ansible/control_example-com/ansible.cfg) = ['/home/repo/ansible/control_example-com/plugins/vars']
DIFF_ALWAYS(/home/repo/ansible/control_example-com/ansible.cfg) = True
DIFF_CONTEXT(/home/repo/ansible/control_example-com/ansible.cfg) = 5
DISPLAY_ARGS_TO_STDOUT(/home/repo/ansible/control_example-com/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/home/repo/ansible/control_example-com/ansible.cfg) = True
HOST_KEY_CHECKING(/home/repo/ansible/control_example-com/ansible.cfg) = False
INVENTORY_IGNORE_PATTERNS(/home/repo/ansible/control_example-com/ansible.cfg) = ['ca', 'configs', 'files']
RETRY_FILES_SAVE_PATH(/home/repo/ansible/control_example-com/ansible.cfg) = /home/user/.ansible/.ansible-retry
```
the home paths are inconsistent due to redactions...

### OS / Environment

Archlinux

### Steps to Reproduce

```yaml (paste below)
  - name: setup ldap link to freeipa
    community.general.keycloak_user_federation:
      auth_keycloak_url: https://keycloak.example.com/auth
      auth_realm: master
      auth_username: "user"
      auth_password: "Password@3"
      realm: "example.com"
      name: freeipa3
      state: present
      provider_id: ldap
      provider_type: org.keycloak.storage.UserStorageProvider
      config:
        priority: 0
        enabled: true
        cachePolicy: NO_CACHE
        batchSizeForSync: 1000
        editMode: WRITABLE #READ_ONLY
        importEnabled: true
        syncRegistrations: false
        vendor: other
        usernameLDAPAttribute: uid
        rdnLDAPAttribute: uid
        uuidLDAPAttribute: ipaUniqueID
        userObjectClasses: inetOrgPerson, organizationalPerson
        connectionUrl: ldaps://freeipa-01.ipa.example.com:636
        usersDn: cn=users,cn=accounts,dc=ipa,dc=example,dc=org
        authType: simple
        bindDn: "cn=Directory Manager"
        bindCredential: "blahblahpassword"
        searchScope: 2
        validatePasswordPolicy: true
        trustEmail: false
        useTruststoreSpi: always
        connectionPooling: true
        pagination: true
        allowKerberosAuthentication: false
        debug: false
        useKerberosForPasswordAuthentication: false
      mappers:
        - name: "full name"
          providerId: "full-name-ldap-mapper"
          providerType: "org.keycloak.storage.ldap.mappers.LDAPStorageMapper"
          config:
            ldap.full.name.attribute: cn
            read.only: true
            write.only: false
        - name: first name
          providerId: "user-attribute-ldap-mapper"
          providerType: "org.keycloak.storage.ldap.mappers.LDAPStorageMapper"
          config:
            always.read.value.from.ldap: true
            is.mandatory.in.ldap: true
            ldap.attribute: cn
            read.only: false
            user.model.attribute: givenName

```
Run this twice then check the keycloak ui and you will find two `freeipa3` entries and ansible will say changed both times
You will also find that each entry contains two `first name` mappers when the first one should have been overwritten.
Ideally you would only find the `full name` and `first name` mappers but instead you will find multiple additional mappers for both `freeipa3` user federation entries.

### Expected Results

One `freeipa3` user federation entry should exist, the default `first name` mapper would be updated and mappers not listed in the above config would not be present.

### Actual Results

```console (paste below)
--- before
+++ after
@@ -0,0 +1,51 @@
+config:
+  allowKerberosAuthentication: 'false'
+  authType: simple
+  batchSizeForSync: '1000'
+  bindCredential: '**********'
+  bindDn: cn=Directory Manager
+  cachePolicy: NO_CACHE
+  changedSyncPeriod: '-1'
+  connectionPooling: 'true'
+  connectionUrl: ldaps://freeipa-01.ipa.example.come:636
+  debug: 'false'
+  editMode: WRITABLE
+  enabled: 'true'
+  fullSyncPeriod: '-1'
+  importEnabled: 'true'
+  pagination: 'true'
+  priority: '0'
+  rdnLDAPAttribute: uid
+  searchScope: '2'
+  startTls: 'false'
+  syncRegistrations: 'false'
+  trustEmail: 'false'
+  useKerberosForPasswordAuthentication: 'false'
+  usePasswordModifyExtendedOp: 'false'
+  useTruststoreSpi: always
+  userObjectClasses: inetOrgPerson, organizationalPerson
+  usernameLDAPAttribute: uid
+  usersDn: cn=users,cn=accounts,dc=ipa,dc=example,dc=com
+  uuidLDAPAttribute: ipaUniqueID
+  validatePasswordPolicy: 'true'
+  vendor: other
+mappers:
+- config:
+    ldap.full.name.attribute: cn
+    read.only: 'true'
+    write.only: 'false'
+  name: full name
+  providerId: full-name-ldap-mapper
+  providerType: org.keycloak.storage.ldap.mappers.LDAPStorageMapper
+- config:
+    always.read.value.from.ldap: 'true'
+    is.mandatory.in.ldap: 'true'
+    ldap.attribute: cn
+    read.only: 'false'
+    user.model.attribute: givenName
+  name: first name
+  providerId: user-attribute-ldap-mapper
+  providerType: org.keycloak.storage.ldap.mappers.LDAPStorageMapper
+name: freeipa3
+providerId: ldap
+providerType: org.keycloak.storage.UserStorageProvider

```
every time the module is run.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### LINKED ISSUE #5286: keycloak_user_federation duplicate mapper name
### Summary

Creating an ldap user federation can't be run twice. 

### Issue Type

Bug Report

### Component Name

keycloak_user_federation

### Ansible Version

```
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/handel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/handel/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```
# /usr/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 5.5.0 
```

### Configuration

```empty
```

### OS / Environment

archlinux

keycloak 18.0.2

### Steps to Reproduce

the playbook task
```
- name: ldap
  tags:
  - ldap
  community.general.keycloak_user_federation:
    name: "{{ keycloak.default_realm }}"
    auth_client_id: "{{ keycloak.auth_client_id }}"
    auth_keycloak_url: "{{ keycloak.auth_keycloak_url }}"
    auth_realm: "{{ keycloak.auth_realm }}"
    auth_username: "{{ keycloak.auth_username }}"
    auth_password: "{{ keycloak.auth_password }}"
    realm: "{{ keycloak.default_realm }}"
    provider_id: ldap
    provider_type: org.keycloak.storage.UserStorageProvider
    config:
      # connection
      vendor: ad
      connectionUrl: "{{ ldap.connectionUrl }}"
      authType: simple
      bindDn: "{{ ldap.bindDn }}"
      bindCredential: "{{ ldap.bindCredential }}"
      batchSizeForSync: 500
      pagination: true
      # search users
      userObjectClasses: person, organizationalPerson, user
      usersDn: "{{ ldap.user_base }}"
      searchScope: 2
      # attributes
      uuidLDAPAttribute: objectGUID
      usernameLDAPAttribute: uid
      rdnLDAPAttribute: cn
      # settings
      editMode: READ_ONLY
      validatePasswordPolicy: false
      trustEmail: "true"
      importEnabled: true
      syncRegistrations: false
      usePasswordModifyExtendedOp: "false"
    mappers:
      - name: "username"
        providerId: "user-attribute-ldap-mapper"
        providerType: "org.keycloak.storage.ldap.mappers.LDAPStorageMapper"
        config:
          always.read.value.from.ldap: "false"
          is.mandatory.in.ldap: "true"
          ldap.attribute: "uid"
          read.only: "true"
          user.model.attribute: "username"
```

on the first run it will create the federation, on the second run it will fail with

### Expected Results

ansible creates the federation on the first run, won't change anything on the second run

### Actual Results

second run fails

```
fatal: [host]: FAILED! => {"changed": false, "msg": "Found multiple mappers with name `username`. Cannot continue."}
```

with a bit of debug output in keycloak_user_federation.py, here is what was found

```
FAILED! => {
"changed": false, 
"msg": "Found multiple mappers with name `
[
{'id': 'b2267b7f-063b-4046-ae5d-94cc36c4218b', 'name': 'username', 
'providerId': 'user-attribute-ldap-mapper', 'providerType': 'org.keycloak.storage.ldap.mappers.LDAPStorageMapper', 
'parentId': '3a6b1799-3dd7-416f-ab99-c5cc256a9581', 
'config': {'ldap.attribute': ['uid'], 'is.mandatory.in.ldap': ['true'], 'always.read.value.from.ldap': ['false'], 'read.only': ['true'], 'user.model.attribute': ['username']}}, 

{'id': '6e952bf9-4df1-49ee-8e46-5386d94cb716', 'name': 'username', 
'providerId': 'user-attribute-ldap-mapper', 'providerType': 'org.keycloak.storage.ldap.mappers.LDAPStorageMapper', 
'parentId': '3a6b1799-3dd7-416f-ab99-c5cc256a9581', 
'config': {'ldap.attribute': ['uid'], 'is.mandatory.in.ldap': ['true'], 'read.only': ['true'], 'always.read.value.from.ldap': ['false'], 'user.model.attribute': ['username']}}]`. 

Cannot continue."}
```

i assume keycloak will create a default mapper (with a random id) during creation. Ansible has the mappings cached (before the creation of the federation, in other words no mapping) and adds a second mapping (also with a random id). 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by morco**
##### SUMMARY
Current version of `keycloak_user_federation` has some idempotency problems in some situations where an already existing user federation is not correctly recognized (detected) which then leads to the module falsely creating a new federation
again and again on each consequent playbook run.
One contributing factor seems to be the optional query param `parent=<realm-name>` which is momentarely always set when checking the server for existing user federations. This param seems to be buggy in upstream keycloak rest api working sometimes as expected while other times not (when parent realm is for example `master`).

Although this is fundamentally an upstream issue fpr keycloak rest api I would still argue that there is something which can and should be done inside this ansible module. As the parent realm (name) is already part of the url-path specifying them again as query param seems superfluous. So simply not setting them as query param seems to have no disadvantadges while insulating against these kind of api flukes.

Fixes #4664: at least for some cases
Fixes #5286: not totally sure here but this might be related to issue above

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
plugins/modules/keycloak_user_federation.py

##### ADDITIONAL INFORMATION
Tested with recent keycloak (api) version: `20.0.2`.

### CODE REVIEW

**Review by felixfontein — COMMENTED** [review]
Thanks for your contribution! Could you please add a [changelog fragment](https://docs.ansible.com/ansible/devel/community/collection_development_process.html#creating-a-changelog-fragment)? Thanks.

**Comment by felixfontein** [comment]
@morco please note that this cannot be merged without a changelog fragment. Thanks.

**Comment by morco** [comment]
Okay, added the changelog fragment now.

**Review by russoz — APPROVED** [review]
LGTM from the Ansible perspective, not very familiar with keycloak myself.

**Comment by felixfontein** [comment]
Same from my POV. If nobody objects in the next two weeks, I'll merge this.

**Comment by felixfontein** [comment]
@morco thanks for your contribution!
@russoz thanks for reviewing!

**Pull request merged**
