### PR TITLE
BOTMETA.yml: grant supershipit

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
BOTMETA.yml: grant supershipit

also "triage" was granted to Ajpantuso in c.g. and c.crypto.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
`.github/BOTMETA.yml`

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @Ajpantuso

**Comment by Andersson007** [comment]
@Ajpantuso could you please approve this

**Review by felixfontein — APPROVED** [review]

**Review by Ajpantuso — APPROVED** [review]
LGTM, thanks.

**Review by aminvakil — APPROVED** [review]

**Comment by felixfontein** [comment]
@Ajpantuso thanks a lot for helping!

**Pull request merged**
