### PR TITLE
Clean up google modules

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
During migration, the google cloud `*_info` modules were moved to `google.cloud`, while the deprecated `_*_facts` symlinks were moved to `community.general`. To make the symlinks work, the migration script also copied the `*_info` modules.

This PR:
1. Renames `*_info.py` to `*_facts.py` (and removes the previous symlink);
2. Adjusts the `*_facts.py` to be deprecated.

This way we only have deprecated modules that will go away eventually. (Next to the non-google google cloud modules.)

No changelog fragment since this fixes an aftermath of the migration.

CC @Akasurde @Andersson007 @gundalow 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
google cloud modules

### CODE REVIEW

**Comment by Andersson007** [comment]
why can't we just remove them?
For example, I'm seeing plugins/modules/gcp_bigquery_dataset_info.py in the google.cloud repo now

**Comment by felixfontein** [comment]
The problem is that the `_facts` module is supposed to be in *this* repo (https://github.com/ansible/ansible/blob/devel/lib/ansible/config/routing.yml#L763-L840). Right now the `_facts` module is simply a symlink to the `_info` module. So we need to keep the `_facts` module working until it is deprecated, and the simplest way to do this is replacing the symlink by a copy of the module.

**Comment by felixfontein** [comment]
Maybe we could use `meta/routing.yml` to simply redirect to the modules in `google.cloud`? I have no idea how that works together with deprecation though. Maybe we have to test that once the collection redirection PR is merged.

**Comment by Andersson007** [comment]
```
The problem is that the _facts module is supposed to be in this repo (https://github.com/ansible/ansible/blob/devel/lib/ansible/config/routing.yml#L763-L840).
```
Do you have any ideas why? Intentionally?
Logical (in my head) to have all such stuff in one place

**Comment by felixfontein** [comment]
I fully agree. We right now have a ton of deprecated stuff where most of the un-deprecated stuff sits somewhere else. I think the main reason is that during migration it was not clear how deprecation will work for officially Supported (with capital S) collections will look like, and it was decided at some point that deprecated stuff will go to the "dumping ground" (i.e. here).

**Comment by gundalow** [comment]
As suggested, we can just update ansible-base's routing.yml and deleting these files.

**Comment by felixfontein** [comment]
@gundalow can ansible-base's routing also do deprecation?

**Comment by felixfontein** [comment]
(Because the `_facts` modules don't exist in google.cloud.)

**Comment by gundalow** [comment]
The source and destination names in ansible-base's routing.yml don't have to match, ie
foo_facts can point to namespace.collection.foo_info

**Comment by felixfontein** [comment]
But then there would be no deprecation notice, right? Well, looks like there weren't before, so it would be ok for me.

**Comment by felixfontein** [comment]
The latest commit deletes the `_facts` modules completely. It requires ansible/ansible#69566 to get merged.

**Comment by felixfontein** [comment]
From this point on, the dependency on google.cloud is only needed in two places:
1. plugins/lookup/gcp_storage_file.py
2. tests/unit/plugins/module_utils/gcp/test_gcp_utils.py

Maybe we should try to vendor the needed parts at least for the plugin, to remove the runtime dependency on google.cloud. Opinions?

**Comment by felixfontein** [comment]
Merging now that ansible/ansible#69566 has been merged.

**Pull request merged**
