### PR TITLE
chroot: clarify disabling of connection chroot tests on macos

### LINKED ISSUE #1017: chroot connection: tests fail on macOS 10.15
##### SUMMARY
The tests for the `chroot` connection plugin fail on macOS (added to CI in #971). They are currently disabled.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/connection/chroot.py

##### ANSIBLE VERSION
2.10

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

Fixes #1017.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
tests/integration/targets/connection_chroot/aliases

### CODE REVIEW

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@Akasurde thanks a lot for debugging this!

**Comment by Akasurde** [comment]
@felixfontein np. 
For me it is - 

It’s not [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection). There is a no way it’s [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection). It was [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection).

**Comment by felixfontein** [comment]
Backport #1601 created manually from the branch the bot created.

**Comment by felixfontein** [comment]
#1602 instead.

**Pull request merged**
