### PR TITLE
Split up 'Ansible version' in issue templates into ansible-core version + community.general version

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Split up 'Ansible version' in issue templates into ansible-core version + community.general version. The ansible-core version which most users provide as "Ansible version" (which is also printed by the instructions provided there) isn't really helpful in most cases.

CC @gundalow @Andersson007 

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
issue templates

### CODE REVIEW

**Comment by felixfontein** [comment]
(Instructions adjusted from ansible-collections/.github#4)

**Review by Andersson007 — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@Andersson007 thanks for reviewing!

**Comment by felixfontein** [comment]
Looks like this wasn't a good idea, since the bot doesn't like this at all: https://github.com/ansible-collections/community.general/issues/3466#issuecomment-929628525

I'll rename that one back to "Ansible version" and try to get the bot fixed :)

**Comment by felixfontein** [comment]
Hotfix in d0f82e2c270535a5e51064584ccb6aa69ab88739.

**Pull request merged**
