### PR TITLE
 collection: Change default='no's and 'yes's to default=False and default=True

### PR DESCRIPTION
**Pull request by aminvakil**
##### SUMMARY
Fixes: https://github.com/ansible-collections/community.general/issues/550

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
collection

### CODE REVIEW

**Comment by aminvakil** [comment]
@resmo I've added a changelog, but as I haven't mentioned WIP in https://github.com/ansible-collections/community.general/pull/554#issuecomment-647291685 and haven't added a changelog for that PR I've added them to this PR changelog too, is it OK?

Is it OK if I add `554-collection.yml` to `changelogs/fragments` in this (556) PR?

**Comment by felixfontein** [comment]
I don't think a changelog fragment is needed, since this shouldn't have any visible effect on users.

**Comment by aminvakil** [comment]
> I don't think a changelog fragment is needed, since this shouldn't have any visible effect on users.

Shall I remove changelog then?

**Comment by felixfontein** [comment]
I would prefer if you remove it. @Andersson007 what do you think?

**Comment by Andersson007** [comment]
@felixfontein agreed, this is extra stuff in this case, imo

**Comment by Andersson007** [comment]
better to avoid. And it'll make noise among probably important strings

**Comment by Andersson007** [comment]
@aminvakil for the contribution! @felixfontein feel free to merge:)

**Comment by felixfontein** [comment]
/me hands over @Andersson007 a "thanks" that got missing ;)

**Comment by felixfontein** [comment]
@aminvakil thanks a lot for fixing all these!
@resmo @Andersson007 thanks a lot for reviewing!

**Comment by aminvakil** [comment]
@felixfontein @resmo @Andersson007 Thank "you" for reviewing!

**Pull request merged**
