### PR TITLE
Replace ansible.module_utils._text by ansible.module_utils.common.text.converters

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
While the private API `ansible.module_utils._text` was the default place to get `to_text`, `to_bytes` and `to_native` for a long time, at least since Ansible 2.9 there's a non-private alternative: `ansible.module_utils.common.text.converters`. So let's use it :)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
various plugins

### CODE REVIEW

**Review by tadeboro — COMMENTED** [review]
The changes look OK, but a quick grep through source code revealed some potential misses:

```
$ git grep "module_utils._text"
tests/unit/mock/loader.py:12:from ansible.module_utils._text import to_bytes, to_text
tests/unit/mock/procenv.py:16:from ansible.module_utils._text import to_bytes
tests/unit/mock/vault_helper.py:6:from ansible.module_utils._text import to_bytes
tests/unit/plugins/module_utils/conftest.py:15:from ansible.module_utils._text import to_bytes
tests/unit/plugins/modules/conftest.py:12:from ansible.module_utils._text import to_bytes
tests/unit/plugins/modules/monitoring/test_circonus_annotation.py:14:from ansible.module_utils._text import to_bytes
tests/unit/plugins/modules/net_tools/test_nmcli.py:11:from ansible.module_utils._text import to_text
tests/unit/plugins/modules/packaging/os/test_rhn_register.py:11:from ansible.module_utils._text import to_native
tests/unit/plugins/modules/remote_management/lenovoxcc/test_xcc_redfish_command.py:11:from ansible.module_utils._text import to_bytes
tests/unit/plugins/modules/system/test_ufw.py:9:from ansible.module_utils._text import to_bytes
tests/unit/plugins/modules/utils.py:11:from ansible.module_utils._text import to_bytes
tests/unit/plugins/modules/web_infrastructure/test_jenkins_build.py:9:from ansible.module_utils._text import to_bytes
```

Were those left out of this changeset on purpose?

**Comment by felixfontein** [comment]
@tadeboro no they weren't... I only grepped in `plugins/`... :)

**Review by tadeboro — APPROVED** [review]

**Comment by gundalow** [comment]
Thank you for this. Makes me wonder if we should have CI detect is people are using private methods

**Comment by tadeboro** [comment]
> Thank you for this. Makes me wonder if we should have CI detect is people are using private methods

Not all private methods are private in ansible/ansible, so I think this is not possible yet.

**Comment by felixfontein** [comment]
@tadeboro @gundalow thanks for reviewing!

**Comment by felixfontein** [comment]
Manual backport to stable-3 in #2882. There was a conflict in plugins/modules/cloud/scaleway/scaleway_security_group_rule.py due to removal of the vendored `ipadress` copy in the `main` branch (for community.general 4.0.0).

**Pull request merged**
