### PR TITLE
Add small unit test framework for testing fetch_url() based modules

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
I had integrated a small such framework in the unit tests for the `hetzner_firewall` and `hetzner_firewall_info` modules. This PR moves this framework to `tests/unit/utils/` so that it can be properly used by unit tests for other modules, module_utils or plugins.

It allows to test modules acting deterministically on `fetch_url()` results in a rather declarative way without the need to be able to access the service the module is supposed to use, or to have a mock-up of the service which can be used instead.

The `hetzner_firewall*` tests now use the framework from its new location, and the tests themselves stayed the same (only the way the test worked changed a little).

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
tests/unit/utils/fetch_url_module_framework.py

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @amigus

**Comment by felixfontein** [comment]
@gundalow what do you think? Should we move this to a new repository / collection? (Maybe `community.internal_test_tools`, so that nobody will get the idea that this is aimed at end-users.)

**Comment by gundalow** [comment]
@mattclay What are you thoughts on this?
Could this be useful to other collections?
If it's useful, should it go into ansible-base so we don't end up with even more dependencies?

**Comment by mattclay** [comment]
I'd put it into a dedicated test collection and not in ansible-base. Common unit testing support code that isn't closely tied to a specific Ansible version shouldn't be in ansible-base. Putting it in a dedicated test collection will allow more rapid changes and easier usage of whatever version is required.

**Comment by felixfontein** [comment]
@resmo @gundalow @mattclay what do you think of `community.internal_test_tools` as a name for that collection? Do you have better ideas?

**Comment by Andersson007** [comment]
@felixfontein just `community.test_tools` sounds good to me (IMO the word `internal` implies a possibility to have something like `community.external_test_tools` but they are usually provided as modules you can install by pip/etc or they are in external repositories.
Or, if really needed, we can create a subdirectory such as `community.test_tools/internal`, for examle. Then add the `external` subdirectory when needed.

**Comment by felixfontein** [comment]
I'm mainly afraid that if the collection name doesn't imply that this is internal, actual users might try to install this collection in the hope it helps *them* to test something.

**Comment by Andersson007** [comment]
anyway they might try to install it:)
it's worth putting a warning about internal puporses into the collection's README.
In general, your variant, IMO, is ok as well.

**Comment by gundalow** [comment]
https://github.com/ansible-collections/community.internal_test_tools exists and you have powers

**Comment by felixfontein** [comment]
Thanks everyone! I'll fill the new repo with content soon and adjust this PR accordingly.

**Comment by felixfontein** [comment]
I've created a PR to update the empty collection (community.internal_test_tools#1), and prepared a commit for this PR to use that collection (https://github.com/ansible-collections/community.general/commit/9b9a35030297a14013b89ebfd4c4cd27c2580819).

I've also copied tests/unit/plugins/modules/utils.py there. Should we remove it from this collections and use the version from there? (Nothing that has to be done right now...)

**Comment by felixfontein** [comment]
CI passes with the new collection! \o/

**Comment by felixfontein** [comment]
@resmo @gundalow @mattclay @Andersson007 thanks all for your feedback!

**Pull request merged**
