### PR TITLE
modules: fix names with hyphens (#656)

### LINKED ISSUE #656: postgresql_privs fails with schema name which contain '-' (dash) character
_From @vosmax on Jul 15, 2020 14:44_

##### SUMMARY

Task with module **postgresql_privs** fails with error when it's trying to apply default privileges to schema with name, which contain '-' (dash) character.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_privs

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = None
  configured module search path = ['/Users/ilon.mask/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible
  python version = 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) [Clang 6.0 (clang-600.0.57)]
```

##### CONFIGURATION

```paste below
empty
```

##### OS / ENVIRONMENT

MacOS Catalina 10.15.5

##### STEPS TO REPRODUCE

```yaml
vars:
  postgres_db:
     host: localhost
     user: test
     password: test 
     db: test 
     schema: "test-schema"
     role: "my-role"

- name: Set default privs 
  postgresql_privs:
     login_host: "{{ postgres_db.host }}"
     login_user: "{{ postgres_db.user }}"
     login_password: "{{ postgres_db.password }}"
     login_db: "{{ postgres_db.db  }}"
     schema: "{{ postgres_db.schema | quote }}"
     role: "{{ postgres_db.role }}"
     type: default_privs
     obj: TABLES
     privs: all
```

##### EXPECTED RESULTS

Default privileges are applied to the schema 

##### ACTUAL RESULTS

```paste below
"msg": "syntax error at or near \"-\"\nLINE 1: ALTER DEFAULT PRIVILEGES IN SCHEMA test-schema REVOKE A...\n
```

_Copied from original issue: ansible/ansible#70654_

### PR DESCRIPTION
**Pull request by vosmax**
##### SUMMARY

Fixes #656

##### ISSUE TYPE

- Bugfix Pull Request
##### COMPONENT NAME

postgresql-privs
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Andersson007** [comment]
could you please:
1. add tests for the changes to somewhere in tests/integration/targets/postgresql_privs/tasks/* (pass a schema name containing a hyphen for example)
2. add a changelog fragment https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

thanks for fixing this

**Comment by Andersson007** [comment]
failed because of https://app.shippable.com/github/ansible-collections/community.general/runs/2877/1/tests

**Comment by vosmax** [comment]
@Andersson007 Sure, I've thought it woud be fast-track fix, but... %)

**Comment by Andersson007** [comment]
you could restrict the pr by fixing schema only and then, after merging, fix db / user name related things in next prs.
it's just a suggestion

**Comment by vosmax** [comment]
@Andersson007 thank you! I think you may validate PR.

**Comment by Andersson007** [comment]
@vosmax thanks for the contribution!
merged https://github.com/ansible-collections/community.general/pull/659 into main

**Pull request merged**
