### PR TITLE
Terraform: ensure workspace is reset to current value

### PR DESCRIPTION
**Pull request by christophemorio**
##### SUMMARY
When terraform apply is failing (topology syntax valid, but unable to complete change), the module ends without resetting the workspace.

Instead of relying on `module.run_command()` exception, this PR resets workspace and renders equivalent output.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
terraform

##### ADDITIONAL INFORMATION
How to reproduce:
The following playbook + topology is expected to fail, since "test" bucket name is not available.
Run and check if topology workspace is back to "default" after the playbook failure.

```paste below
# playbook:
- hosts: localhost
  tasks:
  - community.general.terraform:
      workspace: "foo"
      state: "present"

# topology
resource "aws_s3_bucket" "main" {
  bucket = "test"
}
```

There is still an issue if the **plan** fails, IMHO this needs little refactoring to improve workspace switching.

### CODE REVIEW

**Comment by felixfontein** [comment]
This definitely needs a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to) :)

**Comment by felixfontein** [comment]
PR itself looks good, though I cannot judge this change at all. @m-yosefpor @rainerleber can you please take a look? Thanks!

**Review by rainerleber — APPROVED** [review]
I tested it and looks good to me. This PR will not break anything

**Comment by rainerleber** [comment]
@christophemorio thank you for contributing

**Comment by m-yosefpor** [comment]
LGTM too. Thanks.

**Comment by felixfontein** [comment]
@christophemorio thanks for fixing this!
@rainerleber @m-yosefpor thanks for reviewing!

**Pull request merged**
