### PR TITLE
mysql_user: add resource_limits parameter

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
mysql_user: add resource_limits parameter

Fixes: https://github.com/ansible-collections/community.general/issues/133

```
  resource_limits:
    description:
      - Limit the user for certain server resources. Provided since MySQL 5.6 / MariaDB 10.2.
      - "Available options are C(MAX_QUERIES_PER_HOUR: num), C(MAX_UPDATES_PER_HOUR: num),
        C(MAX_CONNECTIONS_PER_HOUR: num), C(MAX_USER_CONNECTIONS: num)."
      - Used when I(state=present), ignored otherwise.
    type: dict
```

##### EXAMPLE
```
- name: Limit bob's resources to 10 queries per hour and 5 connections per hour
  mysql_user:
    name: bob
    resource_limits:
      MAX_QUERIES_PER_HOUR: 10
      MAX_CONNECTIONS_PER_HOUR: 5
```

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
```plugins/modules/database/mysql/mysql_user.py```

### CODE REVIEW

**Comment by Andersson007** [comment]
fixes https://github.com/ansible/ansible/issues/26581

**Comment by Andersson007** [comment]
CC @Alexander198961 @bmalynovytch @bmildren @michaelcoburn @oneiroi @tolland @Xyon @Andersson007 @kurtdavi

**Comment by Andersson007** [comment]
CI fails unrelatedly.
ready_for_review

**Comment by Andersson007** [comment]
CI will be fixed after https://github.com/ansible-collections/community.general/pull/139

**Comment by drzraf** [comment]
As per https://github.com/ansible/ansible/issues/26581#issuecomment-413876699

Another aspect is that `IDENTIFIED VIA/WITH` (eg `unix_socket`, see https://dev.mysql.com/doc/refman/5.5/en/create-user.html , https://wiki.debian.org/MySql)
Do you think it's something that could be implemented as part of this PR?

**Comment by Andersson007** [comment]
@drzraf anyway IMO better not to mix a lot of things in one PR (easier to review, easier to revert if something wrong happens, etc.)
if it's not implemented yet, feel free to create an issue in this repo

**Comment by Andersson007** [comment]
@bmalynovytch thanks for reviewing!

**Comment by Andersson007** [comment]
@Akasurde thanks for merging:)

**Pull request merged**
