### PR TITLE
Revert #2411 which broke snap

### LINKED ISSUE #2906: snap module is broken in 3.3.0 release
### Summary

snap state parameter is converted to list:
```console
"cmd_args": ["/usr/bin/snap", "i", "n", "f", "o", "['core']"]
```
module fails on unknown command "i"

https://github.com/bonddim/ansible-collection-linux/actions/runs/985033045

### Issue Type

Bug Report

### Component Name

snap

### Ansible Version

```console (paste below)
$ ansible --version
ansible-base-2.10.11
ansible-2.9.23
ansible-core-2.12.0.dev
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu-20.04, Ubuntu-18.04, Debian 10, Fedora 34, Fedora 33, CentOs 8, CentOs 7

### Steps to Reproduce

```yaml (paste below)
- name: Install snap core
  community.general.snap:
    name: core
```

### Expected Results

package from snap is installed 

### Actual Results

```console (paste below)
 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.community.general.plugins.module_utils.mh.exceptions.ModuleHelperException
  fatal: [instance-snapd]: FAILED! => {"attempts": 3, "changed": false, "cmd_args": ["/usr/bin/snap", "i", "n", "f", "o", "['core']"], "force_lang": "C", "msg": "No snap matching 'core' available.", "output": {"cmd_args": ["/usr/bin/snap", "i", "n", "f", "o", "['core']"], "force_lang": "C", "rc": 64, "stderr": "error: unknown command \"i\", see 'snap help'.\n", "stdout": ""}, "rc": 64, "stderr": "error: unknown command \"i\", see 'snap help'.\n", "stderr_lines": ["error: unknown command \"i\", see 'snap help'."], "stdout": "", "stdout_lines": [], "vars": {"cmd_args": ["/usr/bin/snap", "i", "n", "f", "o", "['core']"], "force_lang": "C", "rc": 64, "stderr": "error: unknown command \"i\", see 'snap help'.\n", "stdout": ""}}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by aminvakil**
##### SUMMARY
This is just a test to see if integration tests pass if we revert #2411.
It's a last resort if there isn't any other PR fixing the issue.
Fixes #2906 .

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/modules/packaging/os/snap.py

### CODE REVIEW

**Comment by aminvakil** [comment]
I couldn't make `snap` work even manually on Fedora 34 :) I've also tried installing `squashfs-tools squashfuse`, also rebooted afterwards, didn't work.
But I've tested integration test against Ubuntu 18 and I hope it works against other Ubuntu versions as well.
Feel free to change it afterwards to make it work on CI too.

**Comment by aminvakil** [comment]
I've also ran integration test successfully against Ubuntu 20.04.

**Comment by russoz** [comment]
@aminvakil I believe #2912 is doing the job, I think this one can be closed.

**Comment by aminvakil** [comment]
@russoz, Sure. Superseded by #2912.

**Pull request closed without merging**
