### PR TITLE
Added proxmox module default  group

### PR DESCRIPTION
**Pull request by akira6592**
##### SUMMARY

Added proxmox module defoult  group.
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_module_defaults.html#module-defaults-groups

This eliminates the need to specify common parameters such as `api_user` for each task.

As below:

```yaml
- hosts: proxmox
  module_defaults:
    group/community.general.proxmox:
      api_host: proxmoxhost
      api_user: root@pam
      api_password: passowrd 

  tasks:
    - name: Gather VM Info
      community.general.proxmox_vm_info:
        type: qemu
        node: node01

    - name: List existing nodes
      community.general.proxmox_node_info:
      register: proxmox_nodes
```

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

Relateted forum topic https://forum.ansible.com/t/import-role-and-module-defaults/4277

### CODE REVIEW

**Review by felixfontein — CHANGES_REQUESTED** [review]
The proxmox modules will be moved to community.proxmox and removed from this collection. The action group will be added in the new collection, not here.

**Comment by akira6592** [comment]
@felixfontein Thank you for the information!
I close this.

**Comment by felbinger** [comment]
When will it be merged? Also looking for this feature...

**Comment by felixfontein** [comment]
The original plan was to move the proxmox modules to community.proxmox soon, but I'm not sure what's the plan with it at the moment. I've asked in https://forum.ansible.com/t/whats-up-with-community-proxmox/5189.

**Comment by felixfontein** [comment]
If I don't hear back anything in the next couple of days, I'll re-create this PR (and add the missing documentation) and merge it for community.general 9.0.0.

**Comment by felixfontein** [comment]
I've created a new PR: #8334

**Comment by akira6592** [comment]
@felixfontein Thank you for creating new PR with docs.

**Comment by felixfontein** [comment]
@akira6592 thanks for getting this started, and @felbinger thanks for triggering a restart :) I'm still hoping that community.proxmox will be(come) a thing, but I guess for now the proxmox modules will stay here...

**Comment by tonejito** [comment]
Just for completeness, this is related to issue #7844:

- #7844

**Pull request closed without merging**
