### PR TITLE
Remove -f from mkswap

### LINKED ISSUE #7946: Reconsider the "-f" (force flag) in general.filesystem's swap
### Summary

I am trying to format a partition as swap in an Alpine Linux managed system, the command fails because "-f" is not implemented in BusyBox's `mkswap` command.

I believe this feature change would be helpful for the community for the following reasons:
1- Increase compatibility among node systems
2- Prevent the user from making a "stupid" decision, from the manual:

```

-f
Force - go ahead even if the command is stupid. This allows the creation of a swap area larger than the file or partition it resides on.
Without this option mkswap will refuse to erase the first block on a device with a partition table or on whole disk (e.g. /dec/sda).
```

From my knowledge, different than the use case for `-F` in other `mkfs.*` commands (usually for automation), `mkswap` doesn't require the `-f` flag. These are the uses for the force flage from the [source code](https://github.com/util-linux/util-linux/blob/master/disk-utils/mkswap.c):

Erasing the first block on a device:
```c

if (!ctl->force) {
		if (lseek(ctl->fd, 0, SEEK_SET) != 0)
			errx(EXIT_FAILURE, _("unable to rewind swap-device"));

#ifdef HAVE_LIBBLKID
		pr = new_prober(ctl);
		blkid_probe_enable_partitions(pr, 1);
		blkid_probe_enable_superblocks(pr, 0);

		if (blkid_do_fullprobe(pr) == 0 &&
		    blkid_probe_lookup_value(pr, "PTTYPE", &v, NULL) == 0 && v) {
			type = xstrdup(v);
			zap = 0;
		}
#else
		/* don't zap if compiled without libblkid */
		zap = 0;
#endif
```

Requesting more swap space than is available on the device (I'd consider a bad idea to have on by default):
```c
else if (ctl.npages > sz && !ctl.force)
		errx(EXIT_FAILURE,
			_("error: "
			  "size %llu KiB is larger than device size %"PRIu64" KiB"),
			ctl.npages * (ctl.pagesize / 1024), sz * (ctl.pagesize / 1024));

```

### Issue Type

Feature Idea

### Component Name

filesystem

### Additional Information

```yaml (paste below)
---
- name: Install OS
  hosts: install
  remote_user: root
  vars:
    device: "/dev/vda"
  tasks:
    - name: Setup partition for main filesystem
      community.general.parted:
        device: "{{ device }}"
        label: gpt
        number: 1
        state: present
        flags:
          - boot
        part_start: 1MB
        part_end: -4GB

    - name: Setup partition for swap
      community.general.parted:
        device: "{{ device }}"
        label: gpt
        number: 2
        state: present
        flags:
          - swap
        part_start: -4GB

    - name: Format swap
      community.general.filesystem:
        fstype: swap
        dev: "{{ device }}2"
        state: present
        opts: ""
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by GustavoPeredo**
##### SUMMARY

FIXES #7946
Simply removes the `-f` flag from the variable `MKFS_FORCE_FLAGS` variable

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

filesystem
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pilou-** [comment]
When a filesystem is created by this module, regardless of the `force` module parameter, the _force flags_ switches (`-f` for the swap partitions) are used ([since always](https://github.com/ansible/ansible-modules-extras/commit/4932908754163b131d61f85882434d99361227c5)).

Should not the force flags be used only when the `force` module parameter is enabled?

**Comment by felixfontein** [comment]
> Erasing the first block device

I think that this is the main point of passing `-f`. The way I understand the mkswap man page, "mkswap will refuse to erase the first block on a device with a partition table" if this option is not supplied. It still succeeds, but prints a warning like
```
mkswap: foo: warning: don't erase bootbits sectors
        (gpt partition table detected). Use -f to force.
```
(`foo` is the filename of a 100 MB file I created and created a partition table in with `fdisk` before calling `mkswap foo`).

It doesn't seem to care about filesystem signatures (when I ran `mkfs.ext2 foo` first it only said "mkswap: foo: warning: wiping old ext2 signature." when calling without `-f`).

> Should not the force flags be used only when the `force` module parameter is enabled?

I think not. The way I understand the module and its `force` parameter is that by default, the module checks whether a filesystem already exists, and doesn't overwrite it unless you provide `force`. The "filesystem already exists" check of the `mkfs` commands is not really used, and that's why `-f` is always passed.

**Comment by pilou-** [comment]
> > Should not the force flags be used only when the `force` module parameter is enabled?
> 
> I think not. The way I understand the module and its `force` parameter is that by default, the module checks whether a filesystem already exists, and doesn't overwrite it unless you provide `force`. The "filesystem already exists" check of the `mkfs` commands is not really used, and that's why `-f` is always passed.

That makes sense :)

Then a fix would be to detect if Busybox is used and if so, remove the `-f` switch from the `Swap.MKFS_FORCE_FLAGS`.

**Comment by GustavoPeredo** [comment]
Removing "-f" just seems like the better option. The user can supply "-f" in the flags parameter if they wish to erase the first block, but in most cases this is really not needed/wanted. Also it spares some CPU cycles, but that's whatevs :P

If we stick to detecting busybox, is there an already established way of checking this? Or would this need to be implemented?

**Comment by felixfontein** [comment]
> If we stick to detecting busybox, is there an already established way of checking this? Or would this need to be implemented?

This would need to be implemented, I think. I would add a `__init__()` function to `Swap`, similar to `VFAT.__init__()`, that runs `mkswap --version` and checks whether its stderr output has a line starting with `BusyBox `.

**Comment by felixfontein** [comment]
I'm not sure whether it's the best way forward, but it is one that looks implementable with a not too large amount of effort, and it looks safe in that it doesn't break backwards compatibility.

**Comment by felixfontein** [comment]
@GustavoPeredo ping

needs_info

**Pull request closed without merging**
