### PR TITLE
dig: handle NoNameservers exception

### LINKED ISSUE #9362: dig lookup doesn't process dns.resolver.NoNameservers
### Summary

dig lookup doesn't process NoNameservers so it can't be ignored with fail_on_error set to false. NoNameserver can be raised for a lot of reasons, but a good example is querying authoritative servers to see if they have a domain configured yet. If the authoritative servers don't allow recursion (common), we'll get a refused answer when it doesn't handle the domain which will raise NoNameservers.

### Issue Type

Bug Report

### Component Name

dig

### Ansible Version

```console (paste below)
ansible [core 2.14.17]
  config file = /home/playbooks/ansible.cfg
  configured module search path = ['/home/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.21 (main, Dec  5 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

### Community.general Version

```console (paste below)
Collection        Version
----------------- -------
community.general 6.6.2

```

### Configuration

```console (paste below)
CONFIG_FILE() = /home/playbooks/ansible.cfg

```

### OS / Environment

Rocky9

### Steps to Reproduce

Query a domain that doesn't exist on an authoritative nameserver that doesn't allow recursion.

```yaml (paste below)
{% if not lookup('dig',dns_zone.name,'@' ~ dns_zone.masters|join(','),fail_on_error=false,real_empty=false,qtype='NS') == '' %}
```

### Expected Results

I expected an empty string because I have fail_on_error and real_empty both set to false. The playbook failed because dnspython raised an unhandled exception.

Fixed it on my local copy by adding to the same list with NoAnswer, Timeout, etc. necessary code was also not in 10.1.0.

            except dns.resolver.NoNameservers as err:
                if fail_on_error:
                    raise AnsibleError("Lookup failed: %s" % str(err))
                if not real_empty:
                    ret.append("")

### Actual Results

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleError: An unhandled exception occurred while running the lookup plugin 'dig'. Error was a <class 'ansible.errorrs.AnsibleError'>, original message: dns.resolver unhandled exception All nameservers failed to answer the query example.com. IN NS: Server Do53:x.x.x.x@53 answered REFUSED.

```console (paste below)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #9362.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
dig lookup

### CODE REVIEW

**Review by mariolenz — APPROVED** [review]
LGTM

**Comment by jpmens** [comment]
shipit

**Comment by felixfontein** [comment]
@mariolenz @jpmens thanks for reviewing this!

**Comment by felixfontein** [comment]
Manual backport to stable-9 in #9410.

**Pull request merged**
