### PR TITLE
hetzner_firewall: use correct state in example

### LINKED ISSUE #1148: hetzner_firewall example in documentation is wrong
##### SUMMARY

The parameter **state** is controlling whether the firewall is `present` or `absent` Yet the example code uses:

```yaml
status: active
```

A very easy mistake to make as **status** `active` or `disabled` is part of the return values. No idea why they are not the same but for now it's not working with the example.

P.S. the Edit on GitHub link is missing here: https://docs.ansible.com/ansible/latest/collections/community/general/hetzner_firewall_module.html and it seems to be broken elsewhere in the docs site anyway.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

hetzner_firewall

##### ANSIBLE VERSION

```paste below
ansible 2.10.1
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #1148.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
hetzner_firewall

### CODE REVIEW

**Comment by Andersson007** [comment]
can't this be
```
    status:
      description:
        - Status of the firewall.
        - C(active) or C(disabled).
        - Will be C(in process) if the firewall is currently updated, and
          I(wait_for_configured) is set to C(no) or I(timeout) to a too small value.
      type: str
      sample: active
```
?

**Comment by Andersson007** [comment]
ah , i saw the issue

**Comment by Andersson007** [comment]
sorry

**Review by Andersson007 — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@Andersson007 no problem, thanks a lot for reviewing this! :)

**Pull request merged**
