### PR TITLE
BOTMETA.yml: add maintainers of yum_versionlock module

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/community.general/pull/1405

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
BOTMETA.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
@riemers would you like to be added as a maintainer too? Your shipit/LGTM will be counted by the bot for automerge fixes/new features and you'll get notifications about related issues/PRs (i don't think there will be a lot, and nothing obligatory). If you don't want, please let me know, i'll remove your GH nick from the PR.
What do you think?

**Comment by felixfontein** [comment]
@Andersson007 I removed the backport label since the new module only exists in `main`, not in `stable-1`.

**Comment by Andersson007** [comment]
@felixfontein if there's no minor release of 1.* anymore, that's ok, thanks!

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@Andersson007 thanks!

**Comment by Andersson007** [comment]
@felixfontein thanks for merging!

**Pull request merged**
