### PR TITLE
Docs split filter guide

### PR DESCRIPTION
**Pull request by vbotka**
##### SUMMARY

Update docs. Split filter_guide.rst to files per section. Make the updates and maintenance easier.

##### ISSUE TYPE

- Docs Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by felixfontein — COMMENTED** [review]
Thanks, I really like this idea! I've built the result: https://ansible.fontein.de/collections/community/general/docsite/filter_guide.html

One thing I'm not really sure about is whether we want to do this split now (for a minor 4.x.0 release), or wait for the 5.0.0 release in May. If someone right now uses the link https://docs.ansible.com/ansible/latest/collections/community/general/docsite/filter_guide.html#merging-lists-of-dictionaries to directly go to the docmentation of the plugin, it will stop working as expected (and instead show what you see when clicking on this link: https://ansible.fontein.de/collections/community/general/docsite/filter_guide.html#merging-lists-of-dictionaries). If we include this in a minor release, this break will happen for users using `/latest/` or `/5/` in the URL very soon. If we wait for the next major release, the link with `/5/` will keep working as before, and only the `/latest/` version will break - and this will coincide with the new major Ansible 6 release.

On the other hand, the longer we wait, the more links exist pointing to the old structure - that would be a reason to change it sooner than later :)

I'll try to get some more opinions on this from the docs folks...

(Also CC @Ajpantuso @russoz)

**Comment by vbotka** [comment]
> I really like this idea!

I'm glad to hear this. The timing is up to you. Next, I split the section "Abstract information". This will allow me to generate *filter_guide_abstract_informations_merging_lists_of_dictionaries.rst* automatically for a template. Thank you.

**Comment by samccann** [comment]
I probably won't get to take a deep dive into this right now, but the benefits of multiple pages - Google finds the heading at the top of each page, but not necessarily  the lower headings. So today I can google community.general filter guide and find it, but not community.general paths for example. With this split, google will eventually work for that paths search.  So as you consider what and how to separate, take  that into consideration.

As for whether Abstract Transformations is also worth splitting up, it's hard for me to tell since I don't understand the technology and how a user would approach it. I can say the title 'abstract transformations' means very little to me. But a separate PR could work up update the new page titles to something a person might search for. (And for all I know, a user would search for ansible abstract transformations..lol!).

As for when to make this change, I think whatever works for you. Checking our internal web statistics, community.general overall has 77K hits so far this month. The guide has 279. So not a lot of people finding it yet either way.

**Comment by vbotka** [comment]
> I probably won't get to take a deep dive into this right now, but the benefits of multiple pages - Google finds the heading at the top of each page, but not necessarily the lower headings. So today I can google community.general filter guide and find it, but not community.general paths for example. With this split, google will eventually work for that paths search. So as you consider what and how to separate, take that into consideration.

I already did. There is an example of 2nd level *".. toctree::* working fine with Google. Take a look at the top-level TOC [VMware Guide](https://github.com/ansible-collections/community.vmware/blob/main/docs/docsite/rst/scenario_guide.rst). The item *vmware_scenarios/vmware_scenarios* provides 2nd level TOC [Ansible for VMware Scenarios](https://github.com/ansible-collections/community.vmware/blob/main/docs/docsite/rst/vmware_scenarios/vmware_scenarios.rst). 

Take a look at the page from this 2nd level TOC [Rename an existing virtual machine](https://docs.ansible.com/ansible/latest/collections/community/vmware/docsite/vmware_scenarios/scenario_rename_vm.html). The Introduction informs how to "utilize Ansible to find folder path of an existing VMware virtual machine". Searching this phrase in Google resulted in 4 hits with [Rename an existing virtual machine - Ansible Documentation](https://docs.ansible.com/ansible/latest/scenario_guides/vmware_scenarios/scenario_rename_vm.html) on the top.

> As for whether Abstract Transformations is also worth splitting up, it's hard for me to tell since I don't understand the technology and how a user would approach it. I can say the title 'abstract transformations' means very little to me. But a separate PR could work up update the new page titles to something a person might search for. (And for all I know, a user would search for ansible abstract transformations..lol!).

There are a lot of examples in this section. It's error-prone to publish them manually. Instead, it's possible to write the code of the examples, store the results in the files, and automate the generation of the *rst files for the subsections. See the playbook and the template in [community.general/docs/docsite/helper/lists_mergeby/](https://github.com/ansible-collections/community.general/tree/main/docs/docsite/helper/lists_mergeby). It's Ansible.

> As for when to make this change, I think whatever works for you. Checking our internal web statistics, community.general overall has 77K hits so far this month. The guide has 279. So not a lot of people finding it yet either way.

Thank you! Better publish it sooner than later.

**Comment by felixfontein** [comment]
> There are a lot of examples in this section. It's error-prone to publish them manually. Instead, it's possible to write the code of the examples, store the results in the files, and automate the generation of the *rst files for the subsections. See the playbook and the template in [community.general/docs/docsite/helper/lists_mergeby/](https://github.com/ansible-collections/community.general/tree/main/docs/docsite/helper/lists_mergeby). It's Ansible.

We might want to look at https://github.com/ansible-community/sphinx-ansible for this as well. I haven't tried it yet, but it certainly looks interesting.

Unfortunately it probably won't be a good idea to include it in the real docsite building process. That one is already really slow and Sphinx runs very low on available memory all the time. But I could imagine a preprocessing step where you mark a code listing as "This is Ansible listing X" and then a output listing as "This is the output of Ansible listing X", and then some script reads the file, runs the Ansible code, and replaces the output of that listing - and at the same time validates that the listing actually runs.

But this is nothing we'll have in the next two days ;-)

> > As for when to make this change, I think whatever works for you. Checking our internal web statistics, community.general overall has 77K hits so far this month. The guide has 279. So not a lot of people finding it yet either way.
> 
> Thank you! Better publish it sooner than later.

Sounds good to me, let's get it into 4.4.0 (released on Tuesday).

**Review by felixfontein — APPROVED** [review]
Looks good to me! The latest version of this PR is published here: https://ansible.fontein.de/collections/community/general/docsite/filter_guide.html

**Comment by felixfontein** [comment]
If nobody complains by Monday, I'll merge.

**Comment by vbotka** [comment]
> If nobody complains by Monday, I'll merge.

Take your time. See the helper. The generation of the section is completely automated now. The examples in the section are simplified. The examples in the rst directory aren't needed anymore.

**Comment by felixfontein** [comment]
I think it's better to not include docs changes into this PR. It mainly makes reviewing harder and delays merging. Do you mind reverting the last commit (and create a new PR out of it once this is merged)?

**Comment by vbotka** [comment]
OK. I reverted the last two commits.

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@vbotka thanks for suggesting and implementing this!
@samccann thanks for your feedback!

**Pull request merged**
