### PR TITLE
Cleanup changelog for not included zabbix plugins

### LINKED ISSUE #751: CHANGELOG entries regarding zabbix modules
##### SUMMARY
There are entries related to zabbix modules present in the CHANGELOG.rst. These were carried over from ansible/ansible, but modules have been migrated to the community.zabbix.

Should I open PR for removing them from CHANGELOG.rst and changelogs/changelog.yaml? Will this work or does someone need to regenerate changelog via antsibull-changelog?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
CHANGELOG.rst

### PR DESCRIPTION
**Pull request by D3DeFi**
##### SUMMARY
See #751 for whole discussion. I will move these entries to community.zabbix

Fixes #751 

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
changelogs/changelog.yaml

### CODE REVIEW

**Comment by D3DeFi** [comment]
cc @felixfontein 

better to merge this before 2.10 release so we dont have duplicate entries there from both community.{general,zabbix}

**Comment by felixfontein** [comment]
@D3DeFi it's more important to merge this before the next c.g release, the Ansible release itself doesn't really matter ;)

**Comment by felixfontein** [comment]
The failing tests are unrelated.

**Comment by D3DeFi** [comment]
should I also handle the backport?

**Comment by felixfontein** [comment]
@D3DeFi thanks for spotting this and fixing it as well!

**Comment by felixfontein** [comment]
@D3DeFi no, I will take care of that (we haven't really talked about backporting yet anyway, that will happen today, I'm just labelling everything that needs to be backported so we won't forget about it ;) ).

**Comment by D3DeFi** [comment]
Okeyo! Thank you 🙂

**Pull request merged**
