### PR TITLE
deps module utils: fix bug

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY

Fixes the problem where dependencies leak between modules.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

plugins/module_utils/deps.py

### CODE REVIEW

**Review by felixfontein — COMMENTED** [review]
Hmm, I'm not sure whether it is a good idea to make `deps` more complicated to prevent a situation that can only happen in the unit tests. How about trying to reset `deps` before the unit tests (or before all unit tests), maybe with some code in `tests/unit/plugins/modules/conftest.py`? Not sure whether the individual tests need to be marked or whether there is a mechanism that will run before every test (whether it uses the `deps` module utils or not) - the latter would probably be easier.

**Comment by russoz** [comment]
In a playbook with many modules using `deps`, the last one would be (re-)checking all the previous ones. While it should not fail (because it has been tested multiple times before), it is not clean. I don't reckon that to be a lot more complicated and it can be further simplified down the road - I wrote that in a rush.

**Comment by russoz** [comment]
And arguably it is better to encapsulate a bit of complication into that one util instead of adding one additional complication to all the unit tests that use it.

**Comment by felixfontein** [comment]
> In a playbook with many modules using `deps`, the last one would be (re-)checking all the previous ones. While it should not fail (because it has been tested multiple times before), it is not clean. I don't reckon that to be a lot more complicated and it can be further simplified down the road - I wrote that in a rush.

That's not true. Modules are run fully isolated with a new instance of the Python interpreter. (This would only *potentially* be different if `deps` is used for plugins - which right now is not the case.)

**Comment by felixfontein** [comment]
> And arguably it is better to encapsulate a bit of complication into that one util instead of adding one additional complication to all the unit tests that use it.

IMO using inspection in runtime code is always worse than cleaning up leakage between unit tests. I think it is OK to also fix the runtime code, especially if we also want to use this for plugins (and not just modules), but the separation between unit tests should always be ensured.

(Also I think the way you implement this probably makes it impossible to use this both from module_utils and module code. This change definitely needs some more discussion / review, but that shouldn't delay unbreaking the collection's unit tests.)

**Comment by felixfontein** [comment]
#6459 should fix the unit tests.

**Comment by russoz** [comment]
I will need to chew more on this one. Closing this PR for now.

**Pull request closed without merging**
