### PR TITLE
More docs cleanup

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
We no longer have to mention when something was added/removed/changed in Ansible 1.x or 2.x. This documentation is about the collection, and these changes refer to changes before the code moved into this collection.

Also the collection is Python 2.7+ now, so we don't have to mention that a module requires Python 2.6+ or Python 2.7+ anymore.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
various

### CODE REVIEW

**Comment by felixfontein** [comment]
bot_skip

**Comment by felixfontein** [comment]
recheck

**Review by mariolenz — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
The only two changes I'm not 100% confident of:
1. `ini_files`, removing the `Before Ansible 2.0...` part: should we mention instead that comments are generally preserved (up to potentially `O(modify_inactive_option=true)`)?
2. `timezone`, should information on "AIX 6.1+" be kept somehow? (The module fails for AIX < 6.1.) Now reading my question again, I guess the answer is "yes", let me push something for it :)

**Comment by mariolenz** [comment]
>     1. `ini_files`, removing the `Before Ansible 2.0...` part: should we mention instead that comments are generally preserved (up to potentially `O(modify_inactive_option=true)`)?

I'm not sure myself. Maybe someone else should comment this.

>     2. ~`timezone`, should information on "AIX 6.1+" be kept somehow? (The module fails for AIX < 6.1.) Now reading my question again, I guess the answer is "yes", let me push something for it :)~ [2abe568](https://github.com/ansible-collections/community.general/commit/2abe568d896436e758039b82fa4e9d640e3c1395)

Is this necessary? I mean, does the collection still support AIX < 6.1? I don't know much about AIX, but 6.1 seems to be EOL since 2017...

**Comment by felixfontein** [comment]
> Is this necessary? I mean, does the collection still support AIX < 6.1? I don't know much about AIX, but 6.1 seems to be EOL since 2017...

Individual modules support different things. Individual modules have to state what exactly they support. (Or well, they should, many aren't very explicit.) The collection only mandates which ansible-core versions are supported (and thus which Python versions are potentialy applicable), and that it's not supporting Windows.

**Pull request merged**
