### PR TITLE
proxmox_kvm: code cleanup

### PR DESCRIPTION
**Pull request by Aversiste**
##### SUMMARY

Collections of fixes regarding readability and some very small performance enhancements.
This is more of a proposal right now as I don't want to interfere too much with the long awaited PR #797.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

proxmox_kvm

### CODE REVIEW

**Review by Andersson007 — COMMENTED** [review]
is this about optimization only? if not, the PR has to have a changelog fragment https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to

**Comment by Andersson007** [comment]
@helldorado could you please take a look?

**Comment by helldorado** [comment]
Hello, This change makes the code more readable. shipit

**Comment by Andersson007** [comment]
@helldorado ok, thanks for reviewing!
@Aversiste , the author approved the PR, so if there are no fixes and resp. no changelog fragments needed, we could merge it, couldn't we?

**Comment by Aversiste** [comment]
> is this about optimization only? if not, the PR has to have a changelog fragment https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to

Optimizations are just a little bonus, the main goal was readability.
There is no change in behaviour.

> the author approved the PR, so if there are no fixes and resp. no changelog fragments needed, we could merge it, couldn't we?

There is downside: current PRs will be broken.

**Comment by Andersson007** [comment]
@Aversiste thanks for the explanation! We are now discussing in irc ansible-community if fragments are needed for refactoring PRs. Let you know a bit later.

**Comment by Andersson007** [comment]
@Aversiste yesterday the doc team decided to make fragments necessary for all PRs that can potentially affect any existing stuff. Could you please add the fragment https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to , then we could merge the PR

**Comment by Aversiste** [comment]
Done.

**Review by Andersson007 — APPROVED** [review]

**Comment by Andersson007** [comment]
@Aversiste thanks for the contribution!
@helldorado thanks for reviewing!
merged into main

**Comment by Andersson007** [comment]
@Aversiste the bot faild to create a backport automatically because it found conflicts. Could you create the backport this manually to stable-1 branch?

**Comment by Aversiste** [comment]
Of course !

**Comment by Aversiste** [comment]
[Done](https://github.com/ansible-collections/community.general/pull/956). It conflicted because of my PR #849.

**Comment by Andersson007** [comment]
@Aversiste thank you!

**Pull request merged**
