### PR TITLE
mysql modules: fix seealso section

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql and mysql modules: fix seealso section

fixes https://github.com/ansible-collections/community.general/pull/580

if it's ok, i can go through other modules in community.general (and maybe community.network) with my script

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
To solve https://github.com/ansible-collections/community.general/pull/580

**Comment by felixfontein** [comment]
@Andersson007 watch out that some `seealso`s refer modules from other collections (not here though).

**Comment by Andersson007** [comment]
@felixfontein thanks for reviewing!

**Comment by Andersson007** [comment]
merged https://github.com/ansible-collections/community.general/pull/580 into master

**Comment by Andersson007** [comment]
to solve https://github.com/ansible-collections/overview/issues/45

**Pull request merged**
