### PR TITLE
Supporting scripts for dealing with ignore.txt files

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
Scripts to assist removal of lines from the tests/sanity/ignore*.txt files

Brief description:
- ``count-ignores N <ignore-file>`` will count # of ignore files per module/group, N determines how many levels we use for grouping
- ``sort-ignores <ignore-files>`` will sort by the count of how many times a particular validation is ignored
- ``tmp-ansible-test`` will copy the collection structure to a temporary dir and run ansible-test on it
- ``tmp-tox`` will automatically create venvs with ansible 2.9, 2.10 and devel, and run ``tmp-ansible-test`` in each of them

##### ISSUE TYPE
- Docs Pull Request

##### ADDITIONAL INFORMATION
Scripts ``count-ignores`` and ``sort-ignores`` should work in any Posix system. Examples:
```bash
$ ./tests/utils/sanity_ignores/sort-ignores tests/sanity/ignore-2.10.txt | head -3
    129 validate-modules:parameter-list-no-elements
     87 validate-modules:parameter-type-not-in-doc
     84 validate-modules:doc-missing-type
```
```bash
$ ./tests/utils/sanity_ignores/count-ignores tests/sanity/ignore-2.9.txt 1 | head -3
   165 cloud
    74 net_tools
    52 remote_management
$ ./tests/utils/sanity_ignores/count-ignores tests/sanity/ignore-2.9.txt 3 | head -3
     6 net_tools/nios/nios_nsgroup.py
     4 cloud/ovirt/ovirt_host_storage_facts.py
     4 cloud/ovirt/ovirt_storage_template_facts.py
```
The script ``tmp-ansible-test`` requires ``ansible-test`` to be in the ``PATH``, and respectively ``tmp-tox`` requires ``tox`` to be in ``PATH``. Example:
```bash
$ ./tests/utils/sanity_ignores/tmp-tox -- --test validate-modules plugins/modules/system/lvol.py
sanity-ansible29 installed: ansible==2.9.15,cffi==1.14.4,cryptography==3.2.1,Jinja2==2.11.2,MarkupSafe==1.1.1,pycparser==2.20,PyYAML==5.3.1,six==1.15.0
sanity-ansible29 run-test-pre: PYTHONHASHSEED='1994142645'
sanity-ansible29 run-test: commands[0] | tmp-ansible-test sanity --docker default -v --test validate-modules plugins/modules/system/lvol.py
top_dir=/tmp/dev.0cJUi
coll_dir=/tmp/dev.0cJUi/ansible_collections/community/general
...
sanity-ansible210 run-test: commands[0] | tmp-ansible-test sanity --docker default -v --test validate-modules plugins/modules/system/lvol.py
...
sanity-ansibledev run-test: commands[0] | tmp-ansible-test sanity --docker default -v --test validate-modules plugins/modules/system/lvol.py
...
_____________________________________________________________ summary ______________________________________________________________
  sanity-ansible29: commands succeeded
  sanity-ansible210: commands succeeded
  sanity-ansibledev: commands succeeded
  congratulations :)
```

### CODE REVIEW

**Comment by russoz** [comment]
I was using these scripts to mow through the ignore lines these last couple of weeks. The `tox` one really helped with the differences between 2.9 and 2.10.

What prompted me to raise a PR for including them was:
https://github.com/ansible/community/issues/539#issuecomment-738320567

**Comment by felixfontein** [comment]
I think such tools are much better suited for community.internal_test_tools (https://github.com/ansible-collections/community.internal_test_tools).

**Comment by russoz** [comment]
@felixfontein OK, I didn't noticed that other repo, it probably makes more sense there, yes.

**Comment by russoz** [comment]
Closing this one, will raise another on `community.internal_test_tools`.

**Pull request closed without merging**
