### PR TITLE
BOTMETA.yml: Add a new maintainer of pkgin module

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/community.general/pull/1256

BOTMETA.yml: Add a new maintainer of pkgin module

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
`.github/BOTMETA.yml`

### CODE REVIEW

**Comment by Andersson007** [comment]
@martinm82 could you please approve the PR

**Review by martinm82 — APPROVED** [review]

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@martinm82 thanks!

**Comment by Andersson007** [comment]
@martinm82 thanks for becoming a maintainer of the module!

**Comment by martinm82** [comment]
Will try to give my best :D

**Pull request merged**
