### PR TITLE
Add Ubuntu 20.04 to CI

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
See ansible/ansible#69161.

##### ISSUE TYPE
- CI Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by jpmens** [comment]
why am I being mentioned?

**Comment by felixfontein** [comment]
@jpmens you are a maintainer of the mqtt module.

**Comment by jpmens** [comment]
@felixfontein I see no mention of MQTT other than a commit you added (which I don't understand) and which simply says `skip/ubuntu2004  # FIXME`...

**Comment by felixfontein** [comment]
@jpmens since the commit touches the mqtt tests (even if it just adjusts the aliases file), it could affect the mqtt module, so its maintainers are pinged. That's how the bot works.

**Comment by felixfontein** [comment]
This is now officially available: https://github.com/ansible-collections/overview/issues/45#issuecomment-765670564

**Review by gundalow — APPROVED** [review]

**Comment by felixfontein** [comment]
@gundalow thanks for reviewing and merging!

**Pull request merged**
