### PR TITLE
Use semantic markup (modules d-g)

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
For information on semantic markup, see https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#semantic-markup-within-module-documentation.

Ref: #6627

(Note: I'm only considering modules containing `I(` for now.)

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
modules starting with d-g

### CODE REVIEW

**Comment by felixfontein** [comment]
I'll merge this by tomorrow evening if nobody objects.

**Comment by ramondelafuente** [comment]
@felixfontein There's a #TODO added in the deploy_helper, not sure if that is inteded to be picked up later or if it should be part of this PR?

https://github.com/ansible-collections/community.general/pull/6672/files#diff-0040ba9156ac4621961e2305207033721b58658007992db035fc6bbbdfd3055aR23

**Comment by ramondelafuente** [comment]
Yeah indeed, also true for this one I guess. I'll take a look at the new and shiney documentation options, but I'm not sure if I can get this module documented any time soon.

**Comment by felixfontein** [comment]
@ramondelafuente thanks!

**Pull request merged**
