### PR TITLE
Failing CodeQL workflow: another try: fix languages to check

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Let's try this before #5586.

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by konstruktoid** [comment]
can you trigger a run so we don't have to wait a week?

**Comment by felixfontein** [comment]
Right now (or when this is merged) no. The workflow does not expose a manual trigger.

**Comment by felixfontein** [comment]
It does work now: https://github.com/ansible-collections/community.general/actions/runs/3523113937/jobs/5906878150

**Comment by konstruktoid** [comment]
great!

**Pull request merged**
