### PR TITLE
[stable-8] Fix the homebrew module failing because of warnings (#8406)

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Manual backport of #8406 to stable-8.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
homebrew

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @kustodian @Israphel

**Comment by kustodian** [comment]
Looks good xD

**Review by russoz — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@kustodian @russoz thanks for reviewing!

**Pull request merged**
