### PR TITLE
Deprecate logicmonitor and logicmonitor_facts

### LINKED ISSUE #539: Deprecate logicmonitor_facts and logicmonitor module
##### SUMMARY
[`logicmonitor`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/monitoring/logicmonitor.py) and [`logicmonitor_facts`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/monitoring/logicmonitor_facts.py) are based upon RPC and [deprecated](https://www.logicmonitor.com/support/rpc-api-developers-guide/overview/using-logicmonitors-rpc-api/) in Dec 1, 2017.

There are no active maintainer for these modules - https://github.com/ansible/ansible/pull/67287

I would recommend deprecating these modules in favor of `uri` modules.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/modules/monitoring/logicmonitor.py
plugins/modules/monitoring/logicmonitor_facts.py

##### ANSIBLE VERSION

```paste below
devel
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #539.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
logicmonitor
logicmonitor_facts

### CODE REVIEW

**Comment by gundalow** [comment]
If the API has been turned of we can delete the contents and just mock out main

**Comment by felixfontein** [comment]
@gundalow in that case, wouldn't it better to remove them and tombstone them?

**Comment by gundalow** [comment]
Yup, that's better.

**Comment by felixfontein** [comment]
ready_for_review

The remaining bad test is due to postgres.

**Comment by Akasurde** [comment]
@felixfontein I will close these issue once this PR is merged - https://github.com/ansible-collections/community.general/issues/539#issuecomment-646498500

**Comment by felixfontein** [comment]
@Akasurde @gundalow thanks for reviewing!

**Pull request merged**
