### PR TITLE
gio_mime: add return value version

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY

Add RV `version` to module.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

gio_mime

### CODE REVIEW

**Comment by russoz** [comment]
@felixfontein something different in the CI? only 13 checks???

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
> @felixfontein something different in the CI? only 13 checks???

Hmm, it seems that for some reason AZP didn't run.

**Comment by felixfontein** [comment]
It's an AZP problem: https://status.dev.azure.com/_event/559260722

**Comment by felixfontein** [comment]
@russoz thanks for your contribution!

**Pull request merged**
