### PR TITLE
[stable-1] Add OC, hashi_vault and Google removal announcements

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
See ansible-collections/overview#128.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
changelog

### CODE REVIEW

**Comment by felixfontein** [comment]
recheck

**Comment by felixfontein** [comment]
recheck

**Comment by felixfontein** [comment]
recheck

**Review by Andersson007 — APPROVED** [review]
LGTM but `i.e.` -> `in other words`, IMO, it would be better:)

**Comment by felixfontein** [comment]
I replaced `i.e.` with `in other words` for the `oc` fragment (since there is exactly one plugin and thus one FQCN), and with `for example` for the `google` fragment (since there it is an example).

**Comment by felixfontein** [comment]
This should only be merged once https://github.com/ansible-community/ansible-build-data/pull/47 has been merged.

**Review by gundalow — APPROVED** [review]

**Comment by felixfontein** [comment]
@Andersson007 @gundalow thanks for reviewing!

**Pull request merged**
