### PR TITLE
 Tidy up validate-modules ignores for modules: cloud/centurylink

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
Tidy up on sanity tests' ignore files, removing lines with validation-modules for these modules.

The focus was to pass the tests so no code was changed other than adjusting argument_spec for missing types or inconsistencies with the docs. The priority has been not to change any functionality, but to ensure that code and docs are synchronized.

Some lines were added back to the files, but a total of 77 lines were removed (among 2.9, 2.10 and 2.11).

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
plugins/modules/cloud/centurylink/clc_server_snapshot.py
plugins/modules/cloud/centurylink/clc_server.py
plugins/modules/cloud/centurylink/clc_publicip.py
plugins/modules/cloud/centurylink/clc_modify_server.py
plugins/modules/cloud/centurylink/clc_loadbalancer.py
plugins/modules/cloud/centurylink/clc_group.py
plugins/modules/cloud/centurylink/clc_blueprint_package.py
plugins/modules/cloud/centurylink/clc_firewall_policy.py
plugins/modules/cloud/centurylink/clc_alert_policy.py
plugins/modules/cloud/centurylink/clc_aa_policy.py

### CODE REVIEW

**Comment by felixfontein** [comment]
@russoz you need to rebase, there are conflicts.

**Comment by russoz** [comment]
recheck

**Comment by felixfontein** [comment]
I think ansibullbot auto-cancels CI (at least Shippable) until the merge commit is gone.

**Comment by russoz** [comment]
duplicate_of #1365

**Pull request closed without merging**
