### PR TITLE
docker_container: make sure to_text() and to_native() are used instead of str()

### LINKED ISSUE #640: docker_container: UnicodeDecodeError on probe to set docker ENV variable with non ASCII chars
##### SUMMARY

If i put any Cyrillic chars in docker ENV then running `ansible-playbook myapp.yml` fails with Python error:
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 17: ordinal not in range(128)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
ansible python module location = /usr/lib/python3.6/site-packages/ansible
python version = 3.6.10 (default, Jan 16 2020, 09:12:04) [GCC]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

- CentOS Linux 7
- Python 2.7.5
- Docker version 1.13.1, build 64e9980/1.13.1

##### STEPS TO REPRODUCE

1. create docker container with ansible

```yaml
---
 - hosts:
    - virtualbox
  tasks:
    - name: pull image and restart container
      docker_container:
         image: busybox
        name: test_non_ascii
        env:
          MY_ENV_TO: "Абвг «Д»"
        command: "echo $MY_ENV_TO"
```
2. run this playbook again

##### EXPECTED RESULTS

no error

##### ACTUAL RESULTS

```paste below
MODULE FAILURE
File \"/tmp/ansible_docker_container_payload_LJPmWa/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py\", line 2174, in has_different_configuration\r\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 17: ordinal not in range(128)\r\n"
```
```paste
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1594371809.4944637-14716-155893099858081/AnsiballZ_docker_container.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1594371809.4944637-14716-155893099858081/AnsiballZ_docker_container.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1594371809.4944637-14716-155893099858081/AnsiballZ_docker_container.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.docker.docker_container', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_docker_container_payload_etxiiI/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 3369, in <module>
  File "/tmp/ansible_docker_container_payload_etxiiI/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 3360, in main
  File "/tmp/ansible_docker_container_payload_etxiiI/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 2568, in __init__
  File "/tmp/ansible_docker_container_payload_etxiiI/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 2639, in present
  File "/tmp/ansible_docker_container_payload_etxiiI/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 2174, in has_different_configuration
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 10: ordinal not in range(128)```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #640.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_container

### CODE REVIEW

**Comment by felixfontein** [comment]
ready_for_review

**Comment by jwitko** [comment]
I no longer have a review button on these PRs since moving to `ansible-collections`.   Have reviewing changed to text based or something?

**Comment by felixfontein** [comment]
@jwitko I've never seen a "review" button in ansible/ansible. AFAIK nothing changed, reviews are possible as before with the GitHub interface (you can switch to "Files changed", and add annotations to lines with the "+" button next to the line number, and send off the result with the "Review changes" button at the top right).

The only change is that GitHub recently upgraded their UI.

**Comment by felixfontein** [comment]
CC @Andersson007

**Comment by Andersson007** [comment]
the following files should be changed as well:
```
plugins/modules/cloud/docker/docker_compose.py
plugins/modules/cloud/docker/docker_image_facts.py
plugins/modules/cloud/docker/docker_image_info.py
plugins/modules/cloud/docker/docker_image.py
plugins/modules/cloud/docker/docker_login.py
plugins/modules/cloud/docker/docker_network.py
plugins/modules/cloud/docker/docker_service.py
```

**Comment by felixfontein** [comment]
@jwitko @Andersson007 thanks a lot for reviewing (or at least trying :) )!

**Comment by Andersson007** [comment]
as an idea for the next pr ^
YW

**Pull request merged**
