### PR TITLE
pkgng: add basic integration tests

### PR DESCRIPTION
**Pull request by overhacked**
##### SUMMARY

Add tests for the `pkgng` module, because it doesn't have any. I'd like to add features and address a few issues with the module, and it would be nice to have integration tests.

###### Tests added:
(*All tests also check for idempotency unless noted otherwise*)
* Install a package
* Install into a jail
* Install into a chroot
* Install into an alternate rootdir
* Upgrade a package
* Remove a package
* Install multiple packages; ensure pkg only executes once
* Upgrade/install multiple packages; ensure pkg runs twice, one `upgrade` and one `install`
* Remove a package with `autoremove=yes`; ensure all dependencies are also removed
* Annotate packages: add/modify/remove
* Alternate `pkgsite`

###### Minor features/fixes:
* Upgrading all packages (`name=* state=latest`) did not count "packages to be reinstalled" (due to dependency or build option changes), giving incorrect results for `changed`.
* #3393 broke `check_mode`; fixed so `changed` is correct and number of planned `upgrade` and `install` actions is correct.
* The `annotation` parameter just didn't work due to some longstanding typos, and `check_mode` was not just unsupported but changes to annotations would be made even if `check_mode=yes`.

###### Planned features/fixes that build on this PR:
* Support installing packages from local paths the target host's filesystem. This is supported by `pkg`, but the module's use of the `-g`/`--glob` flag prevents it. Reworking this is more than a minor change, because the local file path has to be detected and the `-g` flag omitted in several places, across multiple functions. This will allow closing #3428.
* Fix some idempotency flaws when using wildcards: if packages are installed with a wildcard, e.g. `py38-*`, the module will skip running the install or upgrade action if **any** package, even just one, matching the pattern is installed.

##### ISSUE TYPE

- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME

pkgng

### CODE REVIEW

**Comment by felixfontein** [comment]
recheck

**Comment by overhacked** [comment]
recheck_failed

**Comment by felixfontein** [comment]
FYI: please note that all code changes (outside tests) require a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to).

**Comment by felixfontein** [comment]
recheck

**Pull request merged**
