### PR TITLE
postgresql_ext: fix module's failing when available ext versions contain a pure string

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.general/issues/1095

postgresql_ext: fix module's failing when available ext versions contain a pure string

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`plugins/modules/database/postgresql/postgresql_ext.py`

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
@rdehouss @tcraxs @andytom @kostiantyn-nemchenko  , in the PR the module i put incomparable versions to available version as they are.
The main question is whether we should eliminate such versions (i.e. not to append them to available versions list) ?
Waiting for your feedback

**Comment by gundalow** [comment]
bot_status

**Comment by gundalow** [comment]
bot_status

**Comment by tcraxs** [comment]
@Andersson007 I like your approach to avoid the failure. The postigs extension is quite difficult. I had also some struggles with that, but always fixed it manually instead of with ansible 😉 
From my point it will be fine to just raise an error if the version cannot be compared because of no leading number (pure string).

In this special case the `unpackaged` will also not be installed or updated by the module. So I like to see a warning or an error of the module.

**Comment by Andersson007** [comment]
@tcraxs thanks for the reply!
Can't `unpackaged` be installed if this is in `available_versions`?
So, you're suggesting not adding this to `ansible_versions` and raise, e.g., a warning?

**Comment by tcraxs** [comment]
> @tcraxs thanks for the reply!
> Can't `unpackaged` be installed if this is in `available_versions`?
https://postgis.net/workshops/postgis-intro/upgrades.html
I'm not sure. I also had the problem and solved it by `drop extension` followed by `create extension`. Not the best solution but worked in my cases. I can remember that there was a postgis script which need to be executed and some manual steps after the unpackaged was installed. I'm not sure if this is covered by the ansible module (I bet not 😉 ).

> So, you're suggesting not adding this to `ansible_versions` and raise, e.g., a warning?
Yes. To avoid such situations of updating extensions which are not able to update easily or net some additional steps.

Warning: My experience with upgrading extensions is quite low, so I could be completely wrong, and upgrades of extensions are standardised and this `unpackaged` is normal, then we should solve this topic in the module.

**Comment by rdehouss** [comment]
Well, I'm not sure we can easily upgrade to `unpackaged` butif having this version in the available ones does not cause issue to determine the "latest" version, it's ok to keep it I guess.
Or because it's a special case, it should be handled differently and a warning explain that this version cannot be installed "like that" but with another parameter for example.

My 2 cents

**Comment by Andersson007** [comment]
>>> from distutils.version import LooseVersion
>>> a = ['unpackaged', '1.0.1dev', '1.0.1', '3.0.2']
>>> sorted(a, key=LooseVersion)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib64/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'

This will fail when returning, line:
```
294     return (current_version, sorted(available_versions, key=LooseVersion))
```
So, we have to remove this with warning that this version cannot be installed. I'll change the PR

**Comment by strk** [comment]
I suggest you just skip 'unpackaged' from the list of
available_version. Providing an 'unpackaged' version is an hack
implemented in PostGIS to work-around drop of support for the
syntax:


  CREATE EXTENSION postgis FROM unpckaged;

The drop of such support started in PostgreSQL 13

**Comment by Andersson007** [comment]
@strk sounds good, thanks! I'm doing this now

**Comment by Andersson007** [comment]
I think we can just add a note about this without any warnings? It can be irritating for users, can't it?

**Comment by Andersson007** [comment]
I'll push the updated version after local tests passed

**Comment by Andersson007** [comment]
The joke is that i found out i can't reproduce TypeError passing `unpackaged` to the function:) See unit tests.
Output equals input...
strange...
Will continue to struggle tomorrow:)
Interesting if there are other options that can't be compared by LooseVersion? if no, we could just

**Comment by Andersson007** [comment]
Maybe this is because of python version in ci or something.
ready_for_review

**Review by tcraxs — APPROVED** [review]
shipit

**Comment by rdehouss** [comment]
shipit

**Comment by Andersson007** [comment]
@tcraxs @rdehouss @strk thanks for reviewing!

**Pull request merged**
