### PR TITLE
[stable-1] Fix capabilities validation for device_requests

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Backport of https://github.com/ansible-collections/community.docker/pull/43 to stable-1.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
docker_container

### CODE REVIEW

**Comment by felixfontein** [comment]
Looks identical to original commit.

**Review by Andersson007 — APPROVED** [review]
LGMT

**Comment by Andersson007** [comment]
@felixfontein thanks for backporting the fix!

**Comment by felixfontein** [comment]
@Andersson007 thanks for reviewing and merging! :)

**Pull request merged**
