### PR TITLE
Remove deprecated modules scheduled for removal in 3.0.0

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Preparations for the 3.0.0 release.

If from now on someone wants to add fixes to these modules, this needs to be done in the stable-2 branch.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME
collection

### CODE REVIEW

**Comment by felixfontein** [comment]
The remaining sanity errors are expected, since the removal version numbers are in the future compared to the version in galaxy.yml.

**Comment by russoz** [comment]
hi @felixfontein I think we're missing the `modules/cloud/misc/ovirt.py` in the changelog fragment (it is being removed, and its mention in ignore lines is going as well, but no mention in the chengelog). That's the odd one out: all other `ovirt` modules are under `.../cloud/ovirt/`, this is hte only one at `.../cloud/misc`

**Comment by felixfontein** [comment]
@russoz I think it's there: https://github.com/ansible-collections/community.general/pull/1924/files#diff-ce1af277b1a883f721e2a4669cdd3d6a7bfd09cc1641a0f08f191152c7c1dbafR36

**Comment by russoz** [comment]
hmmm I did search but I think I was misled by the `ovirt_vm` on the other end. 

BTW, I cloned this branch locally: it takes the ignore lines down to 405 :)

**Comment by felixfontein** [comment]
Rebased now that #1926 has been merged.

**Comment by felixfontein** [comment]
I'll merge this PR (which bumps the next expected release to 3.0.0) once I've started the release process of 2.5.0. Then `main` is in 3.0.0 mode and no more features will be backported to stable-2.

**Pull request merged**
