### PR TITLE
modules: fix seealso sections

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fix seealso sections in community.general https://github.com/ansible-collections/overview/issues/45

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
to solve https://github.com/ansible-collections/overview/issues/45

**Comment by felixfontein** [comment]
Merging, since all tests fail except one timeout (soon to be), which is expected.

**Comment by felixfontein** [comment]
(Freudian typo? :D )

**Comment by felixfontein** [comment]
@Andersson007 thanks for fixing this!

**Comment by Andersson007** [comment]
@felixfontein thanks for reviewing and merging!

**Comment by Andersson007** [comment]
@gundalow thanks for reviewing!

**Pull request merged**
