### PR TITLE
routeros_facts: fix crash when ipv6 is disabled

### PR DESCRIPTION
**Pull request by heuels**
##### SUMMARY

Hi guys! Do you accept PRs to this repository yet? I must say it's been some challenge finding the place where all the network modules have been moved to :)

What you see here is a copy of a PR to the main Ansible repository (ansible/ansible#65077), I'm hoping to get it merged soon because it's a stupid bug that affects a lot of people.

This PR fixes a bug in `routeros_facts` that leads to a crash when trying to fetch network interfaces if `ipv6` package is not enabled on the target router.

Fixes ansible/ansible#64958 and fixes ansible/ansible#66655.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`routeros_facts`

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by felixfontein** [comment]
Hi @heuels! PRs are only partially accepted, since the testing infrastructure isn't complete yet. But depending on the PR it's good enough :)

Please note that your fixture filename (!) has a trailing space. That might solve the failing unit tests.

**Comment by heuels** [comment]
@felixfontein Thanks, I've changed the fixture filename. Never thought that a trailing space in a filename is even a thing!

**Comment by felixfontein** [comment]
@heuels you can even have newlines! Guess how much fun *that* is :D

**Comment by gundalow** [comment]
@heuels @felixfontein merged, thank you.

**Comment by felixfontein** [comment]
Thanks as well! @heuels do you want to "backport" this to ansible/ansible's stable-2.9 branch? Then it should appear in one of the next 2.9.x releases. Backporting is a bit more complicated now, though, you essentially have to create a new PR in ansible/ansible for the stable-2.9 branch which does the same thing as the PR here (and it needs a changelog fragment).

**Comment by heuels** [comment]
@gundalow, thank you!

@felixfontein, sure, I will submit a backport PR to the Ansible repository today.

**Comment by felixfontein** [comment]
@heuels great! BTW, I added a changelog fragment for this PR in #74, feel free to check it and re-use it in ansible/ansible :)

**Comment by heuels** [comment]
Here is the backport PR: ansible/ansible#68554.

**Pull request merged**
