### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
See https://github.com/ansible-collections/overview/issues/45#issuecomment-776859063 and the change below.

I made sure that the targets removed from devel are covered by stable-2.10.

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by felixfontein** [comment]
There's a total increase in one target with three stages, so a total increase of three targets.

**Comment by felixfontein** [comment]
Currently blocked on ansible/ansible#73563.

**Review by Andersson007 — APPROVED** [review]
If this is expected `ERROR: Command "/usr/bin/python3.6 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py check --disable-pip-version-check" returned exit status 1.` , LGTM

**Comment by felixfontein** [comment]
I'm going to merge this so that CI is mostly working again. All of CI should be working again once ansible/ansible#73563 is fixed.

**Comment by felixfontein** [comment]
@Andersson007 thanks for reviewing this!

**Comment by felixfontein** [comment]
Will backport to stable-1 manually later today.

**Comment by felixfontein** [comment]
Backport to stable-1 started in #1790.

**Pull request merged**
