### PR TITLE
Add new modules rundeck_job_run and rundeck_job_executions_info

### PR DESCRIPTION
**Pull request by phsmith**
##### SUMMARY

Adding new modules for executing jobs and get job executions info in Rundeck .

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

- rundeck_job_run
- rundeck_job_executions_info

### CODE REVIEW

**Comment by phsmith** [comment]
@russoz, thanks for the review and the proposed changes.
I've fixed the modules and think that's better now.

**Comment by phsmith** [comment]
> I added the [WIP] prefix to the title to indicate you're still working on this.

Thanks a lot @russoz!

**Comment by phsmith** [comment]
> Hey @phsmith , thanks again for the contribution! Looking good to me (*)!!
> 
> Now I will let the other guys take a look and merge it.
> 
> (*) I still think more examples on the "run" module would help the documentation, but not going to stop it for that.

To get it finished, I've sent a update with more examples to the rundeck_job_run module as suggested.
Thanks a lot for the support and reviews!

**Comment by phsmith** [comment]
Thanks a lot for the support guys, It was very helpful and I learned a lot!

**Comment by felixfontein** [comment]
@phsmith thanks for contributing these modules!
@russoz @Ajpantuso thanks for reviewing!

**Pull request merged**
