### PR TITLE
nagios: force an active service check for all services of a particular host or for the host itself

### PR DESCRIPTION
**Pull request by trumbaut**
##### SUMMARY

Added functionality to force an active service check for all services of a particular host or for the host itself.

Note that I've renamed the `service_check` command to `forced_check` since we now are able to check both a particular service, all services of a particular host and the host itself. This aligns to the `downtime` command.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

nagios.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by felixfontein** [comment]
If `service_check` should be renamed, it must be done today, since we release community.general 1.2.0 tomorrow. Once its released, a rename would be a breaking change.

You need a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to).

**Comment by tgoetheyn** [comment]
A rename is fine for me, as this way of doing it aligns the function more with the existing `downtime` command

**Review by tgoetheyn — APPROVED** [review]
Tested on my development environment.
Everything works fine

**Comment by tgoetheyn** [comment]
@felixfontein the code itself is ok.

If the changelog fragment is compliant with the guidelines, then it can be merged

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@trumbaut thanks for implementing this!
@tgoetheyn thanks for testing and reviewing!

**Pull request merged**
