### PR TITLE
Add REQUIRE X509 privilege

### PR DESCRIPTION
**Pull request by Jorge-Rodriguez**
##### SUMMARY
Allows granting the special REQUIRE X509 privilege. Similar to REQUIRE SSL but more restrictive as it requires both server and client certificate validation.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
mysql_user

```

### CODE REVIEW

**Comment by Jorge-Rodriguez** [comment]
@Andersson007 
Here's the moved PR.
I would like to reopen the conversation because the suggestion to add REQUIRE SUBJECT|ISSUER|CYPHER is very interesting but all of those privileges require parameters and I would like to hear ideas on how to pass those.

**Comment by Jorge-Rodriguez** [comment]
@jpmens @rwky I would like to hear your thoughts on how to add the require SUBJECT|ISSUER|CYPHER privileges given that they require parameters (the code checks the privileges against a set of acceptable privileges, the fact that some privileges could be parameterized was not considered.)

**Comment by rwky** [comment]
I no longer use X509 + Ansible + MySQL so I can't really test/experiment with it.

**Comment by Andersson007** [comment]
i relaunched the tests. there is some sanity stuff to fix like
```
plugins/modules/database/mysql/mysql_user.py:657:41: undefined-variable: Undefined variable 'outuput'
```

**Comment by Jorge-Rodriguez** [comment]
Apparently I have a fat finger.
BTW, this PR and #369 address the same issue, but #369 is more complete and deprecates the use of `priv` to specify SSL requirement

**Comment by Andersson007** [comment]
> Apparently I have a fat finger.
> BTW, this PR and #369 address the same issue, but #369 is more complete and deprecates the use of `priv` to specify SSL requirement

@Jorge-Rodriguez 
if #369 solves the same issue and is more complete, so please close this one

**Comment by Jorge-Rodriguez** [comment]
@Andersson007 I'm in two minds about closing this PR, since it's not incompatible with the other one.
This PR extends the use of `priv` to require X509 in the same manner that it already supports SSL, while the other PR introduces a brand new parameter.
With this in mind I'd appreciate feedback on how to proceed.
It comes to mind that we could include a deprecation notice for `priv: *.*/REQUIRESSL` in #369

**Comment by gundalow** [comment]
recheck

**Comment by Jorge-Rodriguez** [comment]
I'm closing this PR in favor of #369

**Pull request closed without merging**
