### PR TITLE
Tidy up validate-modules ignores for packaging modules

### PR DESCRIPTION
**Pull request by russoz**
##### SUMMARY
Tidy up on sanity tests' ignore files, removing lines with validation-modules for these modules.

The focus was to pass the tests so no code was changed other than adjusting argument_spec for missing types or inconsistencies with the docs. The priority has been not to change any functionality, but to ensure that code and docs are synchronized.

Some lines were added back to the files, but a total of 98 lines were removed (among 2.9, 2.10 and 2.11).

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
plugins/modules/packaging/os/zypper.py
plugins/modules/packaging/os/xbps.py
plugins/modules/packaging/os/urpmi.py
plugins/modules/packaging/os/slackpkg.py
plugins/modules/packaging/os/rhn_channel.py
plugins/modules/packaging/os/pkg5.py
plugins/modules/packaging/os/pacman.py
plugins/modules/packaging/os/opkg.py
plugins/modules/packaging/os/openbsd_pkg.py
plugins/modules/packaging/os/macports.py
plugins/modules/packaging/os/apt_rpm.py
plugins/modules/packaging/os/apk.py
plugins/modules/packaging/language/yarn.py
plugins/modules/packaging/language/pear.py
plugins/modules/packaging/language/maven_artifact.py
plugins/modules/packaging/language/gem.py
plugins/modules/packaging/language/easy_install.py
plugins/modules/packaging/language/cpanm.py
plugins/modules/packaging/language/composer.py
plugins/modules/packaging/language/bundler.py
plugins/modules/packaging/language/bower.py

### CODE REVIEW

**Review by gundalow — APPROVED** [review]
Great work, thank you for this

**Comment by gundalow** [comment]
@russoz Ah, you spotted the inversion, that should be good. Once CI is green I'll merge.

**Review by felixfontein — APPROVED** [review]

**Comment by russoz** [comment]
@gundalow @felixfontein  thx for reviewing... it's late here, it seems something funky happened in the CI this one last run, will trigger it again and will check it out tomorrow. On the happy side, since we started chopping down the ignore lines, have gone from:
```
$ wc -l tests/sanity/ignore-2.*
  1282 tests/sanity/ignore-2.10.txt
  1282 tests/sanity/ignore-2.11.txt
  1007 tests/sanity/ignore-2.9.txt
  3571 total
```
to:
```
$ wc -l tests/sanity/ignore-2.*
   913 tests/sanity/ignore-2.10.txt
   913 tests/sanity/ignore-2.11.txt
   741 tests/sanity/ignore-2.9.txt
  2567 total
```
not bad eh? :)

**Comment by russoz** [comment]
recheck

**Comment by felixfontein** [comment]
The OpenSuSE tests are known to be failing (to me, haven't created an issue yet). It's not related to this PR.

**Comment by russoz** [comment]
Thx guys!

**Pull request merged**
