### PR TITLE
Test of using FQCN for some builtin plugins

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Test of using FQCN for some builtin plugins

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by felixfontein** [comment]
BTW, I've mentioned this problem to @nitzmahone yesterday, I think he is looking into it. It could be that `set_fact` and `include_vars` need to be fixed.

**Comment by Andersson007** [comment]
@felixfontein local docker tests have been passed well

**Comment by Andersson007** [comment]
@felixfontein shippable succeeded

**Comment by felixfontein** [comment]
@Andersson007 thanks for fixing this!

**Pull request merged**
