### PR TITLE
Make sure frenck is no longer accidentally contacted

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
See discussion in #358. The statements made by him in #358 should suffice, so no more pinging here is needed.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
.github/BOTMETA.yml
plugins/modules/system/osx_defaults.py

### CODE REVIEW

**Review by martinm82 — APPROVED** [review]

**Review by Andersson007 — APPROVED** [review]
LGTM

**Comment by frenck** [comment]
I think it should state why...
If exceptions are made, make sure you comment why such an exception is made, or make a reference.

**Comment by felixfontein** [comment]
> I think it should state why...
> If exceptions are made, make sure you comment why such an exception is made, or make a reference.

The merge commit references this PR, and this PR references the discussion. I think that's enough. I don't want to clutter the module even more.

> Nobody in 2 or 3 years is going to directly understand why there is a "DO NOT CONTACT" or "DO NOT RE-ADD GITHUB HANDLE" in the code. Furthermore, was it needed to all caps it?

All caps is less easy to overlook than a regular comment.

**Comment by felixfontein** [comment]
Thanks everyone. This is hopefully the end of all unsolicited pings/CCs from our side.

**Comment by frenck** [comment]
Thanks, Felix, appreciated 👍

**Pull request merged**
