### PR TITLE
BOTMETA.yml: update team_ipa

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/community.general/pull/2159#issuecomment-822665853

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
BOTMETA.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
@justchris1 could you please approve it?

**Review by justchris1 — APPROVED** [review]

**Comment by justchris1** [comment]
@Andersson007 Is there some document explaining how the 'shipit' and any other functions work?  Or some examples?  Thanks!

**Comment by Andersson007** [comment]
@justchris1 https://github.com/ansible-community/collection_bot/blob/main/ISSUE_HELP.md
basically, if you think that a PR is good enough to be merged (as a review checklist you can use https://github.com/ansible-collections/community.postgresql/blob/main/REVIEW_CHECKLIST.md for a while, we'll add the checklist to this repo later), just put shipit in a separate line in the PR

**Comment by Andersson007** [comment]
long story short:), if you're listed in .github.com/BOTMETA.yml as a maintainer of a file / directory and put shipit in a related PR, this shipit will be counted by bot. Then, if another maintainer put their shipit, the bot will automatically merge the PR.
You can check bot status with
bot_status

**Comment by Andersson007** [comment]
please explore the bot's message ^ :) You can see a few counters there. It needs 2 maintainer_shipits to merge automatically.
It's just an example, no need here because we will merge it manually.

**Comment by Andersson007** [comment]
CC @felixfontein

**Comment by felixfontein** [comment]
@justchris1 thanks!

**Pull request merged**
