### PR TITLE
java_cert: import certificate+key bundle from pkcs12

### LINKED ISSUE #2460: module java_cert: PKCS12 file not properly imported into keystore
### Summary

When importing a PKCS12 file into a Java keystore using the `java_cert` module on Ansible 3.3.0 (which uses `community.general 2.5.1`) only the certificate is imported but not the key.

This worked well in Ansible 3.2.0 (wich used `community.general 2.4.0`).

### Issue Type

Bug Report

### Component Name

java_cert

### Ansible Version

Ansible 3.3.0
Ansible-Base 2.10.9
community.general 2.5.1

### Configuration

_No response_

### OS / Environment

Debian 9 and 10
OpenJDK 11

### Steps to Reproduce

Running this sample play on Ansible 3.2.0 and 3.3.0 yields different results:

```yaml
    - name: Create certificate
      command: >
        openssl req -newkey rsa:4096
              -x509
              -sha256
              -nodes
              -out /tmp/example.crt
              -keyout /tmp/example.key
              -subj /C=DE/ST=Berlin/L=Berlin/O=ACME/OU=ACME/CN=localhost

    - name: Generate p12 file for certificate and private key
      command: >
        openssl pkcs12
                -export
                -in /tmp/example.crt
                -inkey /tmp/example.key
                -name localhost
                -out /tmp/example.pksc12
                -password "pass:123456789"

    - name: Generate Java keystore from p12 keystore
      java_cert:
        keystore_create: true
        keystore_pass: 123456789
        keystore_path: /tmp/keystore.jks
        pkcs12_alias: localhost
        pkcs12_path: /tmp/example.pksc12
        pkcs12_password: 123456789
        cert_alias: localhost
        state: present

    - name: Print keystore content
      command: >
        keytool
          -list
          -v
          -keystore /tmp/keystore.jks
          -storepass 123456789
```

### Expected Results

Run with Ansible 3.2.0 this results in a correct keystore that contains a `PrivateKeyEntry`:
```
    Keystore type: PKCS12
    Keystore provider: SUN
  
    Your keystore contains 1 entry
  
    Alias name: localhost
    Creation date: May 6, 2021
    Entry type: PrivateKeyEntry
    Certificate chain length: 1
    Certificate[1]:
    Owner: CN=localhost, OU=ACME, O=ACME, L=Berlin, ST=Berlin, C=DE
    Issuer: CN=localhost, OU=ACME, O=ACME, L=Berlin, ST=Berlin, C=DE
```

### Actual Results

Where on Ansible 3.3.0 the resulting keystore is
```
    Keystore type: PKCS12
    Keystore provider: SUN
  
    Your keystore contains 1 entry
  
    Alias name: localhost
    Creation date: May 6, 2021
    Entry type: trustedCertEntry
  
    Owner: CN=localhost, OU=ACME, O=ACME, L=Berlin, ST=Berlin, C=DE
    Issuer: CN=localhost, OU=ACME, O=ACME, L=Berlin, ST=Berlin, C=DE
```
It only has certificate entry but not a `PrivateKeyEntry` entry. Software using the keystore will thus complain with errors like "The KeyStore xxx does not contain any keys"

Running the play in verbose mode shows that the `keytool` commands executed differ between the Ansible versions.

On Ansible 3.2.0 `keytool -importkeystore` is invoked:
```
keytool -importkeystore -noprompt -destkeystore ''/tmp/keystore.jks'' -srcstoretype PKCS12 -deststorepass ''********'' -destkeypass ''********'' -srckeystore ''/tmp/example.pksc12'' -srcstorepass ''********'' -srcalias ''localhost'' -destalias ''localhost'' '
```

whereas on Ansible 3.3.0 `keytool -importcert` is executed:
```
  cmd:
  - keytool
  - -importcert
  - -noprompt
  - -keystore
  - /tmp/keystore.jks
  - -file
  - /tmp/tmps1mpw0xn
  - -alias
  - localhost
```
This command is only suitable for importing certificates but not a keystore as a whole:
```
$ keytool -importcert --help
keytool -importcert [OPTION]...

Imports a certificate or a certificate chain
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by quidame**
##### SUMMARY

When importing a certificate from a PKCS#12 keystore, import the private key as well (if it is bundled in the source keystore). Fix a regression from #2008. Also clarify documentation about PKCS#12 as source of import.

Fixes #2460 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

java_cert

##### ADDITIONAL INFORMATION

none

### CODE REVIEW

**Comment by quidame** [comment]
@k-c-p, could you try with this version if you have the opportunity ?

**Comment by felixfontein** [comment]
@quidame thanks for working on this! Could you maybe also add something to the integration tests to avoid regressions later on?

**Comment by k-c-p** [comment]
> could you try with this version if you have the opportunity ?

I gave it a try. Looks good so far :+1:.

**Comment by absynth76** [comment]
thanks for your time 

shipit

**Review by felixfontein — COMMENTED** [review]
LGTM

**Comment by absynth76** [comment]
shipit

**Comment by felixfontein** [comment]
@quidame thanks for fixing this!
@k-c-p @absynth76 thanks for testing and reviewing!

**Pull request merged**
