### PR TITLE
Bug/syslog json exception

### LINKED ISSUE #407: syslog_json output plugin is broken
##### SUMMARY

Output callback syslog_json is broken. Reported on https://github.com/ansible/ansible/issues/69686

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

syslog_json.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'debug', u'syslog_json']
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Centos 7.8

##### STEPS TO REPRODUCE

Just set the output callback to use syslog_json

```yaml
ANSIBLE_STDOUT_CALLBACK=syslog_json ansible-playbook -vvv -i inv_file.yml playbooks.yml
```

##### EXPECTED RESULTS

it wouldn't throw an exception

##### ACTUAL RESULTS

```paste below
ERROR! Unexpected Exception, this is probably a bug: 'CallbackModule' object has no attribute '_load_name'
the full traceback was:

Traceback (most recent call last):  File "/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 99, in run
    self._tqm.load_callbacks()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 134, in load_callbacks
    self._stdout_callback = callback_loader.get(self._stdout_callback)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 578, in get
    obj = obj(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/callback/syslog_json.py", line 70, in __init__
    self.set_options()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.py", line 99, in set_options
    self._plugin_options = C.config.get_plugin_options(get_plugin_class(self), self._load_name, keys=task_keys, variables=var_options, direct=direct)
AttributeError: 'CallbackModule' object has no attribute '_load_name'
```

### PR DESCRIPTION
**Pull request by imjoseangel**
##### SUMMARY

Fixes #407 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

syslog_json.py

##### ADDITIONAL INFORMATION

Debug is thrown to the syslog

```paste below
May 24 19:28:29 debian ansible-command: task execution OK; host: localhost; message: {#012    "changed": false,#012    "foo": "VARIABLE IS NOT DEFINED!"#012}
May 24 19:28:29 debian ansible-command: task execution OK; host: localhost; message: {#012    "bar | bool": "VARIABLE IS NOT DEFINED!",#012    "changed": false#012}
May 24 19:28:30 debian ansible-command: task execution OK; host: localhost; message: {#012    "bar | bool | ternary('Eremutonto','Eremutontisimo')": "VARIABLE IS NOT DEFINED!",#012    "changed": false#012}
```

### CODE REVIEW

**Comment by felixfontein** [comment]
@imjoseangel thanks for fixing this!

**Comment by Akasurde** [comment]
@felixfontein @imjoseangel Do you think we need a backport for this?

**Comment by imjoseangel** [comment]
@Akasurde From my point of view yes.

**Comment by felixfontein** [comment]
@Akasurde probably yes. The same problem might also affect other callback plugins.

**Comment by Akasurde** [comment]
@imjoseangel Could you please create a backport 2.9? Thanks in advance.

**Comment by imjoseangel** [comment]
@Akasurde @felixfontein sure! I will work on it ASAP

**Comment by imjoseangel** [comment]
@Akasurde @felixfontein https://github.com/ansible/ansible/pull/69695

Regards

**Comment by Andersson007** [comment]
@imjoseangel hi, if you interested in being added as a maintainer of this plugin to .github/BOTMETA.yml, please let me know (your shipit will be counted for automerge, you'll get related notifications, nothing obligatory, of course). Just a fyi:) Thanks again for the great work!

**Comment by imjoseangel** [comment]
Sure! Go ahead. Thank you!

**Pull request merged**
