### PR TITLE
Remove tleguern from team_virt

### PR DESCRIPTION
**Pull request by tleguern**
Hello,

I am stepping down as a reviewer for the proxmox modules as I do not work with proxmox anymore and thus can't really test or review properly.

Regards.

### CODE REVIEW

**Comment by felixfontein** [comment]
@tleguern thank you very much for all your work on this collection and its proxmox modules!

To fix the sanity tests, can you add a `ignore: tleguern` line next to https://github.com/ansible-collections/community.general/blob/89578ac69d99d682692c00f02e564a78598d9cc3/.github/BOTMETA.yml#L994 ? (GH unfortunately doesn't allow me to add a suggestion there...)

**Comment by felixfontein** [comment]
bot_skip

**Comment by tleguern** [comment]
Is this better?

**Comment by felixfontein** [comment]
@tleguern yes, thank you very much! Now the BOTMETA sanity test is happy again :)

**Comment by felixfontein** [comment]
@tleguern thanks again for creating and maintaining (some of) the proxmox modules!

**Comment by tleguern** [comment]
It was nice working with you and the ansible team, I hope I will be able to contribute again in the future :)

**Pull request merged**
